/**
 * Dynamic course catalog — auto-generated from deep-courses.json.
 * All 205 non-AKM1 courses with full metadata.
 */

export interface CatalogCourse {
  id: string;
  slug: string;
  category: string;
  title: string;
  level: "nyborjare" | "intermediar" | "avancerad";
  minutes: number;
  summary: string;
  chapterCount: number;
  hasLynch: boolean;
  hasGraham: boolean;
  hasAk1: boolean;
  hasHistory: boolean;
}

export const DYNAMIC_CATALOG: CatalogCourse[] = [
  {
    "id": "KM-001",
    "slug": "km-001-bokforingens-grunder",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Bokföringens grunder",
    "level": "nyborjare",
    "minutes": 22,
    "summary": "Dubbel italiensk bokföring, debet/kredit, och hur resultaträkningen knyter till balansräkningen via eget kapital.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-002",
    "slug": "km-002-forvaltningsberattelsen",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Förvaltningsberättelsen",
    "level": "intermediar",
    "minutes": 18,
    "summary": "Årets händelser, risker och framtid i textform — och det styrelsen väljer att inte nämna.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-003",
    "slug": "km-003-kassaflodesanalysen",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Kassaflödesanalysen",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Kassaflödet visar pengarna som rör sig — obrukbara resultat visar sig här först.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-004",
    "slug": "km-004-noter",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Noter — den dolda informationen",
    "level": "avancerad",
    "minutes": 28,
    "summary": "Avskrivningsprinciper, pensionsåtaganden, relaterade parter — noterna bär halva sanningen.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-005",
    "slug": "km-005-eget-kapital-utdelningar",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Eget kapital & utdelningar",
    "level": "nyborjare",
    "minutes": 16,
    "summary": "Vart vinsten tar vägen: utdelning, återinvestering eller aktieåterköp — och hur det bokförs.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-006",
    "slug": "km-006-kvartalsrapporten",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Kvartalsrapporten",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Q1–Q4-rapporterna och varför säsongseffekter och engångsposter lurar den som bara läser årsredovisningen.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-007",
    "slug": "km-007-dcf",
    "category": "VÄRDERINGSMETODER",
    "title": "DCF — diskonterade kassaflöden",
    "level": "avancerad",
    "minutes": 35,
    "summary": "Framtida kassaflöden diskonterade till idag — den mest teoretiskt rena värderingsmetoden.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-008",
    "slug": "km-008-wacc",
    "category": "VÄRDERINGSMETODER",
    "title": "WACC — vägd kapitalkostnad",
    "level": "avancerad",
    "minutes": 30,
    "summary": "Beräkna avkastningskrav med hänsyn till både skuld- och equity-kostnad — DCF-motorns bränsle.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-009",
    "slug": "km-009-pe",
    "category": "VÄRDERINGSMETODER",
    "title": "P/E — Price-to-Earnings djupdykning",
    "level": "nyborjare",
    "minutes": 14,
    "summary": "Den mest citerade multiplen — dess styrkor, fällor och varför den varierar mellan sektorer.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-010",
    "slug": "km-010-evebit",
    "category": "VÄRDERINGSMETODER",
    "title": "EV/EBIT — renare än P/E",
    "level": "intermediar",
    "minutes": 18,
    "summary": "Företagsvärde över driftsresultat — ignorerar kapitalstruktur och ger jämförbarhet över bolag.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-011",
    "slug": "km-011-relativ-vardering",
    "category": "VÄRDERINGSMETODER",
    "title": "Relativ värdering — peer comps",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Jämför bolagets multiplar mot direkta konkurrenter — och varför 'billig' inte alltid betyder 'köpvärd'.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-012",
    "slug": "km-012-sum-of-the-parts-sotp",
    "category": "VÄRDERINGSMETODER",
    "title": "Sum-of-the-Parts (SOTP)",
    "level": "avancerad",
    "minutes": 26,
    "summary": "Värdera konglomerat och investmentbolag som summan av sina delar — och förstå varför rabatten uppstår.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-013",
    "slug": "km-013-volatilitet-standardavvikelse",
    "category": "RISKHANTERING & PORTFÖLJTEORI",
    "title": "Volatilitet & standardavvikelse",
    "level": "intermediar",
    "minutes": 18,
    "summary": "Den vanligaste mätaren på prisförändringars storlek — och varför den fångar bara halva bilden.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-014",
    "slug": "km-014-korrelation-diversifiering",
    "category": "RISKHANTERING & PORTFÖLJTEORI",
    "title": "Korrelation & diversifiering",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Varför orelaterade tillgångar stabiliserar portföljen — och varför 'diversifiering' är missförstått.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-015",
    "slug": "km-015-beta-capm",
    "category": "RISKHANTERING & PORTFÖLJTEORI",
    "title": "Beta & CAPM",
    "level": "avancerad",
    "minutes": 24,
    "summary": "Mät systematisk risk mot marknaden — och varför CAPM är en förenkling som ändå används.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-016",
    "slug": "km-016-sharpe-kvot",
    "category": "RISKHANTERING & PORTFÖLJTEORI",
    "title": "Sharpe-kvot",
    "level": "intermediar",
    "minutes": 16,
    "summary": "Avkastning per enhet risk — två portföljer kan ha samma avkastning, Sharpe skiljer den bättre.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-017",
    "slug": "km-017-position-sizing-kelly-kriteriet",
    "category": "RISKHANTERING & PORTFÖLJTEORI",
    "title": "Position sizing & Kelly-kriteriet",
    "level": "avancerad",
    "minutes": 28,
    "summary": "Hur stor del av kapitalet ska du satsa på en position? Kelly ger ett matematiskt svar — och dess varning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-018",
    "slug": "km-018-forlustaversion",
    "category": "BETEENDEFINANS",
    "title": "Förlustaversion",
    "level": "nyborjare",
    "minutes": 15,
    "summary": "Kahneman & Tverskys prospect theory — och varför vi klamrar oss fast vid förlorare.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-019",
    "slug": "km-019-bekraftelsefalla",
    "category": "BETEENDEFINANS",
    "title": "Bekräftelsefälla",
    "level": "nyborjare",
    "minutes": 14,
    "summary": "Konfirmationsbias: vi noterar bevis som stöder vår tes och ignorerar det som talar emot.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-020",
    "slug": "km-020-ankareffekt",
    "category": "BETEENDEFINANS",
    "title": "Ankareffekt",
    "level": "intermediar",
    "minutes": 16,
    "summary": "Det första priset vi ser på en aktie blir en referenspunkt — även när det borde göra det inte.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-021",
    "slug": "km-021-avskrivningsprinciper",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Avskrivningsprinciper",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Linjärt vs degressivt avskrivning. Hur avskrivningsval påverkar resultat och skatt.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-022",
    "slug": "km-022-goodwill-och-immateriella-tillgangar",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Goodwill och immateriella tillgångar",
    "level": "avancerad",
    "minutes": 25,
    "summary": "Goodwill-bildning vid uppköp. Nedskrivningstester. Hur goodwill påverkar ROE.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-023",
    "slug": "km-023-leasing",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Leasing — IFRS 16",
    "level": "avancerad",
    "minutes": 22,
    "summary": "Hur leasingavtal kapitaliseras på balansräkningen. Påverkan på skuldsättningsgrad.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-024",
    "slug": "km-024-segmentrapportering",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Segmentrapportering",
    "level": "intermediar",
    "minutes": 18,
    "summary": "Hur bolag delar upp intäkter per segment. Vad segmentnoten avslöjar om moat.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-025",
    "slug": "km-025-pensionsataganden",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Pensionsåtaganden",
    "level": "avancerad",
    "minutes": 24,
    "summary": "Hur pensioner bokförs. Dolda skulder i pensionsnoter.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-026",
    "slug": "km-026-relaterade-parter",
    "category": "BOKFÖRING & ÅRSREDOVISNING",
    "title": "Relaterade parter",
    "level": "avancerad",
    "minutes": 20,
    "summary": "Transaktioner med ägare, VD och dotterbolag. Red flags i relaterade-part-noten.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-027",
    "slug": "km-027-pegratio",
    "category": "VÄRDERINGSMETODER",
    "title": "PEG-ratio",
    "level": "intermediar",
    "minutes": 20,
    "summary": "P/E / tillväxt. Lynch's favorit. När PEG fungerar och missleder.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-028",
    "slug": "km-028-reverse-dcf",
    "category": "VÄRDERINGSMETODER",
    "title": "Reverse DCF",
    "level": "avancerad",
    "minutes": 28,
    "summary": "Vilken tillväxt implicerar dagens pris? Om marknaden är realistisk.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-029",
    "slug": "km-029-scenarioanalys",
    "category": "VÄRDERINGSMETODER",
    "title": "Scenario-analys",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Tre scenarier med sannolikheter. Vägt värde. Hantera osäkerhet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-030",
    "slug": "km-030-margin-of-safety",
    "category": "VÄRDERINGSMETODER",
    "title": "Margin of safety",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "Köp under intrinsic value med 30% marginal. Hur beräkna och applicera.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-031",
    "slug": "km-031-var",
    "category": "RISKHANTERING & PORTFÖLJTEORI",
    "title": "VaR — Value at Risk",
    "level": "avancerad",
    "minutes": 26,
    "summary": "Maximal förlust vid 95% konfidens. Begränsningar och fällor.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-032",
    "slug": "km-032-stresstesting-portfoljen",
    "category": "RISKHANTERING & PORTFÖLJTEORI",
    "title": "Stress-testing portföljen",
    "level": "avancerad",
    "minutes": 28,
    "summary": "Simulera kriser: räntehöjning, recession, branschchock.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-033",
    "slug": "km-033-tailrisk-hedging",
    "category": "RISKHANTERING & PORTFÖLJTEORI",
    "title": "Tail-risk hedging",
    "level": "avancerad",
    "minutes": 24,
    "summary": "Skydd mot extrema händelser. Options som försäkring.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-034",
    "slug": "km-034-drawdownanalys",
    "category": "RISKHANTERING & PORTFÖLJTEORI",
    "title": "Drawdown-analys",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Maximal nedgång från topp. Psykologi och compounding.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-035",
    "slug": "km-035-flockbeteende",
    "category": "BETEENDEFINANS",
    "title": "Flockbeteende",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Herd mentality, FOMO. Dot-com, Bitcoin, GameStop.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-036",
    "slug": "km-036-overconfidence",
    "category": "BETEENDEFINANS",
    "title": "Överconfidence",
    "level": "intermediar",
    "minutes": 18,
    "summary": "90% tror de slår marknaden. Ödmjukhet som edge.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-037",
    "slug": "km-037-disposition-effect",
    "category": "BETEENDEFINANS",
    "title": "Disposition effect",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Sälj vinnare, behåll förlorare. Vanligaste orsaken till underprestation.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-038",
    "slug": "km-038-techsektorn",
    "category": "SEKTORANALYS",
    "title": "Tech-sektorn",
    "level": "intermediar",
    "minutes": 28,
    "summary": "Nätverkseffekter, IP, skalbarhet, Rule of 40.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-039",
    "slug": "km-039-pharmasektorn",
    "category": "SEKTORANALYS",
    "title": "Pharma-sektorn",
    "level": "avancerad",
    "minutes": 30,
    "summary": "Pharma-moat via patent. Pipeline-värdering.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-040",
    "slug": "km-040-banksektorn",
    "category": "SEKTORANALYS",
    "title": "Bank-sektorn",
    "level": "intermediar",
    "minutes": 28,
    "summary": "Bank-specifik AKM1. Skuld är normalt. Kapitaltäckning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-041",
    "slug": "km-041-industrisektorn",
    "category": "SEKTORANALYS",
    "title": "Industri-sektorn",
    "level": "intermediar",
    "minutes": 26,
    "summary": "Industri-moat via process, skala, varumärke.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-042",
    "slug": "km-042-fastighetsektorn",
    "category": "SEKTORANALYS",
    "title": "Fastighet-sektorn",
    "level": "intermediar",
    "minutes": 28,
    "summary": "Fastighetsvärdering: direktavkastning, NAV, räntekänslighet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-043",
    "slug": "km-043-energisektorn",
    "category": "SEKTORANALYS",
    "title": "Energi-sektorn",
    "level": "intermediar",
    "minutes": 26,
    "summary": "Olje-major vs förnybar. Oljepris som cykel-drivare.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-044",
    "slug": "km-044-konsumentsektorn",
    "category": "SEKTORANALYS",
    "title": "Konsument-sektorn",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Varumärke-moat, fast fashion vs premium, e-handel.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-045",
    "slug": "km-045-materialsektorn",
    "category": "SEKTORANALYS",
    "title": "Material-sektorn",
    "level": "intermediar",
    "minutes": 26,
    "summary": "Cyklisk, råvaru-exponerad. V03 dämpar volatilitet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-046",
    "slug": "km-046-telekomsektorn",
    "category": "SEKTORANALYS",
    "title": "Telekom-sektorn",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Infrastruktur-moat, kapitalintensiv, utdelning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-047",
    "slug": "km-047-utilitysektorn",
    "category": "SEKTORANALYS",
    "title": "Utility-sektorn",
    "level": "nyborjare",
    "minutes": 20,
    "summary": "Monopol, reglerad avkastning, stabil utdelning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-048",
    "slug": "km-048-halsovardsektorn",
    "category": "SEKTORANALYS",
    "title": "Hälsovård-sektorn",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Medtech: produkt-moat, regulatorisk. Demografisk tailwind.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-049",
    "slug": "km-049-bolagsskatt-206",
    "category": "SVENSK BOLAGSSKATT & JURIDIK",
    "title": "Bolagsskatt 20,6%",
    "level": "nyborjare",
    "minutes": 16,
    "summary": "Svensk bolagsskatt. Vinst före/efter skatt.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-050",
    "slug": "km-050-utdelningsskatt-30",
    "category": "SVENSK BOLAGSSKATT & JURIDIK",
    "title": "Utdelningsskatt 30%",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "Beskattning av utdelning vs återköp. V20 i AKM1 1.1.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-051",
    "slug": "km-051-kapitalvinstskatt",
    "category": "SVENSK BOLAGSSKATT & JURIDIK",
    "title": "Kapitalvinstskatt",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "30% på vinst. 70% avdrag för förlust.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-052",
    "slug": "km-052-isk",
    "category": "SVENSK BOLAGSSKATT & JURIDIK",
    "title": "ISK — schablonskatt",
    "level": "intermediar",
    "minutes": 20,
    "summary": "ISK vs aktiedepå. När lönar det?",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-053",
    "slug": "km-053-312reglerna",
    "category": "SVENSK BOLAGSSKATT & JURIDIK",
    "title": "3:12-reglerna",
    "level": "avancerad",
    "minutes": 26,
    "summary": "Fåmansföretag. Gränsbelopp, huvudregel vs förenklingsregel.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-054",
    "slug": "km-054-ranta",
    "category": "MAKROEKONOMI & RÄNTA",
    "title": "Ränta — priset på pengar",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "Centralbanker, styrränta, DCF och diskonteringsränta.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-055",
    "slug": "km-055-inflation",
    "category": "MAKROEKONOMI & RÄNTA",
    "title": "Inflation — 2% målet",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "KPI, kärninflation. Prissättningsmakt som skydd.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-056",
    "slug": "km-056-centralbanker",
    "category": "MAKROEKONOMI & RÄNTA",
    "title": "Centralbanker",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Styrränta, QE/QT, forward guidance.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-057",
    "slug": "km-057-konjunkturcykler",
    "category": "MAKROEKONOMI & RÄNTA",
    "title": "Konjunkturcykler",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Cykliska vs defensiva sektorer. Identifiera cykelfas.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-058",
    "slug": "km-058-valutor",
    "category": "MAKROEKONOMI & RÄNTA",
    "title": "Valutor",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Valutor och svenska investeringar. Svag krona.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-059",
    "slug": "km-059-optionsgrunder",
    "category": "OPTIONS & DERIVAT",
    "title": "Options-grunder",
    "level": "nyborjare",
    "minutes": 20,
    "summary": "Call och put. Premie, strike, förfall.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-060",
    "slug": "km-060-covered-calls",
    "category": "OPTIONS & DERIVAT",
    "title": "Covered calls",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Sälj call på aktier du äger. Inkomst + capad uppsida.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-061",
    "slug": "km-061-protective-puts",
    "category": "OPTIONS & DERIVAT",
    "title": "Protective puts",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Köp put som försäkring. Skyddar nedsida.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-062",
    "slug": "km-062-blackscholes",
    "category": "OPTIONS & DERIVAT",
    "title": "Black-Scholes",
    "level": "avancerad",
    "minutes": 30,
    "summary": "Matematiken bakom options-priser.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-063",
    "slug": "km-063-direktavkastning",
    "category": "UTDELNINGSSTRATEGI",
    "title": "Direktavkastning",
    "level": "nyborjare",
    "minutes": 16,
    "summary": "Utdelning/kurs. Hög yield = bra eller value trap?",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-064",
    "slug": "km-064-utdelningstillvaxt",
    "category": "UTDELNINGSSTRATEGI",
    "title": "Utdelnings-tillväxt",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Dividend Aristocrats. Växande utdelning slår hög yield.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-065",
    "slug": "km-065-dogs-of-the-dow",
    "category": "UTDELNINGSSTRATEGI",
    "title": "Dogs of the Dow",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Köp 10 högsta yield. Filtrera med AKM1.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-066",
    "slug": "km-066-utdelning-vs-aterkop",
    "category": "UTDELNINGSSTRATEGI",
    "title": "Utdelning vs återköp",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Två sätt att returnera kapital. V20 i AKM1 1.1.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-067",
    "slug": "km-067-investmentbolag",
    "category": "PRIVATE EQUITY & INVESTMENTBOLAG",
    "title": "Investmentbolag — NAV-rabatt",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Holding company discount. Varför under NAV.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-068",
    "slug": "km-068-wallenbergsfaren",
    "category": "PRIVATE EQUITY & INVESTMENTBOLAG",
    "title": "Wallenberg-sfären",
    "level": "intermediar",
    "minutes": 26,
    "summary": "Investor AB, Industrivärden. Aktivt ägande.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-069",
    "slug": "km-069-orderbok-och-prissattning",
    "category": "AKTIEMARKNADEN I PRAKTIKEN",
    "title": "Orderbok och prissättning",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "Börsen. Buy/sell orders, spread, likviditet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "KM-070",
    "slug": "km-070-natmaklare-i-sverige",
    "category": "AKTIEMARKNADEN I PRAKTIKEN",
    "title": "Nätmäklare i Sverige",
    "level": "nyborjare",
    "minutes": 16,
    "summary": "Välja nätmäklare. Courtage, ISK, valutakostnad.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-01",
    "slug": "ts-01-elliott-wave",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Elliott Wave — 5-vågs impuls",
    "level": "avancerad",
    "minutes": 28,
    "summary": "5-vågs impulsmönster och Fibonacci-retracements.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-02",
    "slug": "ts-02-elliott-wave",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Elliott Wave — 3-vågs korrektion",
    "level": "avancerad",
    "minutes": 25,
    "summary": "Korrektionsmönster: zigzag, flat, triangle.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-03",
    "slug": "ts-03-fibonacciretracements",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Fibonacci-retracements",
    "level": "intermediar",
    "minutes": 22,
    "summary": "38.2%, 50%, 61.8% — vilka nivåer som matter.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-04",
    "slug": "ts-04-fibonacciextensions",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Fibonacci-extensions",
    "level": "intermediar",
    "minutes": 20,
    "summary": "161.8%, 261.8% — prismål med Fibonacci.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-05",
    "slug": "ts-05-gannvinklar",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Gann-vinklar",
    "level": "avancerad",
    "minutes": 30,
    "summary": "1×1, 2×1 vinklar. Tid och pris konvergerar.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-06",
    "slug": "ts-06-ganncyklar",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Gann-cyklar",
    "level": "avancerad",
    "minutes": 26,
    "summary": "60-årscykel, 20-årscykel, 90-dagarscykel.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-07",
    "slug": "ts-07-lucastalserie",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Lucas-talserie",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Lucas-tal som tids-cykel-indikatorer.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-08",
    "slug": "ts-08-volymanalys",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Volym-analys",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Volym bekräftar pris. Wyckoff. OBV.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-09",
    "slug": "ts-09-volymprofiler",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Volym-profiler — VPOC",
    "level": "avancerad",
    "minutes": 28,
    "summary": "Volume Profile, Point of Control, Value Area.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-10",
    "slug": "ts-10-ak1ts-25cellers-matris",
    "category": "AK1TS FÖRDJUPNING",
    "title": "AK1TS 25-cellers matris",
    "level": "avancerad",
    "minutes": 35,
    "summary": "5 teorier × 5 tidshorisonter = konfluens.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-11",
    "slug": "ts-11-candlestickmonster",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Candlestick-mönster",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "Doji, Hammer, Engulfing, Morning Star.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-12",
    "slug": "ts-12-moving-averages",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Moving Averages",
    "level": "nyborjare",
    "minutes": 16,
    "summary": "50-dagars, 200-dagars, golden cross, death cross.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-13",
    "slug": "ts-13-rsi",
    "category": "AK1TS FÖRDJUPNING",
    "title": "RSI",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Overbought/oversold, divergens.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-14",
    "slug": "ts-14-macd",
    "category": "AK1TS FÖRDJUPNING",
    "title": "MACD",
    "level": "intermediar",
    "minutes": 20,
    "summary": "MACD-linje, signal-linje, histogram.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-15",
    "slug": "ts-15-bollinger-bands",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Bollinger Bands",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Squeeze, expansion. Volatilitet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-16",
    "slug": "ts-16-stod-och-motstand",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Stöd och motstånd",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "Varför priser studsar. Psykologi, orderbok.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-17",
    "slug": "ts-17-trendlinjer",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Trendlinjer",
    "level": "nyborjare",
    "minutes": 16,
    "summary": "Rita giltiga trendlinjer.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-18",
    "slug": "ts-18-chartmonster",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Chart-mönster",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Huvu-och-skuldror, trianglar.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-19",
    "slug": "ts-19-fibonaccitidszoner",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Fibonacci-tidszoner",
    "level": "avancerad",
    "minutes": 22,
    "summary": "Tids-cykel: 5, 8, 13, 21, 34 dagar.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-20",
    "slug": "ts-20-harmoniska-monster",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Harmoniska mönster",
    "level": "avancerad",
    "minutes": 30,
    "summary": "Gartley, Bat, Crab, Butterfly.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-01",
    "slug": "pc-01-case-atlas-copco",
    "category": "PRAKTISKA CASE",
    "title": "Case: Atlas Copco",
    "level": "intermediar",
    "minutes": 30,
    "summary": "Fyll i alla 20 AKM1 1.1-variabler för Atlas Copco.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-02",
    "slug": "pc-02-case-astrazeneca",
    "category": "PRAKTISKA CASE",
    "title": "Case: AstraZeneca",
    "level": "avancerad",
    "minutes": 35,
    "summary": "Värdering av pharma-pipeline. V13 patent.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-03",
    "slug": "pc-03-case-swedbank",
    "category": "PRAKTISKA CASE",
    "title": "Case: Swedbank",
    "level": "intermediar",
    "minutes": 28,
    "summary": "Bank-specifik AKM1. V10 för banker.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-04",
    "slug": "pc-04-case-investor-ab",
    "category": "PRAKTISKA CASE",
    "title": "Case: Investor AB",
    "level": "intermediar",
    "minutes": 26,
    "summary": "NAV-rabatt och aktivt ägande.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-05",
    "slug": "pc-05-case-volvo-ab",
    "category": "PRAKTISKA CASE",
    "title": "Case: Volvo AB",
    "level": "intermediar",
    "minutes": 28,
    "summary": "Cyklisk industri. Elförskjutning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-06",
    "slug": "pc-06-case-hm",
    "category": "PRAKTISKA CASE",
    "title": "Case: H&M",
    "level": "intermediar",
    "minutes": 25,
    "summary": "V14 urholkas. V07 som indikator.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-07",
    "slug": "pc-07-case-sinch",
    "category": "PRAKTISKA CASE",
    "title": "Case: Sinch",
    "level": "avancerad",
    "minutes": 32,
    "summary": "V19 + V10 = katastrof.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-08",
    "slug": "pc-08-case-precise-biometrics",
    "category": "PRAKTISKA CASE",
    "title": "Case: Precise Biometrics",
    "level": "avancerad",
    "minutes": 35,
    "summary": "Full reproducerbar analys. Alla 20 variabler.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-09",
    "slug": "pc-09-case-novo-nordisk",
    "category": "PRAKTISKA CASE",
    "title": "Case: Novo Nordisk",
    "level": "avancerad",
    "minutes": 30,
    "summary": "V13 + V14 extrem moat. GLP-1.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-10",
    "slug": "pc-10-case-ericsson",
    "category": "PRAKTISKA CASE",
    "title": "Case: Ericsson",
    "level": "intermediar",
    "minutes": 28,
    "summary": "Cyklisk + teknologi-risk. 5G.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-01",
    "slug": "rk-01-kapitalforbranning",
    "category": "RISKHANTERING",
    "title": "Kassatäckning & runway — nyemissionsrisk",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Beräkna burn och runway — räcker kassan så nyemission undviks?",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-02",
    "slug": "rk-02-emissionrisk",
    "category": "RISKHANTERING",
    "title": "Emission-risk — utspädning",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Emissioner utspäddar. TERP-beräkning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-03",
    "slug": "rk-03-skuldfalla",
    "category": "RISKHANTERING",
    "title": "Skuldfälla",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Identifiera ohållbar skuld. Räntetäckning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-04",
    "slug": "rk-04-likviditetskris",
    "category": "RISKHANTERING",
    "title": "Likviditetskris",
    "level": "avancerad",
    "minutes": 26,
    "summary": "SVB, Credit Suisse. Early warning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-05",
    "slug": "rk-05-cykelrisk",
    "category": "RISKHANTERING",
    "title": "Cykelrisk",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Cykliska billiga vid topp, dyra vid botten.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-06",
    "slug": "rk-06-regulatorisk-risk",
    "category": "RISKHANTERING",
    "title": "Regulatorisk risk",
    "level": "avancerad",
    "minutes": 26,
    "summary": "AML, miljökrav. Bedöma sannolikhet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-07",
    "slug": "rk-07-valutarisk",
    "category": "RISKHANTERING",
    "title": "Valutarisk",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Exportbolag och svag krona.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-08",
    "slug": "rk-08-ranterisk",
    "category": "RISKHANTERING",
    "title": "Ränterisk — duration",
    "level": "avancerad",
    "minutes": 28,
    "summary": "Duration-mismatch. SVB-fallet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-09",
    "slug": "rk-09-koncentrationsrisk",
    "category": "RISKHANTERING",
    "title": "Koncentrationsrisk",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "Max 5% per position. Kelly.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-10",
    "slug": "rk-10-korrelationsrisk",
    "category": "RISKHANTERING",
    "title": "Korrelationsrisk",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Korrelation i kriser. Tail-risk.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-11",
    "slug": "rk-11-bedrageririsk",
    "category": "RISKHANTERING",
    "title": "Bedrägeri-risk",
    "level": "avancerad",
    "minutes": 30,
    "summary": "Wirecard, Enron. Red flags.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-12",
    "slug": "rk-12-black-swanrisk",
    "category": "RISKHANTERING",
    "title": "Black swan-risk",
    "level": "avancerad",
    "minutes": 26,
    "summary": "Covid, krig. Antifragilitet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-01",
    "slug": "pf-01-portfoljbyggande",
    "category": "PORTFÖLJHANTERING",
    "title": "Portfölj-byggande",
    "level": "nyborjare",
    "minutes": 20,
    "summary": "Diversifierad portfölj. Sektorsfördelning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-02",
    "slug": "pf-02-position-sizing",
    "category": "PORTFÖLJHANTERING",
    "title": "Position sizing",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "Max 5%. Rätt storlek.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-03",
    "slug": "pf-03-diversifiering",
    "category": "PORTFÖLJHANTERING",
    "title": "Diversifiering",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Orelaterade sektorer. 2008.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-04",
    "slug": "pf-04-rebalansering",
    "category": "PORTFÖLJHANTERING",
    "title": "Rebalansering",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Sälj vinnare, köp förlorare.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-05",
    "slug": "pf-05-utdelningsstrategi",
    "category": "PORTFÖLJHANTERING",
    "title": "Utdelnings-strategi",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Inkomst vs tillväxt. Payout ratio.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-06",
    "slug": "pf-06-aterinvestering",
    "category": "PORTFÖLJHANTERING",
    "title": "Återinvestering",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "Rule of 72. Compounding.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-07",
    "slug": "pf-07-krishantering",
    "category": "PORTFÖLJHANTERING",
    "title": "Kris-hantering",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Fall 30%: panik eller opportunity?",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-08",
    "slug": "pf-08-isk-vs-aktiedepa",
    "category": "PORTFÖLJHANTERING",
    "title": "ISK vs Aktiedepå",
    "level": "nyborjare",
    "minutes": 16,
    "summary": "Schablonskatt vs kapitalvinst.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-01",
    "slug": "se-01-saassektorn",
    "category": "SEKTORANALYS",
    "title": "SaaS-sektorn",
    "level": "avancerad",
    "minutes": 28,
    "summary": "ARR, net retention, Rule of 40.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-02",
    "slug": "se-02-halvledarsektorn",
    "category": "SEKTORANALYS",
    "title": "Halvledar-sektorn",
    "level": "avancerad",
    "minutes": 30,
    "summary": "ASML monopol. Cyklisk men moat.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-03",
    "slug": "se-03-forsvarssektorn",
    "category": "SEKTORANALYS",
    "title": "Försvars-sektorn",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Långsiktiga kontrakt. Geopolitik.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-04",
    "slug": "se-04-logistiksektorn",
    "category": "SEKTORANALYS",
    "title": "Logistik-sektorn",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Nätverkseffekter. E-handel.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-05",
    "slug": "se-05-lyxsektorn",
    "category": "SEKTORANALYS",
    "title": "Lyx-sektorn",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Varumärke = allt. Konstgjord brist.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SJ-01",
    "slug": "sj-01-utlandsk-kallskatt",
    "category": "SKATT & JURIDIK",
    "title": "Utländsk källskatt",
    "level": "intermediar",
    "minutes": 22,
    "summary": "15% källskatt. W-8BEN.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SJ-02",
    "slug": "sj-02-cryptobeskattning",
    "category": "SKATT & JURIDIK",
    "title": "Crypto-beskattning",
    "level": "intermediar",
    "minutes": 22,
    "summary": "30% på vinst. Varje affär skattepliktig.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SJ-03",
    "slug": "sj-03-bolagsstamma-och-rostratt",
    "category": "SKATT & JURIDIK",
    "title": "Bolagsstämma och rösträtt",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "A/B-aktier, rösträtt, stämmor.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "BF-01",
    "slug": "bf-01-tillganglighetsfalla",
    "category": "BETEENDEFINANS",
    "title": "Tillgänglighetsfälla",
    "level": "intermediar",
    "minutes": 16,
    "summary": "Recency bias. Överviktar nylig info.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "BF-02",
    "slug": "bf-02-sunk-cost",
    "category": "BETEENDEFINANS",
    "title": "Sunk cost",
    "level": "nyborjare",
    "minutes": 15,
    "summary": "Fatta beslut oberoende av tidigare kostnad.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "BF-03",
    "slug": "bf-03-mental-accounting",
    "category": "BETEENDEFINANS",
    "title": "Mental accounting",
    "level": "intermediar",
    "minutes": 18,
    "summary": "Olika fickor. Hus-pengar.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "BF-04",
    "slug": "bf-04-investera-som-en-robot",
    "category": "BETEENDEFINANS",
    "title": "Investera som en robot",
    "level": "avancerad",
    "minutes": 24,
    "summary": "Regler under stress. Buffett.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "MK-01",
    "slug": "mk-01-bnp-och-tillvaxt",
    "category": "MAKROEKONOMI",
    "title": "BNP och tillväxt",
    "level": "nyborjare",
    "minutes": 16,
    "summary": "BNP, recession. Makro och aktier.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "MK-02",
    "slug": "mk-02-arbetsloshet",
    "category": "MAKROEKONOMI",
    "title": "Arbetslöshet",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Arbetslöshet, löneinflation, Phillips.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "MK-03",
    "slug": "mk-03-handelsbalans",
    "category": "MAKROEKONOMI",
    "title": "Handelsbalans",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Export/import. Valuta.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "MK-04",
    "slug": "mk-04-statsobligationer",
    "category": "MAKROEKONOMI",
    "title": "Statsobligationer",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Yield curve. Inverterad = recession?",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "MK-05",
    "slug": "mk-05-geopolitik",
    "category": "MAKROEKONOMI",
    "title": "Geopolitik",
    "level": "avancerad",
    "minutes": 26,
    "summary": "Krig, sanktioner. Svenska bolag.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "VM-01",
    "slug": "vm-01-grahams-formel",
    "category": "VÄRDERINGSMETODER",
    "title": "Graham's formel",
    "level": "intermediar",
    "minutes": 22,
    "summary": "V = EPS × (8.5 + 2g).",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "VM-02",
    "slug": "vm-02-intrinsic-value",
    "category": "VÄRDERINGSMETODER",
    "title": "Intrinsic value",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "Vad intrinsic value är. Margin of safety.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "UD-01",
    "slug": "ud-01-payout-ratio",
    "category": "UTDELNINGSSTRATEGI",
    "title": "Payout ratio",
    "level": "intermediar",
    "minutes": 18,
    "summary": "Utdelning/vinst. Hög = risk.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "UD-02",
    "slug": "ud-02-aterinvestering",
    "category": "UTDELNINGSSTRATEGI",
    "title": "Återinvestering",
    "level": "nyborjare",
    "minutes": 18,
    "summary": "Compounding. Rule of 72.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-21",
    "slug": "ts-21-fibonaccikluster",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Fibonacci-kluster",
    "level": "avancerad",
    "minutes": 24,
    "summary": "När flera Fibonacci-nivåer konvergerar — starkare stöd/motstånd.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-22",
    "slug": "ts-22-elliott-wave",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Elliott Wave — multipla tidshorisonter",
    "level": "avancerad",
    "minutes": 28,
    "summary": "Hur Elliott-vågor på olika tidshorisonter relaterar till varandra.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-23",
    "slug": "ts-23-volume-spread-analysis-vsa",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Volume Spread Analysis (VSA)",
    "level": "avancerad",
    "minutes": 26,
    "summary": "Tom Williams metod. Hur spridning mellan volym och pris avslöjar institutionell aktivitet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-24",
    "slug": "ts-24-order-flow",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Order Flow — marknadsdjup",
    "level": "avancerad",
    "minutes": 30,
    "summary": "Läsa orderboken. Bid/ask-storlek, iceberg-ordrar, limit-ordrar.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "TS-25",
    "slug": "ts-25-market-profile",
    "category": "AK1TS FÖRDJUPNING",
    "title": "Market Profile",
    "level": "avancerad",
    "minutes": 28,
    "summary": "TPO (Time Price Opportunity). Value area, POC, auction market theory.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-11",
    "slug": "pc-11-case-boliden",
    "category": "PRAKTISKA CASE",
    "title": "Case: Boliden — gruvor",
    "level": "intermediar",
    "minutes": 26,
    "summary": "Cyklisk + råvaru. V03 dämpar volatilitet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-12",
    "slug": "pc-12-case-skf",
    "category": "PRAKTISKA CASE",
    "title": "Case: SKF — industri-moat",
    "level": "intermediar",
    "minutes": 25,
    "summary": "V13 + V14. Premium-pris = stabil bruttomarginal.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-13",
    "slug": "pc-13-case-ssab",
    "category": "PRAKTISKA CASE",
    "title": "Case: SSAB — cyklisk stål",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Nisch (Hardox). V13 moat i commoditiserad bransch.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-14",
    "slug": "pc-14-case-electrolux",
    "category": "PRAKTISKA CASE",
    "title": "Case: Electrolux — disruption",
    "level": "intermediar",
    "minutes": 26,
    "summary": "V14 hotas. V07 som varning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-15",
    "slug": "pc-15-case-kambi",
    "category": "PRAKTISKA CASE",
    "title": "Case: Kambi — tech-nisch",
    "level": "avancerad",
    "minutes": 28,
    "summary": "V02 ARR + V13 process. V19 bränning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-16",
    "slug": "pc-16-case-beijer-ref",
    "category": "PRAKTISKA CASE",
    "title": "Case: Beijer Ref — kyl-distribution",
    "level": "intermediar",
    "minutes": 24,
    "summary": "V15 skala + V12 stabilitet = compounder.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-17",
    "slug": "pc-17-case-sandvik",
    "category": "PRAKTISKA CASE",
    "title": "Case: Sandvik — verktyg",
    "level": "intermediar",
    "minutes": 25,
    "summary": "V13 + V14. Premium-pris dämpar cykel.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-18",
    "slug": "pc-18-case-oresund",
    "category": "PRAKTISKA CASE",
    "title": "Case: Öresund — investmentbolag",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Deep value. V04 NAV-rabatt. Risk: value trap.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-19",
    "slug": "pc-19-case-hoganas",
    "category": "PRAKTISKA CASE",
    "title": "Case: Höganäs — järnpulver-monopol",
    "level": "avancerad",
    "minutes": 26,
    "summary": "V13 + V15 extrem moat i nisch.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PC-20",
    "slug": "pc-20-case-essity",
    "category": "PRAKTISKA CASE",
    "title": "Case: Essity — hygienvaror",
    "level": "intermediar",
    "minutes": 25,
    "summary": "V14 + V12 inflationsskyddad moat.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-13",
    "slug": "rk-13-gdpr-och-datarisk",
    "category": "RISKHANTERING",
    "title": "GDPR och data-risk",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Dataintrång och GDPR-böter. Facebook-Cambridge Analytica.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-14",
    "slug": "rk-14-esgrisk",
    "category": "RISKHANTERING",
    "title": "ESG-risk — miljö och sociala",
    "level": "intermediar",
    "minutes": 22,
    "summary": "BP Deepwater, 3M PFAS. ESG → finansiell risk.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "RK-15",
    "slug": "rk-15-cykelrisk",
    "category": "RISKHANTERING",
    "title": "Cykel-risk — konjunkturkänslighet",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Industri, bank, lyx = cykliska. Bygg cykel-resistent portfölj.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-09",
    "slug": "pf-09-taxloss-harvesting",
    "category": "PORTFÖLJHANTERING",
    "title": "Tax-loss harvesting",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Sälj förlorare före årsskiftet. 30-dagars regeln.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-10",
    "slug": "pf-10-longshort",
    "category": "PORTFÖLJHANTERING",
    "title": "Long/short — hedging",
    "level": "avancerad",
    "minutes": 28,
    "summary": "Hedga med puts eller short. Risk/reward.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-11",
    "slug": "pf-11-koncentrerad-portfolj",
    "category": "PORTFÖLJHANTERING",
    "title": "Koncentrerad portfölj — 5-10 bolag",
    "level": "avancerad",
    "minutes": 26,
    "summary": "Buffett/Munger. Få bolag, djup förståelse.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-12",
    "slug": "pf-12-arsrapportering",
    "category": "PORTFÖLJHANTERING",
    "title": "Årsrapportering — portfölj-review",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Årlig genomgång. Uppdatera AKM1, sälj låg, köj hög.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-06",
    "slug": "se-06-finanssektorn",
    "category": "SEKTORANALYS",
    "title": "Finans-sektorn — försäkring",
    "level": "intermediar",
    "minutes": 26,
    "summary": "Försäkring: float-moat. Asset management: AUM-nätverk.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-07",
    "slug": "se-07-detailhandel",
    "category": "SEKTORANALYS",
    "title": "Detailhandel — skala och e-handel",
    "level": "intermediar",
    "minutes": 26,
    "summary": "Skala-moat. Category killer vs nisch. E-handel-disruption.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-08",
    "slug": "se-08-media",
    "category": "SEKTORANALYS",
    "title": "Media — innehåll och streaming",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Innehålls-moat (Disney, Netflix). Streaming-disruption.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-09",
    "slug": "se-09-bil",
    "category": "SEKTORANALYS",
    "title": "Bil — disruption och el",
    "level": "intermediar",
    "minutes": 26,
    "summary": "Disruption (Tesla), cykel, kapitalintensiv. Elförskjutning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-10",
    "slug": "se-10-flyg",
    "category": "SEKTORANALYS",
    "title": "Flyg — cykel och bränsle",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Extremt cykliska. Bränslekostnad. Låga marginaler.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-11",
    "slug": "se-11-krypto",
    "category": "SEKTORANALYS",
    "title": "Krypto — extrem risk",
    "level": "avancerad",
    "minutes": 28,
    "summary": "Volatilt, regulatorisk osäkerhet. V18, V19 dominerar. Anti-casino.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-12",
    "slug": "se-12-spel",
    "category": "SEKTORANALYS",
    "title": "Spel — licens och regulation",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Licens-moat, regulatorisk risk. Kambi som B2B.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-13",
    "slug": "se-13-utbildning",
    "category": "SEKTORANALYS",
    "title": "Utbildning — återkommande intäkter",
    "level": "intermediar",
    "minutes": 22,
    "summary": "ARR-modell, regering-kund. V12 stabilitet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-14",
    "slug": "se-14-livsmedel",
    "category": "SEKTORANALYS",
    "title": "Livsmedel — staplar och varumärke",
    "level": "nyborjare",
    "minutes": 20,
    "summary": "Varumärke + distribution. Inflationsskydd.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SE-15",
    "slug": "se-15-logistik",
    "category": "SEKTORANALYS",
    "title": "Logistik — nätverk",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Nätverkseffekter (FedEx, UPS). Infrastruktur-moat.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SJ-04",
    "slug": "sj-04-optionsbeskattning",
    "category": "SKATT & JURIDIK",
    "title": "Options-beskattning",
    "level": "avancerad",
    "minutes": 24,
    "summary": "Personaloptioner: beskattning vid utnyttjande. Kvalificerade vs okvalificerade.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "SJ-05",
    "slug": "sj-05-kapitalforsakring-vs-isk",
    "category": "SKATT & JURIDIK",
    "title": "Kapitalförsäkring vs ISK",
    "level": "intermediar",
    "minutes": 20,
    "summary": "KF vs ISK. Skillnader, fördelar, nackdelar.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "BF-05",
    "slug": "bf-05-ankareffekt",
    "category": "BETEENDEFINANS",
    "title": "Ankareffekt — snitt irrelevant",
    "level": "intermediar",
    "minutes": 18,
    "summary": "Första priset = referens. 'Averaging down' fara.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "BF-06",
    "slug": "bf-06-tillganglighetsheuristik",
    "category": "BETEENDEFINANS",
    "title": "Tillgänglighetsheuristik",
    "level": "intermediar",
    "minutes": 16,
    "summary": "Vi överviktar lättillgänglig information.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "BF-07",
    "slug": "bf-07-framstegseffekt",
    "category": "BETEENDEFINANS",
    "title": "Framstegseffekt",
    "level": "nyborjare",
    "minutes": 14,
    "summary": "Vi fortsätter beteenden som belönats tidigare, även när de slutar fungera.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "BF-08",
    "slug": "bf-08-priming",
    "category": "BETEENDEFINANS",
    "title": "Priming — omedvetna influenser",
    "level": "intermediar",
    "minutes": 16,
    "summary": "Hur miljön påverkar beslut utan att vi märker det.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "BF-09",
    "slug": "bf-09-haloeffekt",
    "category": "BETEENDEFINANS",
    "title": "Halo-effekt",
    "level": "nyborjare",
    "minutes": 14,
    "summary": "En bra egenskap (t.ex. varumärke) gör oss positiva till allt om bolaget.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "BF-10",
    "slug": "bf-10-dunningkruger",
    "category": "BETEENDEFINANS",
    "title": "Dunning-Kruger",
    "level": "intermediar",
    "minutes": 18,
    "summary": "Nybörjare överskattar, experter underskattar. Kunskap = osäkerhet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "MK-06",
    "slug": "mk-06-penningpolitik",
    "category": "MAKROEKONOMI",
    "title": "Penningpolitik — QE och QT",
    "level": "avancerad",
    "minutes": 24,
    "summary": "Quantitative easing/tightening. Hur centralbanker expanderar/krymper penningmängd.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "MK-07",
    "slug": "mk-07-fiscal-politik",
    "category": "MAKROEKONOMI",
    "title": "Fiscal politik — statsbudget",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Regeringens budget. Underskott, statsskuld, stimulans.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "MK-08",
    "slug": "mk-08-omvand-yield-curve",
    "category": "MAKROEKONOMI",
    "title": "Omvänd yield curve",
    "level": "avancerad",
    "minutes": 20,
    "summary": "När korta räntor > långa. Historisk recession-signal.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "MK-09",
    "slug": "mk-09-deflation-vs-inflation",
    "category": "MAKROEKONOMI",
    "title": "Deflation vs inflation",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Deflation farligare än inflation. Japan-exemplet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "MK-10",
    "slug": "mk-10-oljepris",
    "category": "MAKROEKONOMI",
    "title": "Oljepris — makro-drivrutin",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Oljeprisets påverkan på inflation, tillväxt, valutor.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "VM-03",
    "slug": "vm-03-multipelval",
    "category": "VÄRDERINGSMETODER",
    "title": "Multipel-val — när använda vilken",
    "level": "intermediar",
    "minutes": 22,
    "summary": "P/E vs EV/EBITDA vs P/S. När vilken multipel är bäst.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "VM-04",
    "slug": "vm-04-cyklisk-justering",
    "category": "VÄRDERINGSMETODER",
    "title": "Cyklisk justering — Shiller P/E",
    "level": "avancerad",
    "minutes": 24,
    "summary": "CAPE (Cyclically Adjusted P/E). 10-års genomsnitt. Robert Shiller.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "VM-05",
    "slug": "vm-05-realoptioner",
    "category": "VÄRDERINGSMETODER",
    "title": "Realoptioner",
    "level": "avancerad",
    "minutes": 28,
    "summary": "Värdera flexibilitet. Optioner i verkliga tillgångar. R&D som option.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "VM-06",
    "slug": "vm-06-dividend-discount-model-ddm",
    "category": "VÄRDERINGSMETODER",
    "title": "Dividend Discount Model (DDM)",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Värdera bolag via framtida utdelningar. Gordon Growth Model.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "VM-07",
    "slug": "vm-07-free-cash-flow-yield",
    "category": "VÄRDERINGSMETODER",
    "title": "Free Cash Flow Yield",
    "level": "intermediar",
    "minutes": 20,
    "summary": "FCF / börsvärde. Buffett's favorit. Ägarens verkliga avkastning.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "VM-08",
    "slug": "vm-08-evsales",
    "category": "VÄRDERINGSMETODER",
    "title": "EV/Sales",
    "level": "intermediar",
    "minutes": 18,
    "summary": "Företagsvärde / omsättning. När P/S inte räcker.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "VM-09",
    "slug": "vm-09-pricetocashflow",
    "category": "VÄRDERINGSMETODER",
    "title": "Price-to-Cash-Flow",
    "level": "intermediar",
    "minutes": 20,
    "summary": "P/CF — svårare att manipulera än P/E. Kassaflöde vs vinst.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "VM-10",
    "slug": "vm-10-assetbased-valuation",
    "category": "VÄRDERINGSMETODER",
    "title": "Asset-based valuation",
    "level": "avancerad",
    "minutes": 24,
    "summary": "Värdera baserat på nettoförmögenhet. Liquidationsvärde. Graham's cigar butt.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "UD-03",
    "slug": "ud-03-dividend-aristocrats",
    "category": "UTDELNINGSSTRATEGI",
    "title": "Dividend Aristocrats",
    "level": "intermediar",
    "minutes": 22,
    "summary": "25+ år av höjningar. Coca-Cola, P&G. Hållbarhet.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "UD-04",
    "slug": "ud-04-utdelningsfallor",
    "category": "UTDELNINGSSTRATEGI",
    "title": "Utdelnings-fällor",
    "level": "intermediar",
    "minutes": 20,
    "summary": "Hög yield = risk. Sänkningar. Valeant, GE.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "UD-05",
    "slug": "ud-05-drip",
    "category": "UTDELNINGSSTRATEGI",
    "title": "DRIP — automatisk återinvestering",
    "level": "nyborjare",
    "minutes": 16,
    "summary": "Dividend Reinvestment Plan. Compounding utan beslut.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "UD-06",
    "slug": "ud-06-svenska-utdelningsaktier",
    "category": "UTDELNINGSSTRATEGI",
    "title": "Svenska utdelnings-aktier",
    "level": "intermediar",
    "minutes": 22,
    "summary": "Swedbank 6%, H&M 4%, Atlas Copco 2%. Svensk utdelningskultur.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "UD-07",
    "slug": "ud-07-utdelningskalender",
    "category": "UTDELNINGSSTRATEGI",
    "title": "Utdelnings-kalender",
    "level": "nyborjare",
    "minutes": 16,
    "summary": "När bolag delar ut. Ex-datum, record date, betalningsdatum.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "UD-08",
    "slug": "ud-08-speciella-utdelningar",
    "category": "UTDELNINGSSTRATEGI",
    "title": "Speciella utdelningar",
    "level": "intermediar",
    "minutes": 18,
    "summary": "Extra utdelningar vid uppköp, försäljning. Engångsposter.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-13",
    "slug": "pf-13-esgportfolj",
    "category": "PORTFÖLJHANTERING",
    "title": "ESG-portfölj",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Bygg portfölj med ESG-fokus. Gröna bolag. Risker och möjligheter.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "PF-14",
    "slug": "pf-14-pensionssparande",
    "category": "PORTFÖLJHANTERING",
    "title": "Pensionssparande",
    "level": "nyborjare",
    "minutes": 20,
    "summary": "IPS, pensionsförsäkring. Långsiktigt sparande 30+ år.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "BF-11",
    "slug": "bf-11-kognitiv-bias",
    "category": "BETEENDEFINANS",
    "title": "Kognitiv bias — komplett lista",
    "level": "intermediar",
    "minutes": 24,
    "summary": "Alla kognitiva biaser som påverkar investeringar. 20+ typer.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "MK-11",
    "slug": "mk-11-kinaekonomin",
    "category": "MAKROEKONOMI",
    "title": "Kina-ekonomin",
    "level": "avancerad",
    "minutes": 26,
    "summary": "Kinas påverkan på globala marknader. Tillväxt, skulder, geopolitik.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  },
  {
    "id": "VM-11",
    "slug": "vm-11-waccfallor",
    "category": "VÄRDERINGSMETODER",
    "title": "WACC-fällor",
    "level": "avancerad",
    "minutes": 22,
    "summary": "Vanliga misstag med WACC. Beta-instabilitet, riskpremie-debatt.",
    "chapterCount": 6,
    "hasLynch": true,
    "hasGraham": true,
    "hasAk1": true,
    "hasHistory": true
  }
];

export const CATALOG_CATEGORIES = ["AK1TS FÖRDJUPNING", "AKTIEMARKNADEN I PRAKTIKEN", "BETEENDEFINANS", "BOKFÖRING & ÅRSREDOVISNING", "MAKROEKONOMI", "MAKROEKONOMI & RÄNTA", "OPTIONS & DERIVAT", "PORTFÖLJHANTERING", "PRAKTISKA CASE", "PRIVATE EQUITY & INVESTMENTBOLAG", "RISKHANTERING", "RISKHANTERING & PORTFÖLJTEORI", "SEKTORANALYS", "SKATT & JURIDIK", "SVENSK BOLAGSSKATT & JURIDIK", "UTDELNINGSSTRATEGI", "VÄRDERINGSMETODER"];

export const TOTAL_CATALOG_COURSES = 205;
