/**
 * LÄRVÄGSKARTAN — GENERERAD FIL (våg 88): RÖR EJ FÖR HAND.
 * Genererad av scripts/bygg-larvag-karta.ts ur public/deep-courses.json
 * (490 kurser) + kurs-access.ts (kraverFas) + kurstips.ts
 * V-spåret (vIndex 0–19, -1 = utanför). Deterministisk: samma indata ⇒
 * samma fil. niva = level-tolkning (0=allmän, 1=Nybörjare,
 * 2=Intermediär, 3=Avancerad). Fas-fördelningen: 448 gratis,
 * 18 Fas 2, 24 Fas 3.
 *
 * Pedagogisk plattform — inte investeringsråd.
 */

/** En kurs i lärvägskartan — den vy raknaLarvag (larvag.ts) rankar mot. */
export type LarvagKurs = {
  slug: string;
  titel: string;
  /** Rå kategori ur kursdata (versal, t.ex. "TILLVÄXT"). */
  kategori: string;
  /** Level-tolkning: 0 = allmän, 1 = Nybörjare, 2 = Intermediär, 3 = Avancerad. */
  niva: number;
  /** Kravd fas (kurs-access): 0 = gratis, 2 eller 3. */
  kraverFas: number;
  /** Index i kurstips V-spåret (0–19), -1 = utanför spåret. */
  vIndex: number;
  /** Total speltid i minuter. */
  minuter: number;
};

/** Hela kursuniversumet i deep-courses.json-ordning (deterministisk brytning). */
export const LARVAG_KARTA: readonly LarvagKurs[] = [
  { slug: "v01-forsaljningstillvaxt", titel: "Försäljningstillväxt", kategori: "TILLVÄXT", niva: 1, kraverFas: 0, vIndex: 0, minuter: 44 },
  { slug: "v02-arr-tillvaxt", titel: "ARR-tillväxt (återkommande intäkter)", kategori: "TILLVÄXT", niva: 2, kraverFas: 0, vIndex: 1, minuter: 46 },
  { slug: "v03-intaktsdiversifiering", titel: "Intäktsdiversifiering", kategori: "TILLVÄXT", niva: 1, kraverFas: 0, vIndex: 2, minuter: 43 },
  { slug: "v04-ps", titel: "P/S (Price-to-Sales)", kategori: "VÄRDERING", niva: 1, kraverFas: 0, vIndex: 3, minuter: 44 },
  { slug: "v05-pb", titel: "P/B (Price-to-Book)", kategori: "VÄRDERING", niva: 1, kraverFas: 0, vIndex: 4, minuter: 44 },
  { slug: "v06-ev-ebitda", titel: "EV/EBITDA", kategori: "VÄRDERING", niva: 2, kraverFas: 0, vIndex: 5, minuter: 44 },
  { slug: "v07-bruttomarginal", titel: "Bruttomarginal", kategori: "LÖNSAMHET", niva: 1, kraverFas: 0, vIndex: 6, minuter: 44 },
  { slug: "v08-ebitda-marginal", titel: "EBITDA-marginal", kategori: "LÖNSAMHET", niva: 2, kraverFas: 0, vIndex: 7, minuter: 44 },
  { slug: "v09-roe", titel: "ROE (Return on Equity)", kategori: "LÖNSAMHET", niva: 2, kraverFas: 0, vIndex: 8, minuter: 44 },
  { slug: "v10-skuldsattningsgrad", titel: "Skuldsättningsgrad", kategori: "STABILITET", niva: 1, kraverFas: 0, vIndex: 9, minuter: 43 },
  { slug: "v11-likviditet", titel: "Likviditet (Kvick)", kategori: "STABILITET", niva: 1, kraverFas: 0, vIndex: 10, minuter: 43 },
  { slug: "v12-intaktsstabilitet", titel: "Intäktsstabilitet", kategori: "STABILITET", niva: 2, kraverFas: 0, vIndex: 11, minuter: 43 },
  { slug: "v13-patent-ip", titel: "Patent & Immateriella rättigheter", kategori: "MOAT", niva: 2, kraverFas: 0, vIndex: 12, minuter: 48 },
  { slug: "v14-varumarke", titel: "Varumärke & Kundlojalitet", kategori: "MOAT", niva: 2, kraverFas: 0, vIndex: 13, minuter: 48 },
  { slug: "v15-natverkseffekter", titel: "Nätverkseffekter", kategori: "MOAT", niva: 3, kraverFas: 0, vIndex: 14, minuter: 48 },
  { slug: "v16-produktlanseringar", titel: "Produktlanseringar", kategori: "KATALYSATOR", niva: 2, kraverFas: 0, vIndex: 15, minuter: 48 },
  { slug: "v17-avtal-partnerskap", titel: "Avtal & Partnerskap", kategori: "KATALYSATOR", niva: 2, kraverFas: 0, vIndex: 16, minuter: 48 },
  { slug: "v18-regulatoriska", titel: "Regulatoriska katalysatorer", kategori: "KATALYSATOR", niva: 3, kraverFas: 0, vIndex: 17, minuter: 48 },
  { slug: "v19-kapitalforbranning", titel: "Kapitalförbränning & Emission-risk", kategori: "RISK", niva: 3, kraverFas: 0, vIndex: 18, minuter: 67 },
  { slug: "v20-aterekop-egna-aktier", titel: "Återköp av egna aktier", kategori: "KAPITALSTRUKTUR", niva: 2, kraverFas: 0, vIndex: 19, minuter: 47 },
  { slug: "km-001-bokforingens-grunder", titel: "Bokföringens grunder", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "km-002-forvaltningsberattelsen", titel: "Förvaltningsberättelsen", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "km-003-kassaflodesanalysen", titel: "Kassaflödesanalysen", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "km-004-noter", titel: "Noter — den dolda informationen", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "km-005-eget-kapital-utdelningar", titel: "Eget kapital & utdelningar", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "km-006-kvartalsrapporten", titel: "Kvartalsrapporten", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-007-dcf", titel: "DCF — diskonterade kassaflöden", kategori: "VÄRDERINGSMETODER", niva: 3, kraverFas: 0, vIndex: -1, minuter: 35 },
  { slug: "km-008-wacc", titel: "WACC — vägd kapitalkostnad", kategori: "VÄRDERINGSMETODER", niva: 3, kraverFas: 0, vIndex: -1, minuter: 30 },
  { slug: "km-009-pe", titel: "P/E — Price-to-Earnings djupdykning", kategori: "VÄRDERINGSMETODER", niva: 1, kraverFas: 0, vIndex: -1, minuter: 14 },
  { slug: "km-010-evebit", titel: "EV/EBIT — renare än P/E", kategori: "VÄRDERINGSMETODER", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "km-011-relativ-vardering", titel: "Relativ värdering — peer comps", kategori: "VÄRDERINGSMETODER", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "km-012-sum-of-the-parts-sotp", titel: "Sum-of-the-Parts (SOTP)", kategori: "VÄRDERINGSMETODER", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "km-013-volatilitet-standardavvikelse", titel: "Volatilitet & standardavvikelse", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "km-014-korrelation-diversifiering", titel: "Korrelation & diversifiering", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-015-beta-capm", titel: "Beta & CAPM", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "km-016-sharpe-kvot", titel: "Sharpe-kvot", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "km-017-position-sizing-kelly-kriteriet", titel: "Position sizing & Kelly-kriteriet", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "km-018-forlustaversion", titel: "Förlustaversion", kategori: "BETEENDEFINANS", niva: 1, kraverFas: 0, vIndex: -1, minuter: 15 },
  { slug: "km-019-bekraftelsefalla", titel: "Bekräftelsefälla", kategori: "BETEENDEFINANS", niva: 1, kraverFas: 0, vIndex: -1, minuter: 14 },
  { slug: "km-020-ankareffekt", titel: "Ankareffekt", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "km-021-avskrivningsprinciper", titel: "Avskrivningsprinciper", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-022-goodwill-och-immateriella-tillgangar", titel: "Goodwill och immateriella tillgångar", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 25 },
  { slug: "km-023-leasing", titel: "Leasing — IFRS 16", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "km-024-segmentrapportering", titel: "Segmentrapportering", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "km-025-pensionsataganden", titel: "Pensionsåtaganden", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "km-026-relaterade-parter", titel: "Relaterade parter", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-027-pegratio", titel: "PEG-ratio", kategori: "VÄRDERINGSMETODER", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-028-reverse-dcf", titel: "Reverse DCF", kategori: "VÄRDERINGSMETODER", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "km-029-scenarioanalys", titel: "Scenario-analys", kategori: "VÄRDERINGSMETODER", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "km-030-margin-of-safety", titel: "Margin of safety", kategori: "VÄRDERINGSMETODER", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "km-031-var", titel: "VaR — Value at Risk", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "km-032-stresstesting-portfoljen", titel: "Stress-testing portföljen", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "km-033-tailrisk-hedging", titel: "Tail-risk hedging", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "km-034-drawdownanalys", titel: "Drawdown-analys", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-035-flockbeteende", titel: "Flockbeteende", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-036-overconfidence", titel: "Overconfidence", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "km-037-disposition-effect", titel: "Disposition effect", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-038-techsektorn", titel: "Tech-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "km-039-pharmasektorn", titel: "Pharma-sektorn", kategori: "SEKTORANALYS", niva: 3, kraverFas: 0, vIndex: -1, minuter: 30 },
  { slug: "km-040-banksektorn", titel: "Bank-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "km-041-industrisektorn", titel: "Industri-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "km-042-fastighetsektorn", titel: "Fastighet-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "km-043-energisektorn", titel: "Energi-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "km-044-konsumentsektorn", titel: "Konsument-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "km-045-materialsektorn", titel: "Material-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "km-046-telekomsektorn", titel: "Telekom-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "km-047-utilitysektorn", titel: "Utility-sektorn", kategori: "SEKTORANALYS", niva: 1, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-048-halsovardsektorn", titel: "Hälsovård-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "km-049-bolagsskatt-206", titel: "Bolagsskatt 20,6%", kategori: "SVENSK BOLAGSSKATT & JURIDIK", niva: 1, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "km-050-utdelningsskatt-30", titel: "Utdelningsskatt 30%", kategori: "SVENSK BOLAGSSKATT & JURIDIK", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "km-051-kapitalvinstskatt", titel: "Kapitalvinstskatt", kategori: "SVENSK BOLAGSSKATT & JURIDIK", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "km-052-isk", titel: "ISK — schablonskatt", kategori: "SVENSK BOLAGSSKATT & JURIDIK", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-053-312reglerna", titel: "3:12-reglerna", kategori: "SVENSK BOLAGSSKATT & JURIDIK", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "km-054-ranta", titel: "Ränta — priset på pengar", kategori: "MAKROEKONOMI & RÄNTA", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "km-055-inflation", titel: "Inflation — 2% målet", kategori: "MAKROEKONOMI & RÄNTA", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "km-056-centralbanker", titel: "Centralbanker", kategori: "MAKROEKONOMI & RÄNTA", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "km-057-konjunkturcykler", titel: "Konjunkturcykler", kategori: "MAKROEKONOMI & RÄNTA", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "km-058-valutor", titel: "Valutor", kategori: "MAKROEKONOMI & RÄNTA", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "km-059-optionsgrunder", titel: "Options-grunder", kategori: "OPTIONS & DERIVAT", niva: 1, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-060-covered-calls", titel: "Covered calls", kategori: "OPTIONS & DERIVAT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "km-061-protective-puts", titel: "Protective puts", kategori: "OPTIONS & DERIVAT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "km-062-blackscholes", titel: "Black-Scholes", kategori: "OPTIONS & DERIVAT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 30 },
  { slug: "km-063-direktavkastning", titel: "Direktavkastning", kategori: "UTDELNINGSSTRATEGI", niva: 1, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "km-064-utdelningstillvaxt", titel: "Utdelningstillväxt", kategori: "UTDELNINGSSTRATEGI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-065-dogs-of-the-dow", titel: "Dogs of the Dow", kategori: "UTDELNINGSSTRATEGI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "km-066-utdelning-vs-aterkop", titel: "Utdelning vs återköp", kategori: "UTDELNINGSSTRATEGI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "km-067-investmentbolag", titel: "Investmentbolag — NAV-rabatt", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "km-068-wallenbergsfaren", titel: "Wallenberg-sfären", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 2, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "km-069-orderbok-och-prissattning", titel: "Orderbok och prissättning", kategori: "AKTIEMARKNADEN I PRAKTIKEN", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "km-070-natmaklare-i-sverige", titel: "Nätmäklare i Sverige", kategori: "AKTIEMARKNADEN I PRAKTIKEN", niva: 1, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "ts-01-elliott-wave", titel: "Elliott Wave — 5-vågs impuls", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "ts-02-elliott-wave", titel: "Elliott Wave — 3-vågs korrektion", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 25 },
  { slug: "ts-03-fibonacciretracements", titel: "Fibonacci-retracements", kategori: "AK1TS FÖRDJUPNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "ts-04-fibonacciextensions", titel: "Fibonacci-extensions", kategori: "AK1TS FÖRDJUPNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "ts-05-gannvinklar", titel: "Gann-vinklar", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 30 },
  { slug: "ts-06-ganncyklar", titel: "Gann-cyklar", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "ts-07-lucastalserie", titel: "Lucas-talserie", kategori: "AK1TS FÖRDJUPNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "ts-08-volymanalys", titel: "Volym-analys", kategori: "AK1TS FÖRDJUPNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ts-09-volymprofiler", titel: "Volym-profiler — VPOC", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "ts-10-ak1ts-25cellers-matris", titel: "AK1TS 25-cellers matris", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 35 },
  { slug: "ts-11-candlestickmonster", titel: "Candlestick-mönster", kategori: "AK1TS FÖRDJUPNING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "ts-12-moving-averages", titel: "Moving Averages", kategori: "AK1TS FÖRDJUPNING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "ts-13-rsi", titel: "RSI", kategori: "AK1TS FÖRDJUPNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "ts-14-macd", titel: "MACD", kategori: "AK1TS FÖRDJUPNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "ts-15-bollinger-bands", titel: "Bollinger Bands", kategori: "AK1TS FÖRDJUPNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "ts-16-stod-och-motstand", titel: "Stöd och motstånd", kategori: "AK1TS FÖRDJUPNING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "ts-17-trendlinjer", titel: "Trendlinjer", kategori: "AK1TS FÖRDJUPNING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "ts-18-chartmonster", titel: "Chart-mönster", kategori: "AK1TS FÖRDJUPNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ts-19-fibonaccitidszoner", titel: "Fibonacci-tidszoner", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "ts-20-harmoniska-monster", titel: "Harmoniska mönster", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 30 },
  { slug: "pc-01-case-atlas-copco", titel: "Case: Atlas Copco", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 30 },
  { slug: "pc-02-case-astrazeneca", titel: "Case: AstraZeneca", kategori: "PRAKTISKA CASE", niva: 3, kraverFas: 0, vIndex: -1, minuter: 35 },
  { slug: "pc-03-case-swedbank", titel: "Case: Swedbank", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "pc-04-case-investor-ab", titel: "Case: Investor AB", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "pc-05-case-volvo-ab", titel: "Case: Volvo AB", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "pc-06-case-hm", titel: "Case: H&M", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 25 },
  { slug: "pc-07-case-sinch", titel: "Case: Sinch", kategori: "PRAKTISKA CASE", niva: 3, kraverFas: 0, vIndex: -1, minuter: 32 },
  { slug: "pc-08-case-precise-biometrics", titel: "Case: Precise Biometrics", kategori: "PRAKTISKA CASE", niva: 3, kraverFas: 0, vIndex: -1, minuter: 35 },
  { slug: "pc-09-case-novo-nordisk", titel: "Case: Novo Nordisk", kategori: "PRAKTISKA CASE", niva: 3, kraverFas: 0, vIndex: -1, minuter: 30 },
  { slug: "pc-10-case-ericsson", titel: "Case: Ericsson", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "rk-01-kapitalforbranning", titel: "Kapitalförbränning — runway", kategori: "RISKHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "rk-02-emissionrisk", titel: "Emission-risk — utspädning", kategori: "RISKHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rk-03-skuldfalla", titel: "Skuldfälla", kategori: "RISKHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "rk-04-likviditetskris", titel: "Likviditetskris", kategori: "RISKHANTERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "rk-05-cykelrisk", titel: "Cykelrisk", kategori: "RISKHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rk-06-regulatorisk-risk", titel: "Regulatorisk risk", kategori: "RISKHANTERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "rk-07-valutarisk", titel: "Valutarisk", kategori: "RISKHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "rk-08-ranterisk", titel: "Ränterisk — duration", kategori: "RISKHANTERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "rk-09-koncentrationsrisk", titel: "Koncentrationsrisk", kategori: "RISKHANTERING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "rk-10-korrelationsrisk", titel: "Korrelationsrisk", kategori: "RISKHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "rk-11-bedrageririsk", titel: "Bedrägeri-risk", kategori: "RISKHANTERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 30 },
  { slug: "rk-12-black-swanrisk", titel: "Black swan-risk", kategori: "RISKHANTERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "pf-01-portfoljbyggande", titel: "Portfölj-byggande", kategori: "PORTFÖLJHANTERING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "pf-02-position-sizing", titel: "Position sizing", kategori: "PORTFÖLJHANTERING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "pf-03-diversifiering", titel: "Diversifiering", kategori: "PORTFÖLJHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "pf-04-rebalansering", titel: "Rebalansering", kategori: "PORTFÖLJHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "pf-05-utdelningsstrategi", titel: "Utdelnings-strategi", kategori: "PORTFÖLJHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pf-06-aterinvestering", titel: "Återinvestering — portföljens ränta-på-ränta", kategori: "PORTFÖLJHANTERING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "pf-07-krishantering", titel: "Kris-hantering", kategori: "PORTFÖLJHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pf-08-isk-vs-aktiedepa", titel: "ISK vs Aktiedepå", kategori: "PORTFÖLJHANTERING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "se-01-saassektorn", titel: "SaaS-sektorn", kategori: "SEKTORANALYS", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "se-02-halvledarsektorn", titel: "Halvledar-sektorn", kategori: "SEKTORANALYS", niva: 3, kraverFas: 0, vIndex: -1, minuter: 30 },
  { slug: "se-03-forsvarssektorn", titel: "Försvars-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-04-logistiksektorn", titel: "Logistik-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-05-lyxsektorn", titel: "Lyx-sektorn", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "sj-01-utlandsk-kallskatt", titel: "Utländsk källskatt", kategori: "SKATT & JURIDIK", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "sj-02-cryptobeskattning", titel: "Crypto-beskattning", kategori: "SKATT & JURIDIK", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "sj-03-bolagsstamma-och-rostratt", titel: "Bolagsstämma och rösträtt", kategori: "SKATT & JURIDIK", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "bf-01-tillganglighetsfalla", titel: "Tillgänglighetsfälla", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "bf-02-sunk-cost", titel: "Sunk cost", kategori: "BETEENDEFINANS", niva: 1, kraverFas: 0, vIndex: -1, minuter: 15 },
  { slug: "bf-03-mental-accounting", titel: "Mental accounting", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "bf-04-investera-som-en-robot", titel: "Investera som en robot", kategori: "BETEENDEFINANS", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "mk-01-bnp-och-tillvaxt", titel: "BNP och tillväxt", kategori: "MAKROEKONOMI", niva: 1, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "mk-02-arbetsloshet", titel: "Arbetslöshet", kategori: "MAKROEKONOMI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "mk-03-handelsbalans", titel: "Handelsbalans", kategori: "MAKROEKONOMI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "mk-04-statsobligationer", titel: "Statsobligationer", kategori: "MAKROEKONOMI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "mk-05-geopolitik", titel: "Geopolitik", kategori: "MAKROEKONOMI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "vm-01-grahams-formel", titel: "Grahams formel", kategori: "VÄRDERINGSMETODER", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "vm-02-intrinsic-value", titel: "Intrinsic value", kategori: "VÄRDERINGSMETODER", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "ud-01-payout-ratio", titel: "Payout ratio", kategori: "UTDELNINGSSTRATEGI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "ud-02-aterinvestering", titel: "Återinvestering — utdelningens kraft", kategori: "UTDELNINGSSTRATEGI", niva: 1, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "ts-21-fibonaccikluster", titel: "Fibonacci-kluster", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ts-22-elliott-wave", titel: "Elliott Wave — multipla tidshorisonter", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "ts-23-volume-spread-analysis-vsa", titel: "Volume Spread Analysis (VSA)", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "ts-24-order-flow", titel: "Order Flow — marknadsdjup", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 30 },
  { slug: "ts-25-market-profile", titel: "Market Profile", kategori: "AK1TS FÖRDJUPNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "pc-11-case-boliden", titel: "Case: Boliden — gruvor", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "pc-12-case-skf", titel: "Case: SKF — industri-moat", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 25 },
  { slug: "pc-13-case-ssab", titel: "Case: SSAB — cyklisk stål", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pc-14-case-electrolux", titel: "Case: Electrolux — disruption", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "pc-15-case-kambi", titel: "Case: Kambi — tech-nisch", kategori: "PRAKTISKA CASE", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "pc-16-case-beijer-ref", titel: "Case: Beijer Ref — kyl-distribution", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pc-17-case-sandvik", titel: "Case: Sandvik — verktyg", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 25 },
  { slug: "pc-18-case-oresund", titel: "Case: Öresund — investmentbolag", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "pc-19-case-hoganas", titel: "Case: Höganäs — järnpulver-monopol", kategori: "PRAKTISKA CASE", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "pc-20-case-essity", titel: "Case: Essity — hygienvaror", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 25 },
  { slug: "pc-21-ditt-forsta-case", titel: "Ditt första case — metoden före bolagen: ett påhittat bolag, steg för steg", kategori: "PRAKTISKA CASE", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pc-22-ditt-andra-case", titel: "Ditt andra case — jämförelsen: två bolag, samma bransch, sida vid sida", kategori: "PRAKTISKA CASE", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rk-13-gdpr-och-datarisk", titel: "GDPR och data-risk", kategori: "RISKHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "rk-14-esgrisk", titel: "ESG-risk — miljö och sociala", kategori: "RISKHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "rk-15-cykelrisk", titel: "Cykel-risk — konjunkturkänslighet", kategori: "RISKHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rk-16-kontrahentrisken", titel: "Kontrahentrisken — vem står på andra sidan när det blåser", kategori: "RISKHANTERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pf-09-taxloss-harvesting", titel: "Tax-loss harvesting", kategori: "PORTFÖLJHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "pf-10-longshort", titel: "Long/short — hedging", kategori: "PORTFÖLJHANTERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "pf-11-koncentrerad-portfolj", titel: "Koncentrerad portfölj — 5-10 bolag", kategori: "PORTFÖLJHANTERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "pf-12-arsrapportering", titel: "Årsrapportering — portfölj-review", kategori: "PORTFÖLJHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "se-06-finanssektorn", titel: "Finans-sektorn — försäkring", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "se-07-detailhandel", titel: "Detaljhandel — skala och e-handel", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "se-08-media", titel: "Media — innehåll och streaming", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-09-bil", titel: "Bil — disruption och el", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "se-10-flyg", titel: "Flyg — cykel och bränsle", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-11-krypto", titel: "Krypto — extrem risk", kategori: "SEKTORANALYS", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "se-12-spel", titel: "Spel — licens och regulation", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-13-utbildning", titel: "Utbildning — återkommande intäkter", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "se-14-livsmedel", titel: "Livsmedel — staplar och varumärke", kategori: "SEKTORANALYS", niva: 1, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "se-15-logistik", titel: "Logistik — nätverk", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-16-sektoranalysens-metod", titel: "Sektoranalysens metod — tre frågor till vilken sektor som helst", kategori: "SEKTORANALYS", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-17-skogssektorn", titel: "Skog — massans cykel och ägd råvara", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-18-rederi-och-shipping", titel: "Rederi och shipping — fraktens cykel och fartyget som kapital", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-19-forsakringssektorn", titel: "Försäkringssektorn — combined ratio, floaten och de två motorerna", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-20-gruv-och-metallsektorn", titel: "Gruv- och metallsektorn — berget, kassamarginalen och den tröga cykeln", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-21-kemisektorn", titel: "Kemisektorn — kväve ur luft, fosfor ur berg", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-22-byggentreprenaden", titel: "Byggentreprenaden — fast pris, orderstocken och procenten på färdigt", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-23-stalsektorn", titel: "Stålsektorn — kapacitetens hävstång, malmen mot skrotet och förädlingstrappan", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "se-24-banksektorn", titel: "Banksektorn — räntenätet, inlåningsfranchisen och kreditförlustens klocka", kategori: "SEKTORANALYS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "sj-04-optionsbeskattning", titel: "Options-beskattning", kategori: "SKATT & JURIDIK", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "sj-05-kapitalforsakring-vs-isk", titel: "Kapitalförsäkring vs ISK", kategori: "SKATT & JURIDIK", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "sj-06-arv-gava-och-ingaende-varde", titel: "Arv, gåva och aktiernas ingående värde", kategori: "SKATT & JURIDIK", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "sj-07-forlustavdrag-och-kvotering", titel: "Förlustavdrag och kvotering — förlustens skattemekanik", kategori: "SKATT & JURIDIK", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bf-05-ankareffekt", titel: "Ankareffekt — snitt irrelevant", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "bf-06-tillganglighetsheuristik", titel: "Tillgänglighetsheuristik", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "bf-07-framstegseffekt", titel: "Framstegseffekt", kategori: "BETEENDEFINANS", niva: 1, kraverFas: 0, vIndex: -1, minuter: 14 },
  { slug: "bf-08-priming", titel: "Priming — omedvetna influenser", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "bf-09-haloeffekt", titel: "Halo-effekt", kategori: "BETEENDEFINANS", niva: 1, kraverFas: 0, vIndex: -1, minuter: 14 },
  { slug: "bf-10-dunningkruger", titel: "Dunning-Kruger", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "mk-06-penningpolitik", titel: "Penningpolitik — QE och QT", kategori: "MAKROEKONOMI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "mk-07-fiscal-politik", titel: "Finanspolitik — statsbudget", kategori: "MAKROEKONOMI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "mk-08-omvand-yield-curve", titel: "Omvänd yield curve", kategori: "MAKROEKONOMI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "mk-09-deflation-vs-inflation", titel: "Deflation vs inflation", kategori: "MAKROEKONOMI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "mk-10-oljepris", titel: "Oljepris — makro-drivrutin", kategori: "MAKROEKONOMI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "vm-03-multipelval", titel: "Multipel-val — när använda vilken", kategori: "VÄRDERINGSMETODER", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "vm-04-cyklisk-justering", titel: "Cyklisk justering — Shiller P/E", kategori: "VÄRDERINGSMETODER", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "vm-05-realoptioner", titel: "Realoptioner", kategori: "VÄRDERINGSMETODER", niva: 3, kraverFas: 0, vIndex: -1, minuter: 28 },
  { slug: "vm-06-dividend-discount-model-ddm", titel: "Dividend Discount Model (DDM)", kategori: "VÄRDERINGSMETODER", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "vm-07-free-cash-flow-yield", titel: "Free Cash Flow Yield", kategori: "VÄRDERINGSMETODER", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "vm-08-evsales", titel: "EV/Sales", kategori: "VÄRDERINGSMETODER", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "vm-09-pricetocashflow", titel: "Price-to-Cash-Flow", kategori: "VÄRDERINGSMETODER", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "vm-10-assetbased-valuation", titel: "Asset-based valuation", kategori: "VÄRDERINGSMETODER", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ud-03-dividend-aristocrats", titel: "Dividend Aristocrats", kategori: "UTDELNINGSSTRATEGI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "ud-04-utdelningsfallor", titel: "Utdelnings-fällor", kategori: "UTDELNINGSSTRATEGI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "ud-05-drip", titel: "DRIP — automatisk återinvestering", kategori: "UTDELNINGSSTRATEGI", niva: 1, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "ud-06-svenska-utdelningsaktier", titel: "Svenska utdelnings-aktier", kategori: "UTDELNINGSSTRATEGI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "ud-07-utdelningskalender", titel: "Utdelnings-kalender", kategori: "UTDELNINGSSTRATEGI", niva: 1, kraverFas: 0, vIndex: -1, minuter: 16 },
  { slug: "ud-08-speciella-utdelningar", titel: "Speciella utdelningar", kategori: "UTDELNINGSSTRATEGI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "ud-09-utdelningens-hallbarhet", titel: "Utdelningens hållbarhet — att stressa kronorna bakom utdelningen", kategori: "UTDELNINGSSTRATEGI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pf-13-esgportfolj", titel: "ESG-portfölj", kategori: "PORTFÖLJHANTERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pf-14-pensionssparande", titel: "Pensionssparande", kategori: "PORTFÖLJHANTERING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 20 },
  { slug: "pf-15-faktorpremierna", titel: "Faktorpremierna — värde, storlek, momentum och det tysta betat", kategori: "PORTFÖLJHANTERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bf-11-kognitiv-bias", titel: "Kognitiv bias — komplett lista", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bf-12-prospektteori", titel: "Prospektteori — Kahneman & Tversky", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 18 },
  { slug: "bf-13-arbitragens-granser", titel: "Arbitragens gränser — varför biasen får stanna i priserna", kategori: "BETEENDEFINANS", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bf-14-beteendeportfoljteori", titel: "Beteendeportföljteori — pyramiden med mentala konton", kategori: "BETEENDEFINANS", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bf-15-bubblans-anatomi", titel: "Bubblans anatomi — när allas misstag blir en och samma marknad", kategori: "BETEENDEFINANS", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bf-16-slumpens-serier", titel: "Slumpens serier — mönster i brus och lagen om små tal", kategori: "BETEENDEFINANS", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bf-17-nutidsbias-och-den-hyperboliska-kurvan", titel: "Nutidsbias och den hyperboliska kurvan — tidens psykologi", kategori: "BETEENDEFINANS", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bf-18-kompetensillusionen", titel: "Kompetensillusionen — när skickligheten är en berättelse", kategori: "BETEENDEFINANS", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "mk-11-kinaekonomin", titel: "Kina-ekonomin", kategori: "MAKROEKONOMI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 26 },
  { slug: "mk-12-demografins-klocka", titel: "Demografins klocka — åldrandets aritmetik och den redan slagna prognosen", kategori: "MAKROEKONOMI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "vm-11-waccfallor", titel: "WACC-fällor", kategori: "VÄRDERINGSMETODER", niva: 3, kraverFas: 0, vIndex: -1, minuter: 22 },
  { slug: "portfolj-ekosystemet", titel: "Från aktie till portfölj — 5×5×4-ekosystemet i praktiken", kategori: "PRAKTISKA CASE", niva: 2, kraverFas: 0, vIndex: -1, minuter: 55 },
  { slug: "the-intelligent-investor", titel: "The Intelligent Investor — Graham: KOMPLETT (alla kapitel)", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 180 },
  { slug: "mina-basta-investeringar", titel: "Mina bästa investeringar — Peter Lynch: KOMPLETT (alla kapitel)", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 180 },
  { slug: "blue-ocean-strategy", titel: "Blue Ocean Strategy — Kim & Mauborgne: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 184 },
  { slug: "zero-to-one", titel: "Zero to One — Peter Thiel: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 184 },
  { slug: "a-random-walk-down-wall-street", titel: "A Random Walk Down Wall Street — Malkiel: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 198 },
  { slug: "security-analysis", titel: "Security Analysis — Graham & Dodd: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 240 },
  { slug: "technical-analysis-financial-markets", titel: "Technical Analysis of the Financial Markets — Murphy: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 220 },
  { slug: "common-stocks-uncommon-profits", titel: "Common Stocks and Uncommon Profits — Fisher: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 165 },
  { slug: "japanese-candlestick-charting", titel: "Japanese Candlestick Charting — Nison: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 160 },
  { slug: "financial-shenanigans", titel: "Financial Shenanigans — Schilit: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 140 },
  { slug: "how-to-make-money-in-stocks", titel: "How to Make Money in Stocks — O'Neil: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 176 },
  { slug: "investment-valuation", titel: "Investment Valuation — Damodaran: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 198 },
  { slug: "the-most-important-thing", titel: "The Most Important Thing — Marks: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 150 },
  { slug: "interpretation-of-financial-statements", titel: "The Interpretation of Financial Statements — Graham: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 130 },
  { slug: "margin-of-safety", titel: "Margin of Safety — Klarman: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 140 },
  { slug: "poor-charlies-almanack", titel: "Poor Charlie's Almanack — Munger: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "the-dhandho-investor", titel: "The Dhandho Investor — Pabrai: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 130 },
  { slug: "the-little-book-that-beats-the-market", titel: "The Little Book That Beats the Market — Greenblatt: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 99 },
  { slug: "the-outsiders", titel: "The Outsiders — Thorndike: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "100-baggers", titel: "100 Baggers — Mayer: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 130 },
  { slug: "quality-of-earnings", titel: "Quality of Earnings — O'Glove: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 120 },
  { slug: "expectations-investing", titel: "Expectations Investing — Rappaport & Mauboussin: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 130 },
  { slug: "what-works-on-wall-street", titel: "What Works on Wall Street — O'Shaughnessy: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 130 },
  { slug: "market-wizards", titel: "Market Wizards — Schwager: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 130 },
  { slug: "the-essays-of-warren-buffett", titel: "The Essays of Warren Buffett — Cunningham: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 150 },
  { slug: "ak1ts-vaglarans-hierarki", titel: "AK1TS — Våglärans Hierarki: SUPERDJUP", kategori: "EKOSYSTEM", niva: 0, kraverFas: 3, vIndex: -1, minuter: 220 },
  { slug: "akm1-den-kontroversiella-modellen", titel: "AKM1 — Den Kontroversiella Modellen: SUPERDJUP", kategori: "EKOSYSTEM", niva: 0, kraverFas: 2, vIndex: -1, minuter: 240 },
  { slug: "the-alchemy-of-finance", titel: "The Alchemy of Finance — Soros: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "the-art-of-short-selling", titel: "The Art of Short Selling — Staley: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 130 },
  { slug: "contrarian-investment-strategies", titel: "Contrarian Investment Strategies — Dreman: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "elliott-wave-principle", titel: "Elliott Wave Principle — Frost & Prechter: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 170 },
  { slug: "trading-for-a-living", titel: "Trading for a Living — Elder: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "tanka-snabbt-och-langsamt", titel: "Tänka snabbt och långsamt — Kahneman: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 150 },
  { slug: "technical-analysis-of-stock-trends", titel: "Technical Analysis of Stock Trends — Edwards & Magee: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 150 },
  { slug: "valuation-measuring-managing", titel: "Valuation — McKinsey (Koller m.fl.): KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 175 },
  { slug: "the-psychology-of-money", titel: "The Psychology of Money — Housel: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "the-snowball", titel: "The Snowball — Schroeder om Buffett: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 165 },
  { slug: "encyclopedia-of-chart-patterns", titel: "Encyclopedia of Chart Patterns — Bulkowski: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 140 },
  { slug: "reminiscences-of-a-stock-operator", titel: "Reminiscences of a Stock Operator — Lefèvre: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 135 },
  { slug: "when-genius-failed", titel: "When Genius Failed — Lowenstein: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "you-can-be-a-stock-market-genius", titel: "You Can Be a Stock Market Genius — Greenblatt: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "against-the-gods", titel: "Against the Gods — Bernstein: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "fooled-by-randomness", titel: "Fooled by Randomness — Taleb: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "the-theory-of-investment-value", titel: "The Theory of Investment Value — Williams: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 140 },
  { slug: "the-signal-and-the-noise", titel: "The Signal and the Noise — Silver: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "liars-poker", titel: "Liar's Poker — Lewis: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 130 },
  { slug: "the-black-swan", titel: "The Black Swan — Taleb: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 150 },
  { slug: "misbehaving", titel: "Misbehaving — Thaler: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "devil-take-the-hindmost", titel: "Devil Take the Hindmost — Chancellor: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 150 },
  { slug: "extraordinary-popular-delusions", titel: "Extraordinary Popular Delusions — Mackay: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 120 },
  { slug: "irrational-exuberance", titel: "Irrational Exuberance — Shiller: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "manias-panics-and-crashes", titel: "Manias, Panics, and Crashes — Kindleberger & Aliber: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 150 },
  { slug: "the-big-short", titel: "The Big Short — Lewis: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "the-great-crash-1929", titel: "The Great Crash 1929 — Galbraith: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 130 },
  { slug: "common-sense-on-mutual-funds", titel: "Common Sense on Mutual Funds — Bogle: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 130 },
  { slug: "flash-boys", titel: "Flash Boys — Lewis: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 120 },
  { slug: "the-intelligent-asset-allocator", titel: "The Intelligent Asset Allocator — Bernstein: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 140 },
  { slug: "the-money-game", titel: "The Money Game — Adam Smith: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 120 },
  { slug: "stocks-for-the-long-run", titel: "Stocks for the Long Run — Siegel: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 130 },
  { slug: "all-about-asset-allocation", titel: "All About Asset Allocation — Ferri: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 150 },
  { slug: "vagfundament-variablerna-som-tidsserier", titel: "Vågfundament — Variablerna som Tidsserier", kategori: "EKOSYSTEM", niva: 0, kraverFas: 3, vIndex: -1, minuter: 144 },
  { slug: "foretagsvardering-med-fundamental-analys", titel: "Företagsvärdering: med fundamental analys — Hjelström, Isaksson & Nilsson: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 190 },
  { slug: "quantitative-value", titel: "Quantitative Value — Gray & Carlisle: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 165 },
  { slug: "the-warren-buffett-way", titel: "The Warren Buffett Way — Hagstrom: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 180 },
  { slug: "the-acquirers-multiple", titel: "The Acquirer's Multiple — Tobias Carlisle: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 160 },
  { slug: "the-five-rules-for-successful-stock-investing", titel: "The Five Rules for Successful Stock Investing — Pat Dorsey: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 206 },
  { slug: "creative-cash-flow-reporting", titel: "Creative Cash Flow Reporting — Mulford & Comiskey: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 165 },
  { slug: "the-little-book-of-value-investing", titel: "The Little Book of Value Investing — Christopher Browne: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 141 },
  { slug: "value-investing-from-graham-to-buffett", titel: "Value Investing: From Graham to Buffett and Beyond — Greenwald: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 190 },
  { slug: "distress-investing", titel: "Distress Investing: Principles and Technique — Whitman & Diz: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 170 },
  { slug: "fooling-some-of-the-people", titel: "Fooling Some of the People All of the Time — Einhorn: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 180 },
  { slug: "the-warren-buffett-portfolio", titel: "The Warren Buffett Portfolio — Hagstrom: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 160 },
  { slug: "competition-demystified", titel: "Competition Demystified — Greenwald & Kahn: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 185 },
  { slug: "financial-statement-analysis-and-security-valuation", titel: "Financial Statement Analysis and Security Valuation — Stephen Penman: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 204 },
  { slug: "the-innovators-dilemma", titel: "The Innovator's Dilemma — Clayton Christensen: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 180 },
  { slug: "come-into-my-trading-room", titel: "Come Into My Trading Room — Elder: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 170 },
  { slug: "the-visual-investor", titel: "The Visual Investor — Murphy: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 170 },
  { slug: "winning-the-losers-game", titel: "Winning the Loser's Game — Ellis: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 180 },
  { slug: "intermarket-analysis", titel: "Intermarket Analysis — Murphy: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 180 },
  { slug: "martin-pring-on-market-momentum", titel: "Martin Pring on Market Momentum — Pring: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 180 },
  { slug: "the-master-swing-trader", titel: "The Master Swing Trader — Farley: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 177 },
  { slug: "charlie-munger-complete-investor", titel: "Charlie Munger: The Complete Investor — Griffin: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 165 },
  { slug: "fibonacci-applications", titel: "Fibonacci Applications and Strategies for Traders — Fischer: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 160 },
  { slug: "good-to-great", titel: "Good to Great — Jim Collins: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 180 },
  { slug: "the-bogleheads-guide-to-investing", titel: "The Bogleheads' Guide to Investing — Larimore, Lindauer & LeBoeuf: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 180 },
  { slug: "konfluens-varde-moter-vagor", titel: "Konfluens — Där Värde Möter Vågor: DEN SAMMANSATTA METODEN", kategori: "EKOSYSTEM", niva: 0, kraverFas: 3, vIndex: -1, minuter: 169 },
  { slug: "bollinger-on-bollinger-bands", titel: "Bollinger on Bollinger Bands — Bollinger: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 170 },
  { slug: "teknisk-analys-med-johnny-torssell", titel: "Teknisk analys med Johnny Torssell — SVENSKT STANDARDVERK: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 195 },
  { slug: "way-of-the-turtle", titel: "Way of the Turtle — Faith: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 168 },
  { slug: "the-hour-between-dog-and-wolf", titel: "The Hour Between Dog and Wolf — Coates: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 168 },
  { slug: "trading-in-the-zone", titel: "Trading in the Zone — Douglas: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 160 },
  { slug: "market-mind-games", titel: "Market Mind Games — Shull: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 160 },
  { slug: "the-trend-following-bible", titel: "The Trend Following Bible — Abraham: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 168 },
  { slug: "the-complete-turtletrader", titel: "The Complete TurtleTrader — Covel: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 168 },
  { slug: "the-new-science-of-technical-analysis", titel: "The New Science of Technical Analysis — DeMark: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 168 },
  { slug: "this-time-is-different", titel: "This Time Is Different — Reinhart & Rogoff: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 180 },
  { slug: "your-money-and-your-brain", titel: "Your Money and Your Brain — Zweig: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 3, vIndex: -1, minuter: 168 },
  { slug: "origins-of-the-crash", titel: "Origins of the Crash — Lowenstein: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 168 },
  { slug: "var-ekonomi", titel: "Vår ekonomi — Klas Eklund: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 190 },
  { slug: "made-in-america", titel: "Made in America — Sam Walton: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 168 },
  { slug: "analysis-for-financial-management", titel: "Analysis for Financial Management — Robert C. Higgins: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 214 },
  { slug: "bull-a-history-of-boom-and-bust", titel: "Bull! — Maggie Mahar: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 186 },
  { slug: "of-permanent-value", titel: "Of Permanent Value — Andrew Kilpatrick: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 187 },
  { slug: "one-up-on-wall-street", titel: "One Up on Wall Street — Peter Lynch: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 188 },
  { slug: "principles-of-corporate-finance", titel: "Principles of Corporate Finance — Brealey, Myers & Allen: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 2, vIndex: -1, minuter: 215 },
  { slug: "shoe-dog", titel: "Shoe Dog — Phil Knight: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 156 },
  { slug: "the-everything-store", titel: "The Everything Store — Brad Stone: KOMPLETT", kategori: "BOKMASTER", niva: 0, kraverFas: 0, vIndex: -1, minuter: 169 },
  { slug: "bk-01-balansrakningen", titel: "Balansräkningen — bolagets karta", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bk-02-resultatrakningen", titel: "Resultaträkningen — bolagets resedagbok", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bk-03-kassaflodesrakningen", titel: "Kassaflödesräkningen — pengarna som faktiskt rörde sig", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bk-04-koncernredovisningens-grunder", titel: "Koncernredovisning — bolaget som äger bolag: konsolideringens logik", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bk-05-redovisningspolitiken", titel: "Redovisningspolitiken — siffrornas formbara rum: samma ekonomi, två rapporter", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bk-06-obeskattade-reserver-och-avsattningar", titel: "Obeskattade reserver och avsättningar — balansräkningens tvegift", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bk-07-lagret-och-lagervarderingen", titel: "Lagret och lagervärderingen — balansräkningens termometer", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "bk-08-intaktredovisningen", titel: "Intäktredovisningen — när intäkten föds (IFRS 15:s fem steg)", kategori: "BOKFÖRING & ÅRSREDOVISNING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ln-01-dupont-analysen", titel: "Du Pont-analysen — plocka isär ROE", kategori: "LÖNSAMHET", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ln-04-kapitalbindning-och-rorelsekapital", titel: "Kapitalbindning och rörelsekapital — lönsamhetens andra halva", kategori: "LÖNSAMHET", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ln-02-resultatkvalitet-och-accruals", titel: "Resultatkvalitet — är vinsten äkta?", kategori: "LÖNSAMHET", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ln-03-marginaltrappan-och-operativ-havstavng", titel: "Marginaltrappan och operativ hävstång — resultaträkningens känslighet", kategori: "LÖNSAMHET", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ln-05-vad-ar-lonsamhet", titel: "Vad är lönsamhet? — vinstens förståelse i sex steg", kategori: "LÖNSAMHET", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "st-01-soliditet-och-rantetackning", titel: "Soliditet & räntetäckningsgrad — svensk stabilitetsstandard", kategori: "STABILITET", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "st-02-kanslighetsanalys-och-stresstest", titel: "Känslighetsanalys — stresstesta balansräkningen", kategori: "STABILITET", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "st-03-altman-z-score", titel: "Konkursprognos — Altman Z-score", kategori: "STABILITET", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "st-04-stabilitet-genom-kreditcykeln", titel: "Stabilitet genom kreditcykeln — samma balansräkning, två världar", kategori: "STABILITET", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "st-05-refinansieringsmuren", titel: "Refinansieringsmuren — när skulden förfaller i klunga", kategori: "STABILITET", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "st-06-likviditetsreserven", titel: "Likviditetsreserven — kassan, faciliteten och överlevnadstiden", kategori: "STABILITET", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "st-07-skuggskulderna", titel: "Skuggskulderna — borgen, garantier och åtagandena utanför skuldraden", kategori: "STABILITET", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "tx-01-organisk-mot-forvarvad-tillvaxt", titel: "Organisk vs förvärvad tillväxt — spåra källan", kategori: "TILLVÄXT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "tx-02-volym-pris-och-mix", titel: "Volym, pris och mix — tillväxtens tre motorer", kategori: "TILLVÄXT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "tx-03-nar-skapar-tillvaxt-varde", titel: "När skapar tillväxt värde? — återinvesteringens matematik", kategori: "TILLVÄXT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "tx-04-tillvaxtens-granser", titel: "Tillväxtens gränser — S-kurvan, mättnaden och utrymmesräkningen", kategori: "TILLVÄXT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "tx-05-tillvaxtens-forsta-lasning", titel: "Tillväxtens första läsning — årtal, procent och tjocka filtar", kategori: "TILLVÄXT", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "tx-06-enhetsekonomin", titel: "Enhetsekonomin — nästa kunds hela räknelära", kategori: "TILLVÄXT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "tx-07-fran-siffra-till-kassa", titel: "Från siffra till kassa — tillväxtens konverteringstest", kategori: "TILLVÄXT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ks-01-kapitalstruktur-grunder", titel: "Kapitalstruktur — hur bolaget är finansierat", kategori: "KAPITALSTRUKTUR", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ks-02-kapitalallokering", titel: "Kapitalallokering — styrelsens fem vägar", kategori: "KAPITALSTRUKTUR", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ks-03-skuldens-anatomi", titel: "Skuldens anatomi — löptider, bindning och covenants", kategori: "KAPITALSTRUKTUR", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ks-04-emissionens-mekanik", titel: "Emissionens mekanik — kvot, teckningsrätt och utspädningens aritmetik", kategori: "KAPITALSTRUKTUR", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ks-05-covenanter-och-kreditbetyg", titel: "Covenanter och kreditbetyg — skuldens spelregler och prislapp", kategori: "KAPITALSTRUKTUR", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ks-06-konvertibler-och-hybridkapital", titel: "Konvertibler och hybridkapital — skulden som kan bli eget kapital", kategori: "KAPITALSTRUKTUR", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ks-07-kapitalstrukturens-avvagning", titel: "Kapitalstrukturens avvägning — tre teorier om skuldens rättvikt", kategori: "KAPITALSTRUKTUR", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ks-08-valutasakringen", titel: "Valutasäkringen — terminen, swappen och kronan i rapporten", kategori: "KAPITALSTRUKTUR", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rs-01-volatilitet-och-risk", titel: "Volatilitet och risk — skilj svängningar från förlust", kategori: "RISK", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rs-02-kundkoncentration", titel: "Kundkoncentration — när få kunder bär intäkterna", kategori: "RISK", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rs-03-dold-samvariation", titel: "Dold samvariation — när bolagen delar samma risk", kategori: "RISK", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rs-04-riskmatrisen", titel: "Riskmatrisen — att kartlägga osäkerheten", kategori: "RISK", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rs-05-riskavsnittet-mellan-raderna", titel: "Riskavsnittet mellan raderna — att läsa bolagets egen riskredovisning", kategori: "RISK", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rs-06-riskens-anatomi", titel: "Riskens anatomi — de fyra adresserna där risken bor", kategori: "RISK", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rs-07-leverantorsrisken", titel: "Leverantörsrisken — inköpens koncentration och maktbalansen", kategori: "RISK", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rs-08-modellrisken", titel: "Modellrisken — den femte adressen: antagandena, felmarginalen och det egna felet", kategori: "RISK", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rs-09-personalrisken", titel: "Personalrisken — den sjätte adressen: nyckelpersonerna, kunskapen och successionen", kategori: "RISK", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "mt-01-vad-ar-en-moat", titel: "Vad är en moat? — bolagets försvarsmur", kategori: "MOAT", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "mt-02-moat-erosion-och-vallgravstest", titel: "Moat-erosion — när vallgraven grävs igen", kategori: "MOAT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "mt-03-vallgraven-i-siffror", titel: "Vallgraven i siffror — att mäta en moats styrka och livslängd", kategori: "MOAT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "mt-04-vallgravens-fodelse", titel: "Vallgravens födelse — hur en moat byggs sten för sten", kategori: "MOAT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "mt-05-byteskostnader-och-inlasning", titel: "Byteskostnader och inlåsning — moaten som håller kunden kvar", kategori: "MOAT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "mt-06-kostnadsoverlagsenhet", titel: "Kostnadsöverlägsenhet — moaten ingen ser", kategori: "MOAT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "mt-07-prisfullmakten", titel: "Prisfullmakten — moatens ultimata test", kategori: "MOAT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "mt-08-kvalitetspremien", titel: "Kvalitetspremien — moatens pris och framtiden som redan betalats", kategori: "MOAT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "kt-01-vad-ar-en-katalysator", titel: "Vad är en katalysator? — händelsen som kan flytta en aktie", kategori: "KATALYSATOR", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "kt-02-forvantningsanalys-och-kalibrering", titel: "Förväntningsanalys — vad står redan i kursen?", kategori: "KATALYSATOR", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "kt-03-katalysatorkedjor", titel: "Katalysatorkedjor — andra ordningens effekter när en händelse utlöser nästa", kategori: "KATALYSATOR", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "kt-04-den-uteblivna-katalysatorn", titel: "Den uteblivna katalysatorn — när händelsen kommer och ingenting händer", kategori: "KATALYSATOR", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "kt-05-katalysatorernas-kalender", titel: "Katalysatorernas kalender — att bygga händelsekartan och läsa klustren", kategori: "KATALYSATOR", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "kt-06-guidningen", titel: "Guidningen — bolagets egen prognos som leverans och katalysator", kategori: "KATALYSATOR", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "kt-07-den-tillverkade-katalysatorn", titel: "Den tillverkade katalysatorn — aktivisten och händelsen som ingen annan skulle ha orsakat", kategori: "KATALYSATOR", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "kt-08-optionsforfallets-dag", titel: "Optionsförfallets dag — kalenderns inbyggda katalysator", kategori: "KATALYSATOR", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "kt-09-budpremien-och-budprocessen", titel: "Budpremien och budprocessen — katalysatorns paradfall", kategori: "KATALYSATOR", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "kt-10-avknoppningen", titel: "Avknoppningen — delen som blir ett eget bolag", kategori: "KATALYSATOR", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "am-01-likviditet-och-spread", titel: "Likviditet och spread — handelns dolda kostnader", kategori: "AKTIEMARKNADEN I PRAKTIKEN", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "am-02-index-och-passivt-agande", titel: "Index och passivt ägande — hur marknadens mått blev en vara", kategori: "AKTIEMARKNADEN I PRAKTIKEN", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "am-03-lasa-aktiesidan", titel: "Läsa aktiesidan — siffrorna på skärmen före metoderna", kategori: "AKTIEMARKNADEN I PRAKTIKEN", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "am-04-marknadsstruktur", titel: "Marknadsstruktur — hur handeln faktiskt fungerar", kategori: "AKTIEMARKNADEN I PRAKTIKEN", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "am-05-handelsdagens-auktioner", titel: "Handelsdagens auktioner — öppning, löpande handel och stängning", kategori: "AKTIEMARKNADEN I PRAKTIKEN", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "am-06-kortlage-och-aktieutlaning", titel: "Kortläge och aktieutlåning — den andra sidan av orderboken", kategori: "AKTIEMARKNADEN I PRAKTIKEN", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "am-07-indexomlaggningen", titel: "Indexomläggningen — flödet som flyttar kursen utan en enda nyhet", kategori: "AKTIEMARKNADEN I PRAKTIKEN", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "am-08-etfens-inre-mekanik", titel: "ETF:ens inre mekanik — korgen, skapelsen och arbitraget som håller priset", kategori: "AKTIEMARKNADEN I PRAKTIKEN", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "am-09-marginalhandeln", titel: "Marginalhandeln — belåningskontot, marginalkravet och kaskaden", kategori: "AKTIEMARKNADEN I PRAKTIKEN", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "vr-01-multipelgapet", titel: "Multipelgapet — varför lika bolag handlas olika", kategori: "VÄRDERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "vr-02-normaliserade-multipler", titel: "Normaliserade multipler — räkna bort cykeln", kategori: "VÄRDERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "vr-03-multipelns-anatomi", titel: "Multipelns anatomi — vad ett värderingstal innehåller", kategori: "VÄRDERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "vr-04-avkastningens-tre-kallor", titel: "Avkastningens tre källor — vinsttillväxt, utdelning och multipelns resa: redovisningen av var avkastningen kom ifrån", kategori: "VÄRDERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "vr-05-pris-och-varde", titel: "Pris och värde — aktiens två tal och första jämförelsen", kategori: "VÄRDERING", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "vr-06-jamforelsebolagen", titel: "Jämförelsebolagen — urvalet bakom varje multipel", kategori: "VÄRDERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "vr-07-terminalvardet", titel: "Terminalvärdet — DCF:s andra halva: det som händer efter prognosisperioden", kategori: "VÄRDERING", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "vr-08-tobins-q", titel: "Tobins Q — marknadsvärdet möter återanskaffningspriset", kategori: "VÄRDERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "vr-09-konglomeratrabatten", titel: "Konglomeratrabatten — när helheten är värd mindre än delarna", kategori: "VÄRDERING", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ib-01-vad-ar-ett-investmentbolag", titel: "Vad är ett investmentbolag? — bolaget som äger bolag", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ib-02-substansens-kvalitet", titel: "Substansens kvalitet — att granska vad substanssiffran innehåller", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ib-03-forvaltarskapet", titel: "Förvaltarskapet — röstvärde, mandat och den aktiva ägaren", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ib-04-avkastningsrakningen", titel: "Avkastningsräkningen — substans, rabatt och utdelning: varje krona har en adress", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ib-05-kostnadstrappan", titel: "Kostnadstrappan — vad som äts på vägen mellan vinsten och fickan", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ib-06-evighetskapitalet", titel: "Evighetskapitalet — ägandet utan slutdatum", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ib-07-family-officen", titel: "Familjekontoret — kapitalets tredje ägarform", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pe-01-private-equity-fonder", titel: "Private equity-fonder — hur onoterat kapital arbetar", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pe-02-utfasningar-och-irr-mekanik", titel: "Utfasningar och IRR-mekanik — hur fonder realiserar värde", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pe-03-forvarvsmaskinen", titel: "Förvärvsmaskinen — hur private equity bygger (och belastar) ett bolag", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pe-04-den-privata-agarsidan", titel: "Den privata ägarsidan — bolagens värld utanför börsen", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pe-05-andrahandsmarknaden", titel: "Andrahandsmarknaden — LP-andelens pris när fonden inte får vänta", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pe-06-j-kurvan-och-capital-calls", titel: "J-kurvan och capital calls — pengarnas tid i private equity", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pe-07-co-investeringen", titel: "Co-investeringen — andelen bredvid fonden", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "pe-08-avgiftsmaskinen", titel: "Avgiftsmaskinen — 2/20, tröskeln och trappan som delar vinsten", kategori: "PRIVATE EQUITY & INVESTMENTBOLAG", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "roic-01-avkastning-pa-investerat-kapital", titel: "ROIC — lönsamhet utan hävstångens makeup", kategori: "LÖNSAMHET", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "roic-02-avkastningstrappan", titel: "Avkastningstrappan — marginal och kapitalomsättning: ROIC:s två vägar", kategori: "LÖNSAMHET", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "roic-03-inkrementell-roic", titel: "Inkrementell ROIC — nästa kronas avkastning och medeltalets blindhet", kategori: "LÖNSAMHET", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "roic-04-vardeekvationen", titel: "Värdeekvationen — ROIC, återinvestering och multipelns pris", kategori: "LÖNSAMHET", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "roic-05-den-ekonomiska-vinsten", titel: "Den ekonomiska vinsten — EVA och tröskeln där tillväxt börjar skapa värde", kategori: "LÖNSAMHET", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ma-01-transmissionsmekaniken", titel: "Transmissionsmekaniken — från styrränta till bolagets resultat och värdering", kategori: "MAKROEKONOMI & RÄNTA", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ma-02-lonebildning-och-kostnadsspiralen", titel: "Lönebildningen och kostnadsspiralen — från avtal till bolagets marginal", kategori: "MAKROEKONOMI & RÄNTA", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ma-03-realrantan", titel: "Realräntan — pengars tidsvärde efter inflation", kategori: "MAKROEKONOMI & RÄNTA", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ma-04-konjunkturindikatorerna", titel: "Konjunkturindikatorerna — månadens siffror och bolagets nästa rapport", kategori: "MAKROEKONOMI & RÄNTA", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ma-05-kreditpremien", titel: "Kreditpremien — varför bolagets lån kostar mer än statens", kategori: "MAKROEKONOMI & RÄNTA", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ma-06-aktiernas-riskpremie", titel: "Aktiernas riskpremie — varför börsen betalar mer än statsobligationen", kategori: "MAKROEKONOMI & RÄNTA", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ma-07-valutakursens-mekanik", titel: "Valutakursens mekanik — PPP, ränteparitet och exportörens vind", kategori: "MAKROEKONOMI & RÄNTA", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ma-08-bostadsmarknadens-mekanik", titel: "Bostadsmarknadens mekanik — lånekraft, tröghet och vägen till börsen", kategori: "MAKROEKONOMI & RÄNTA", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ma-09-produktionsgapet", titel: "Produktionsgapet — hastighetstaket, gapet och räntans fixpunkt", kategori: "MAKROEKONOMI & RÄNTA", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "od-01-optionens-greker", titel: "Optionens greker — delta, gamma, theta och vega", kategori: "OPTIONS & DERIVAT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "od-02-implicit-volatilitet", titel: "Implicit volatilitet — marknadens pris på framtiden", kategori: "OPTIONS & DERIVAT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "od-03-warranter-och-teckningsoptioner", titel: "Warranter och teckningsoptioner — optionen möter den svenska emissionen", kategori: "OPTIONS & DERIVAT", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "od-04-kombinerade-optionspositioner", titel: "Kombinerade optionspositioner — collar, straddle och prisspridning", kategori: "OPTIONS & DERIVAT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "od-05-utdelningen-och-optionen", titel: "Utdelningen och optionen — ex-dagen, pariteten och det glömda kassaflödet", kategori: "OPTIONS & DERIVAT", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "od-06-positionen-efter-bygget", titel: "Positionen efter bygget — delta, band och förfallodagen", kategori: "OPTIONS & DERIVAT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "od-07-terminskontraktet", titel: "Terminskontraktet — priset idag, leveransen sedan", kategori: "OPTIONS & DERIVAT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "od-08-binomialtradet-och-replikeringen", titel: "Binomialträdet och replikeringen — hur optionen får sitt pris", kategori: "OPTIONS & DERIVAT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "od-09-forsakringsskrivandet", titel: "Försäkringsskrivandet — optionssäljarens sida", kategori: "OPTIONS & DERIVAT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "od-10-kreditderivatet", titel: "Kreditderivatet — CDS, försäkringen på låntagaren", kategori: "OPTIONS & DERIVAT", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ek-01-sam-viktningen", titel: "SAM-viktningen — fem teorier röstas, en signal föds", kategori: "EKOSYSTEM", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ek-02-labbets-karta", titel: "Labbets karta — fem motorer, ett hus: orienteringen före ek-01", kategori: "EKOSYSTEM", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ek-03-arbetsflodet-i-labbet", titel: "Arbetsflödet i labbet — fem stationer, en loggad analys: arbetet mellan kartan och ek-01", kategori: "EKOSYSTEM", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ek-04-backtestens-hantverk", titel: "Backtestens hantverk — att testa en metod mot historien utan att lura sig själv", kategori: "EKOSYSTEM", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ek-05-monte-carlo-i-motorn", titel: "Monte Carlo i motorn — tusen framtider ur en kassaflödesprognos", kategori: "EKOSYSTEM", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ek-06-bayesianska-omviktningen", titel: "Bayesianska omviktningen — hur rösterna lär sig av träffar och missar", kategori: "EKOSYSTEM", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "ek-07-walk-forward-i-motorn", titel: "Walk-forward i motorn — fönstret som validerar", kategori: "EKOSYSTEM", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rp-01-riskmattens-karta", titel: "Riskmåttens karta — fem mått, fem frågor, innan formlerna", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 1, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rp-02-tre-matt-tre-fragor", titel: "Tre mått, tre frågor — Sharpe, Sortino och Calmar i samma portfölj", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rp-03-riskparitet", titel: "Riskparitet — att viktta portföljen efter risk, inte kronor", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rp-04-volatilitetsbudgeten", titel: "Volatilitetsbudgeten — portföljens risk satt i ett tal och fördelad i kronor", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rp-05-sekvensrisken", titel: "Sekvensrisken — utfallsordningen som äger decenniet", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rp-06-volatilitetsdraget", titel: "Volatilitetsdraget — brusets avgift på tillväxten", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 2, kraverFas: 0, vIndex: -1, minuter: 24 },
  { slug: "rp-07-vantan-i-svansen", titel: "Väntat fall i svansen — CVaR och måttet bakom tröskeln", kategori: "RISKHANTERING & PORTFÖLJTEORI", niva: 3, kraverFas: 0, vIndex: -1, minuter: 24 },
];

/** slug → index i LARVAG_KARTA (O(1)-uppslag; deterministisk brytningsnyckel). */
export const LARVAG_KARTA_INDEX: ReadonlyMap<string, number> = new Map(
  LARVAG_KARTA.map((k, i) => [k.slug, i] as const),
);

/** Antal kurser i kartan — paritetsvakt mot deep-courses.json. */
export const LARVAG_ANTAL_KURSER = 490;
