#!/usr/bin/env node
// _s4u3-cp-bygg.mjs — byggmotor för Canadian Pacific Kansas City (CP) Q3-2026-läspaketet
// (spår 4, kvartalsrapportserien; byggare s4-u3, omgång auto-s4-1790873126824).
// ABORT-grindar: universumraden CP måste finnas, paketet får INTE redan finnas på disk.
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const FIL = "data/blogg-utkast/kvartal/2026-q3/sa-laser-du-cp-q3-2026.json";
if (existsSync(FIL)) { console.error("ABORT: paketet finns redan på disk — duplikat är förlorat arbete"); process.exit(1); }

const uni = JSON.parse(readFileSync("data/portfolj-system/bolagsunivers.json", "utf8"));
const lista = Array.isArray(uni) ? uni : (uni.bolag || uni.universum || uni.poster || Object.values(uni).find(Array.isArray));
const cpRad = lista.find(b => b.ticker === "CP");
if (!cpRad) { console.error("ABORT: universumraden CP saknas i bolagsunivers.json"); process.exit(1); }

const body = `Canadian Pacific Kansas City — järnvägsduopolens andra ben, det nät som binder Vancouver till Mexiko via Kansas City sedan KCS-förvärvet 2023, med noteringen CP i Toronto och New York och 106,54 miljarder kanadensiska dollar i börsvärde enligt mätningen den 1 oktober 2026 — rapporterar tredje kvartalet 2026 **onsdagen 28 oktober efter marknadsstängning, med konferenssamtalet 16:30 östamerikansk tid = 21:30 svensk tid**. Datumet står i bolagets egen mediarum-kungörelse: högsta datumklassen, ingen estimering. Tre dörrar väntar innan en enda siffra läses: **medianbolaget med toppmarginalerna** — EBIT-marginalen 28,3 procent är industri-grenens tredje högsta av 36 och nettomarginalen likaså tredje högsta, ändå står aktien på exakt grenens medianpris: P/E 28,17 mot medianen 28,21, och EV/EBIT 18,85 är medianen själv — frågan paketet gräver i är varför toppmarginaler bara betalar medianmultipel, och svaret står i de två andra dörrarna; **avkastningarnas botten** — ROIC 5,7 procent ligger under radens WACC 7,4 och är grenens fjärde lägsta, FCF-avkastningen 1,8 procent fjärde lägst: KCS-integrationens enorma kapitalbas äter fortfarande marginalernas värde; och **de två EPS-världarna** — samma Q2-kvartal rapporterar GAAP-EPS 1,15 (ned 14 procent) och core-justerad EPS 1,27 (upp 13 procent), skillnaden är en källsluten engångspost: försäljningen av Panama Canal Railway i fjolårets Q2. Allt här är utbildning i metod: inte en rekommendation att köpa, sälja eller behålla några värdepapper.

Paketet är industri-grenens tolfte läspaket — järnvägsduon därmed sluten: tvillingen Canadian National (CNR, paket från september) möter duopolens andra ben — och seriens andra Kanada-bolag med kanadensiska dollar hela vägen och TSX-primärnoting. Val-motiveringen bär två koordinater: BCE-utbyggnadens paragraf 10 öppnade Kanada/industri-cellen med CNR som förstakoordinat och CP som andra (universumradens egen kandidatnot), och ASM-paketets kö-notis — senaste leveransen före denna — rangordnar CP som FIFO-ettan bland återstående bärande objekt ("Kö vidare: CP 28/10, XOM 30/10, novemberfältet"). Duplikatkontrollen vid klaimen (disk-först i data/vakten/klaim-s4u3-cp-q3-2026.md): inget CP-paket bland de dryga nittio på disk. Biblioteksposten saknas — som CNR, Equinor, NVIDIA och MTG är CP plockat utanför de 22 vågvaliderade bolagen; universumraden (hämtad 2026-09-25, StockAnalysis TSX-primär i CAD med dubbelreplicerade nyckeltal) plus detta pakets nya primärinsamling är hela modellunderlaget: fem kvartalsrader, core-kedjan, rappdagen och guidancen sök- och webbverifierade 2026-10-01.

## Urvalet: järnvägsduon sluts — och datumklassen höjs till bolagsbekräftad

Universumradens not bar nästa rapport 2026-10-28 som v172-könotis, och kalenderfilens panel-estimat skrev samma dag — men den 1 oktober står kungörelsen i bolagets eget mediarum: **CPKC redovisar Q3 2026 onsdagen 28 oktober efter marknadsstängning, samtal 16:30 ET (14:30 MT) = 21:30 svensk tid**. Datumklassen höjs alltså från panel-estimat till bolagsbekräftad — samma lyft tvillingen CNR gjorde när IR-kalendern ägde över StockAnalysis divergens. Rytmen bär: Q3-2025 kom onsdagen 29 oktober 2025, Q1-2026 onsdagen 29 april, Q2-2026 onsdagen 29 juli — onsdag efter stängning är CP:s rytm, och 28 oktober 2026 är en onsdag. Tidsvillan för svenska läsare är fem timmar just denna vecka (sommartiden slutar i USA först 1 november, Sverige bytte 25 oktober): 16:30 ET = 21:30 svensk tid.

Kalenderkopplingen: kalenderår är räkenskapsår (decemberbokslut), Q3 2026 är julis–september-kvartalet, och rappdagen ligger två dagar före tvillingens — CNR rapporterar fredagen 30 oktober kl 14:30 svensk tid (paketet finns): järnvägsduon landar inom 48 timmar. Datakärnan: universumraden CP med full värderingsrad, lönsamhetstrappa, balansräkning och fyra räkenskapsår i serierna — och radens källnot redovisar den detalj som får bära halva källkritiken nedan: CPKC rapporterar själv core justerad EPS som primärmått, med KCS-purchase-accounting-avdrag i siffran, och källans P/E-fält står på justerad bas medan GAAP-världen ligger en annanstans.

## Nyckeltalen: medianbolaget med toppmarginaler — järnvägens tre världar

Värdena är universumradens (2026-09-25) med länkar till aspektsidor som lär ut hur talet räknas och tolkas inom industrigrenen. Varningsflaggan hissas först: järnvägsbolaget levererar tre världar — marginalernas, kapitalets och fönstrens — och de sammanfattas inte av ett enda tal. Värderingsraden:

- **P/E 28,17** ([så räknas det](/dataset/industri/pe)) — 18:e lägst av 36 i grenen (median 28,21): exakt mitten. Obs: på källans core-justerade EPS-bas; GAAP-världen ligger annorlunda (källkritikens första fynd).
- **P/B 2,63** ([aspekt](/dataset/industri/pb)) — 9:e lägst av 36 (median 4,68): bokfört kapital prissätts under medianen — men läs det med balansräkningen i handen, för det bokförda kapitalet är KCS-förvärvets.
- **EV/EBIT 18,85** ([aspekt](/dataset/industri/ev-ebit)) — 18:e lägst av 35: **CP:s eget värde är fältets median** — 17 bolag under, 17 över; ett renlysende sätt att förstå vad median-jämförelse är.
- **PEG 2,26** ([aspekt](/dataset/industri/peg)) — 8:e högst av 30 (median 1,46): spår-PEG på prognostillväxten +12,46 procent; källans egen 3-årshistoriska PEG är 5,41 — nämnaren är allt (övning tre).
- **FCF-avkastning 1,81 procent** ([aspekt](/dataset/industri/fcf-avkastning)) — 4:e lägst av 34 (median 3,54): kassan efter banunderhållet är tunn — integrations-capex och OR-arbetet syns här.

Lönsamhetstrappan ([ROE](/dataset/industri/roe) 9,54 procent mot median 18,8; [ROIC](/dataset/industri/roic) 5,66 procent mot median 12,6 — och UNDER radens WACC 7,37; [bruttomarginal](/dataset/industri/brutto-marginal) 46,4 mot 32,5; EBIT-marginal 28,27 mot 13,0; [nettomarginal](/dataset/industri/netto-marginal) 26,35 mot 9,88): **marginalerna i toppklass — avkastningarna i botten**. EBIT- och nettomarginal är grenens tredje högsta av 36, bruttomarginal sjunde högsta — men ROE femte lägst och ROIC fjärde lägst: precis spegelvändt mot tvillingen CNR, som bär samma toppmarginaler men ROIC över sin WACC. Skillnaden mellan tvillingarna är inte driftens — den är kapitalbasens: KCS-förvärvet 2023 lade USA:s och Mexikos nät i balansräkningen till förvärvspris, och integrations-vinsterna realiseras fortfarande i marginalerna medan kapitalkostnaden betalar fullt pris. Universumradens källnot är tydlig: ROIC under WACC är Kanada-blockets enda i panelen — integrationssyntesen pågår, och tills den släpper är det här utbildningsfrågan snarare än handlingsfrågan. [Intäktstillväxten TTM](/dataset/industri/omsattningstillvaxt-ttm) +5,0 procent (mitt i fältet, median +5,2) och [prognostillväxten](/dataset/industri/prognos-tillvaxt) +12,5 (trailing/fwd-modellen; 15:e lägst av 35). Balansräkningen är den tredje världen: [skuld/eget kapital](/dataset/industri/skuldsattning) 0,66 mot medianen 0,675 — mitten — men räntetäckningen 5,23 och Altman-Z 2,69 i källans varningszon (Piotroski 6); och under hösten har träppan vuxit: total skuld 21,31 miljarder vid radens mätning mot 25,15 i Q2-rapportens balansräkning — källkritikens fjärde fynd. Återbetalningarna växer — och bär tre världar: radens årsfält 0,80 CAD per aktie (0,74 procent på radens kurs), de deklarerade kvartalen 0,228 och nu 0,268 (höjning +17,5 procent med Q2), årsbasis 1,07 på dagens takt — och aktieantalet FALLER: 10,9 miljoner aktier återköpta i Q2 för 1 298 miljoner CAD.

## Källkritiken: fyra P/E-världar, två aktiebasser och en serie som inte räcker till

Kärnfyndet är **P/E-världarnas karta**. Identitetstestet: P/B delat med ROE ska ge P/E — 2,63 delat på 9,54 procent ger 27,57. Källans P/E-fält säger 28,17 (gap +2,2 procent), radens GAAP-replik 107,49/4,12 säger 26,08 (gap −5,4 procent): identiteten ligger närmast fältet, alltså bär fältet bolagets egen core-justerade värld (bas cirka 3,82) — inte GAAP. Nu lägg höstens ny mätning till: kvartalskedjan summerar GAAP-EPS till 4,29 (nedan) och mätningen 1 oktober (kurs härledd 121,19 ur mcap 106,54 delat på 879,1 miljoner aktier) ger P/E 28,25 mot statistikfältet 28,19 — dvs **fyra P/E-världar: 26,08 (radens GAAP-bas på kursen 107,49), 28,17 (radens core-bas, samma kurs), 28,19 (statistikfältets GAAP-TTM-bas på dagens kurs) och 25,57 (core-TTM-kedjan 4,74 på dagens kurs)** — och ingen av dem är fel: olika fönster, olika bas, olika kursdag. Två världar har dessutom korsat varandra under hösten: radens core-multiikel 28,17 och dagens GAAP-multiikel 28,19 ligger på samma tall — kursen steg 12,8 procent mellan mätningarna medan fönstret glided — läs alltid vilken EPS-värld en multipel står på innan två multiplar jämförs.

**Andra fyndet: aktiebasernas gap.** Raden bär 933,0 miljoner aktier (replik mot mcap och pris: 933,0 × 107,49 = 100 292 — 0,02 procent exakt), statistiksidan 879,1 miljoner, och kvartalssidans EPS räknas på en tredje värld kring 890–905 miljoner viktade aktier (Q2-26: 1 024 miljoner netto delat på EPS 1,15 = 890). Gapet högsta mot lägsta bas är drygt 6 procent — dokumentklass av samma slag som Tesla-paketets aktiebas-världar: paketet räknar EPS och scenarier på statistiksidans 879,1 (den bas som stämmer med nuvarande mcap och återköpstakten) och redovisar de övriga öppet.

**Tredje fyndet: års-serien som inte räcker till.** Radens FY-serie (intäkt 8 814 → 12 555 → 14 546 → 14 655 miljoner, med KCS-förvärvets strukturbrott 2023 — hoppet +42 procent i ett steg är förvärv, inte tillväxt; netto 3 317 → 3 861 → 3 923 → 3 801; GAAP-EPS 3,57 → 4,15 → 4,20 → 4,08) ligger i sin 2025-ände systematiskt under både kvartalssidans summor (intäkt 15 078, netto 4 141, EPS 4,50) och bolagets egen rapport (intäkt 15,1 miljarder, rapporterad EPS 4,51): gapen 2,9, 8,9 och 10,5 procent. Radens serie-bas (S&P Global-underlag) och källans kvartalssida bär olika världar — samma fenomen som tvilling-paketet CNR dokumenterade, och kuriren är densamma: paketets taltyp är kvartalssidan plus pressreleaserna, dubbelhämtade och namngivna; årsfälten redovisas som dokumentklass. Notera också att radens P/E-bärarkriterium är intakt (TTM-netto positiva i alla världar).

**Fjärde fyndet: skuldträppan och prisdriften.** Total skuld i kvartalsbalansräkningarna: 22 269 (Q2-25) → 23 891 → 23 598 → 24 320 → 25 147 miljoner (Q2-26): +12,9 procent på ett år, medan kassan smalnat från 799 till 366 miljoner — nettoskuld 21 470 → 24 781, +15,4 procent. Altman-Z har under samma höst läst 2,69 (raden) och 2,09 (oktobermätningen) — varningszonen båda gångerna. Och prisdriften: mellan universumradens hämtning (2026-09-25, kurs 107,49, mcap 100,27 miljarder) och oktobermätningen (mcap 106,54 miljarder) har aktien stigit 12,7 procent — alla prisberoende fält från raden är 09-25-läget och redovisas som sådana, dokumentklass inte fel.

## Kvartalskedjan: GAAP-fallet, Panamaposten och core-kedjan som stänger på öret

Kedjan bakåt från senaste rapporterade kvartal — GAAP-världen ur StockAnalysis kvartalssida (dubbelhämtad 2026-10-01, M CAD utom EPS), core-kolumnerna ur bolagets pressreleaser:

- **Q3 2025 (29 oktober 2025):** intäkt 3 661 (+3,2 procent på årsbasis), netto 920, GAAP-EPS 1,01; **core-justerad EPS 1,10** (+11 procent), core-OR 60,7. Detta är kvartalet som rullar ur fönstret den 28 oktober.
- **Q4 2025 (januari 2026):** intäkt 3 923 (+1,3 procent), netto 1 077, GAAP-EPS 1,19 (pressreleasen: 1,20); **core 1,33** (+3 procent) på **core-OR 55,9 — rekord**, FCF 729.
- **Q1 2026 (29 april 2026):** intäkt 3 701 (−2,5 procent — dippen), netto 846, GAAP-EPS 0,94; **core 1,04** (−2 procent), core-OR 63,0 — valutavindar och bränsle förklarade, RTM +2 procent.
- **Q2 2026 (29 juli 2026):** intäkt 4 164 (+12,6 procent — rekordkvartal), netto 1 024, GAAP-EPS 1,15; **core 1,27** (+13 procent), rapporterad OR 64,6, core-OR 61,6, RTM +4 procent, FCF 960 — rapporten som gjorde titeln "poised for accelerated growth in second half of 2026".

Tre mönster att läsa kedjan efter. **För det första: fyrkanten.** Q2-26:s intäkt +12,6 procent, GAAP-EPS −14 procent, core-EPS +13 procent, netto −17 procent — fyra riktningar i samma kvartal, och förklaringen är källsluten: Q2-2025:s GAAP-netto 1 234 bär försäljningen av Panama Canal Railway (1 april 2025) med en vinst efter skatt på 282 miljoner CAD — cirka 0,30 per aktie. Räknat utan Panamaposten var fjolårets Q2-netto cirka 952 miljoner, och Q2-26:s 1 024 är då **+7,6 procent i GAAP-världen** — GAAP-fallet är en bas-effekt, inte ett driftsfall; och core-kedjans +13 procent är bolagets egen värld som tar bort både Panamaposten, purchase-accounting-amortiseringen (94 miljoner i Q2-26), förvärvskostnader (27) och STB-kostnaderna i Union Pacific–Norfolk Southern-ärendet (14). Två EPS-världar, båda sanna, olika frågor. **För det andra: core-kedjan stänger årsfältet på öret.** 1,06 + 1,12 + 1,10 + 1,33 = 4,61 — exakt bolagets rapporterade core-justerade EPS för hela 2025, paritet på hundradelen, seriens kedjekontroll i sin renaste form. **För det tredje: OR-trappans säsong.** 60,7 → 55,9 (rekord) → 63,0 → 61,6: fjärde kvartalet är järnvägens skörde-toppen, första kvartalet vinterns bottennivå — läs Q3 mot Q3, aldrig mot föregående kvartal. Bakom raderna: spannmålsflödet 925 miljoner i Q2 mot 743 (+24,5 procent på årsbasis), intermodal 758 mot 684 (+10,8) och fordonsflödet 403 mot 330 (+22), medan kolet föll från 256 till 209 (−18); bränslekostnaden 618 mot 405 miljoner (+52,6 procent); och den effektiva skattesatsen 24,65 mot 22,45 procent.

## Så står sig bolaget mot branschen

Industrigrenen i bolagsuniversumet: 36 bolag (verkstadskollegorna ABB, Atlas Copco, Alfa Laval, Siemens, flygets Boeing och Airbus — och järnvägsduon CNR och CP), medianer räknade LIVE ur filen (n varierar med fältens täckning). Tabellen läses: CP-värde (raden, 2026-09-25), grenens median, CP:s rang.

| Nyckeltal | CP | Grenens median | Rang |
|---|---|---|---|
| P/E (core-justerad bas) | 28,17 | 28,21 | 18:e lägst av 36 |
| P/B | 2,63 | 4,68 | 9:e lägst av 36 |
| EV/EBIT (fältet) | 18,85 | 18,85 | 18:e lägst av 35 — medianen själv |
| PEG (spår) | 2,26 | 1,46 | 8:e högst av 30 |
| FCF-avkastning | 1,81 procent | 3,54 procent | 4:e lägst av 34 |
| ROE | 9,54 procent | 18,8 procent | 5:e lägst av 36 |
| ROIC | 5,66 procent | 12,6 procent | 4:e lägst av 34 |
| Bruttomarginal | 46,4 procent | 32,5 procent | 7:e högst av 34 |
| EBIT-marginal | 28,27 procent | 13,0 procent | 3:e högst av 36 |
| Nettomarginal | 26,35 procent | 9,88 procent | 3:e högst av 36 |
| Skuld/eget kapital | 0,66 | 0,675 | mitten av 36 (16 under, 18 över) |
| Intäktstillväxt TTM | +5,0 procent | +5,2 procent | mitten av 36 |

Läsarten i tre rader: **toppmarginaler på medianpris** — EBIT och netto tredje högst av 36, medan P/E står på exakt mitten och EV/EBIT är medianen själv; frågan är varför, och svaret är de två nästa raderna. **Avkastningarnas botten** — ROIC fjärde lägst och under WACC, FCF-avkastningen fjärde lägst: marknaden rabatterar marginalerna för kapitalbasens tyngd (KCS-förvärvet) och kassans tunnhet (FCF 1 818 miljoner i radens årsfält mot nettot 3 801); jämför aldrig ROE mellan bolag med olika belåning utan att läsa [skuldsättningssidan](/dataset/industri/skuldsattning) först — CP:s 0,66 är mitten av fältet, men det är en järnvägs-0,66 på en KCS-tung balansräkning. **Tvillingläsningen** — CNR-paketets profil var marginaltoppar på multiplarns billiga halva med ROIC över WACC; CP är samma drift men medianpris och ROIC under WACC: duopolens två ben prissätts olika av skäl som inte står i resultaträkningen. [Universumjämförelsen i sin helhet](/dataset/industri/universumjamforelse) visar alla lager.

## Tre sätt att läsa utfallet — läsövningar i metod

**Övning ett — fönstrets rotation i rätt EPS-värld.** Rullande GAAP-EPS är 4,29 (1,01 + 1,19 + 0,94 + 1,15; P/E 28,25 på kursen 121,19). Efter rapporten rullar Q3-2025:s GAAP-EPS 1,01 och core-EPS 1,10 UR — och nya kvartalet rullar IN i respektive värld. GAAP-brytpunkterna: för P/E 28 krävs rullande 4,33, alltså Q3-GAAP-EPS 1,05 (+4 procent); P/E 27 kräver 1,21; P/E 26 kräver 1,38; P/E 25 kräver 1,57 (+55 procent). Core-världen: rullande core 4,74 (1,10 + 1,33 + 1,04 + 1,27), P/E 25,57 — och där är frågan annorlunda: Q3-2025:s 1,10 är fjolårets näst svagaste core-kvartal, ett Q3 på konsensus 1,33 lyfter rullande core till 4,97 och sänker multipln till 121,19/4,97 = 24,4 — i core-världen köper tillväxten multiplen ned (kontrollen själv är övningen: räkna 4,74 + 0,23 = 4,97 och jämför). Kontrollen att bära in: CP rapporterar båda världarna i samma pressrelease — läs rätt värld innan brytpunkten används, och minns Panamaposten när GAAP-tillväxten räknas på årsbasis.

**Övning två — EV från balansräkningen, och skuldträppans aritmetik.** Bygg imperativet själv: mcap + skuld − kassa. Oktobermätningen: 106,54 + 25,15 − 0,37 = 131,3 miljarder CAD (statistikfältets EV-imperativ via EV/Sales landar 132,2 — 0,7 procent internt). Dividera med kvartalskedjans driftsresultat TTM 6 196 (1 456 + 1 727 + 1 390 + 1 623): EV/EBIT 21,2 — inte radens 18,85: fältet är 09-25-läget före höstens kursstegring och skuldtillväxt. Sedan träppan: utdelning 204 + återköp 1 298 + capex 766 = 2 268 miljoner i Q2 mot driftens kassaflöde 1 726 — återbetalningarna och underhållet överstiger kassaflödet med 542 miljoner, och skillnaden syns i nettoskuldposten (+3 311 miljoner på ett år mot Q2-25). Läxan: en utdelning som växer 17,5 procent och ett återköp på 1,3 miljarder i kvartalet kan samtidigt vara en balansräkning som lånar — läs de tre posterna tillsammans, aldrig var för sig.

**Övning tre — PEG:s nämnare och guidancens H2-aritmetik.** Fältet säger PEG 2,26: trailing-P/E 28,17 delat med prognostillväxten +12,5 (trailing/fwd-modellen). Källans egen 3-årshistoriska PEG är 5,41, oktobermätningens 1,52 — tre PEG, tre nämnare, ingen fel. Men den intressantaste nämnaren står i bolagets egen guidans: **lågt dubbeltsiffrig core-justerad EPS-tillväxt 2026 från basen 4,61** (kungjord med Q4-rapporten, bekräftad i septemberpresentationen; därtill mid single-digit RTM-tillväxt och capex cirka 2,65 miljarder). Aritmetiken: H1-2026 har levererat core 1,04 + 1,27 = 2,31 — så för ens tio procents helårstillväxt (4,61 × 1,10 = 5,07) kräver H2 core 2,76 mot H2-2025:s 2,43: **+13,6 procent under hösten, och +17,4 för tolv procent**. Det är detta "accelerated growth i H2" betyder i siffror — och Q3-konsensus cirka 1,33 core (MarketWatchs trend, +21 procent på årsbasis; källorna divergerar i valuta och bas) ligger mitt i den aritmetiken. Räkna själv från en tillväxtdefinition du kan försvara, och redovisa nämnaren.

**Scenariorutan** — metod, inte prognos: tre intäktslägen mot tre GAAP-nettomarginaler (22 dippen under Q1:s 22,9 / 24 mitt, strax under TTM:s 25,0 / 26 över Q2:s 24,6), aktier 879,1 miljoner, rullande GAAP-EPS 4,29 med Q3-25:s 1,01 rullande ut, kurs 121,19. Cellerna: netto (M CAD), EPS, nytt rullande P/E.

| Intäkt → marginal ↓ | Låg (3 900 M) | Mitt (4 100 M) | Hög (4 300 M) |
|---|---|---|---|
| **22 procent** | 858 · 0,98 · 28,5 | 902 · 1,03 · 28,1 | 946 · 1,08 · 27,8 |
| **24 procent** | 936 · 1,06 · 27,9 | 984 · 1,12 · 27,5 | 1 032 · 1,17 · 27,2 |
| **26 procent** | 1 014 · 1,15 · 27,3 | 1 066 · 1,21 · 27,0 | 1 118 · 1,27 · 26,6 |

Vikterna att minnas: hela rutan landar P/E 26,6–28,5 mot dagens 28,25 — rotationen är i princip neutral över hela rutan (Q3-25:s GAAP-EPS 1,01 är kedjans näst lägsta, så utrullningen bär inte samma tryck som hos tvillingen), och det är marginalen som flyttar: varje nettomarginalpunkt på mitt-intäkten är cirka 41 miljoner CAD = 0,05 CAD i EPS, medan hela intäktsspannet ±5 procent flyttar EPS 0,10 — i den här rutan väger marginalfrågan och intäktsfrågan ungefär lika, till skillnad från tillväxtbolagens ruttor där intäkten dominerar. Notera vilken värld rutan bär: GAAP — bygg en parallell core-ruta på core-TTM 4,74 för att öva världarna mot varandra.

## Praktiskt inför onsdagen 28 oktober kl 21:30 svensk tid

Tre saker att göra före rapporten, i fallande ordning. **Först: boka bevakningspunkten** — [CPKC:s mediarum och investorsidor](https://www.cpkcr.com/en/media/) (rapporten läggs upp efter stängning 28 oktober, samtalet 16:30 ET; onsdagsvanan är sedan länge). **Andra: bygg dina fönster innan rapporten** — rullande GAAP 4,29 med brytpunkterna 1,05/1,21/1,38, core-rullande 4,74 med H2-aritmetiken 2,76 för tio procents helår, och EV från balansvägen 131,3 miljarder, inte från radens 09-25-fält. **Tredje: de tre talen att läsa först** — intäkten mot rekordkvartalets 4 164 och årsbasen 3 661 (+13-procentloppet: nivåskifte eller topp?); core-OR mot 60,7 (förra årets Q3) och säsongstrappan — förbättrad OR på förbättrad intäkt är guidans marginal-språk i praktiken; och volymen RTM mot +4 (spannmålsvinden som burit Q2, kolet som motarbetat). Bakom dem: utdelningsdeklarationen (Q3-deklarationen väntas med rapporten; senaste höjning 17,5 procent), återköpstakten (NCIB-rammen bär upp till 44,9 miljoner aktier till februari 2027), och UP–NS-vågen — CP har själv sökt villkor i transaktionen, och STB-kostnaderna syns redan i core-justeringarna. [Ordlistan](/kurser) och [transparensen](/transparens) förklarar metodens delar; [källöversikten](/kallor) redovisar hela underlaget.

## Källor

- **Universumraden CP** — [bolagsunivers.json](/dataset/industri/universumjamforelse), hämtad 2026-09-25 (StockAnalysis TSX-primär i CAD med repliknoter): värderingsrad, lönsamhetstrappa, balansräkning, FY-serier, WACC-not, P/E-bärarkriterium kontrollerat före leverans.
- **Kvartals- och balansdata** — StockAnalysis kvartalssida ([stockanalysis.com/quote/tsx/CP](https://stockanalysis.com/quote/tsx/CP/) + /financials/?p=quarterly, dubbelhämtad 2026-10-01): fem kvartal GAAP (intäkt, netto, EPS, FCF, driftsresultat), skuldträppan, fraktkategorierna.
- **Statistikmätningen** — StockAnalysis /statistics/ (2026-10-01): mcap 106,54 miljarder, aktier 879,1 miljoner, P/E 28,19, PEG 1,52, EV-fälten, ROE/ROIC, Altman 2,09, utdelning 1,07 (0,90 procent), nästa rapport 28 oktober.
- **Pressreleaser (core-världen)** — Q2-2026: [CPKC reports strong Q2 results](https://www.prnewswire.com/news-releases/cpkc-reports-strong-q2-results-poised-for-accelerated-growth-in-second-half-of-2026-302838199.html) (2026-07-29; core 1,27 mot 1,12, Panamaposten, återköp, skatt, bränsle); Q1-2026: [CPKC reports first quarter results](https://www.cpkcr.com/en/media/Q1-apr2026) (2026-04-29; core 1,04, OR 63,0); Q4/FY-2025: [CPKC showcases strength of Precision Scheduled Railroading, delivers record margins](https://www.prnewswire.com/news-releases/cpkc-showcases-strength-of-precision-scheduled-railroading-delivers-record-margins-302673112.html) (core 1,33, rekord-OR 55,9, FY-core 4,61, 2026-guidansen); Q3-2025: [CPKC reports solid third quarter results](https://www.cpkcr.com/en/media/Q3-Results-2025) (2025-10-29; core 1,10, OR 60,7).
- **Rappdagen** — [CPKC to report third-quarter 2026 earnings results on October 28](https://www.cpkcr.com/en/media/Q3-Sept2026) (bolagets egen kungörelse: efter stängning 28 oktober 2026, samtal 16:30 ET / 14:30 MT); investor.cpkcr.com event-sida.
- **Konsensus och tvillingläsning** — MarketWatch analytikerestimat (Q3-trend cirka 1,33 CAD core; källorna divergerar i valuta och bas — redovisas som tredjepartsprognos); CNR-paketet sa-laser-du-cnr-q3-2026 (duopolens första ben, rappdag 30 oktober).

Rygraden i detta paket är aritmetiken: varje tal är antingen hämtat ur universumets insamling (med källnoter och dokumentklasser redovisade), webbverifierat hos namngiven källa, eller beräknat ur de tre — och beräkningsvägen redovisas, härledda imperativ inklusive. Inga köp-, sälj- eller behållningsrekommendationer förekommer; texten är utbildning i metodik enligt utbildningsundantaget (2 kap 5 § lagen 2007:528). Publicering av utkastet är kundens beslut (R2).`;

const paket = {
  slug: "sa-laser-du-cp-q3-2026",
  title: "CPKC (CP) Q3-rapport 2026: så läser du den — EBIT-marginal 28,3 procent 3:e högst av 36 på P/E 28,17 mot median 28,21 (EV/EBIT 18,85 är medianen), ROIC 5,7 under WACC 7,4, två EPS-världar (GAAP 1,15 ned 14, core 1,27 upp 13), skuld 21,3–25,1 mdr CAD — rappdag 28 oktober, 21:30 svensk tid (bolagsbekräftad)",
  description: "Canadian Pacific Kansas City (CP, TSX/NYSE) — järnvägsduopolens andra ben, 106,5 miljarder kanadensiska dollar i börsvärde — rapporterar Q3 2026 onsdagen 28 oktober efter marknadsstängning; samtalet 16:30 östamerikansk tid = 21:30 svensk tid, bolagsbekräftat. Läspaketet: marginalerna i topp-3 av 36 i industri-grenen på exakt grenens medianmultiplar; ROIC under WACC och FCF-avkastningen nästan botten; kvartalskedjans två EPS-världar där Panamaposten från Q2-2025 förklarar GAAP-fallet; skuldträppan som vuxit till 25,1 miljarder; guidancens H2-aritmetik (lågt dubbeltsiffrig core-tillväxt från basen 4,61). Allt som utbildning, aldrig råd.",
  pillar: "Institutionell metodik",
  author: "AK1A Research Lab",
  publishedAt: "2026-10-28",
  readingMinutes: 5,
  tags: ["kvartalsrapport", "Canadian Pacific Kansas City", "industri", "Kanada", "järnväg", "läspaket"],
  body
};

writeFileSync(FIL, JSON.stringify(paket, null, 2) + "\n", "utf8");
console.log("SKREV", FIL, "bytes:", Buffer.byteLength(JSON.stringify(paket, null, 2), "utf8"));
