#!/usr/bin/env node
// _s8u1o148-bokfor.mjs — ENGÅNGSVERKTYG (o148): appendar worklogposten +
// skriver commitmeddelandefilen. Node-kanalen (skal-kvoten: sammansatta
// bash-citeringar hänger; Write+node är den bevisat säkra vägen).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const post = `## SPÅR 8 s8-u1 (manifest auto-s8-1790006726228, redispatch) — 2026-09-21 ~18:3x–19:0x lokal: kvalitetsvåg o148 — BOLAGSMETADATA-KONTRAKTET: /bolag:s hårdkodade "100 bolag"-löften datadrivna (o146 §7 + o147 §6 kvarpost) [fabrik]

Fabriksagent s8-u1 (redispatch — inkarnation 1 LEVERERADE o145 klart: commits 28bff354+fd24a1ea, fabrikslogg 18:30, slutbevis omVerifierat av detta pass; här = duplikatskyddad omstart). VAL: kvarposten "'100 bolag'-metadata föråldrad", bokförd av två oberoende källor (o146 §7 i 98219b5f + o147 §6 i 2d253a4e); ytan disjunkt från bägge syskonen. FYND: /bolag-title "…100 bolag i tio branscher" + description "alla 100 bolag" mot verklighetens 249 bolag/10 branscher (bolagsunivers.json, maskinrknat) — ljuget ~2,5×; sekundärt: vy-fallback "100-bolagsuniversum" i detaljingressen + två lib-kommentarer. ROTORSAKA (o146:s glidningsklass i metadataform): talen hårdkodade vid våg 149 (då sanna) i stället för räknade ur källan vyn läser; universumet växer per dataleverans (o146: 243→249 samma dag). KUR (3 src-filer via Edit/Write): page.tsx metadata→generateMetadata() räknar antalBolag/antalBranscher ur SAMMA publiceradeBolagSidor() som vyn (force-static+revalidate 86400 orörda — metadatin evalueras vid build+ISR, koherent med vyns props); vy-fallback → lasBolagsSidor().length (serverkedja verifierad: två server-sidor, ingen use client); lib-kommentarerna talar ej längre "100" (v203-lärdomen). BEVIS: tsc 0 (projektbinären) · svit testa-bolag-metadata-kontrakt.mjs 13 PASS/0 FAIL (K1 metadata datadriven · K2 fallback · K3 paritet universum 249/publicerade 249/branscher 10 · K4 force-static-kontrakt orört; grinden strippar kommentarer så dokumentation FÅR citera historien — svitens första körning fångade egen kommentarscitering = konstruktörens fångst, o145-precedensen) · FÖRE-facit i HTTP-sonden: prod-titeln bär fortfarande "100 bolag i tio branscher" mot kodens 249/10 · EFTER-kvitto ETT kommando vid nästa gröna bygge: node verktyg/testa-bolag-metadata-kontrakt.mjs ⇒ sonden EFTER-GRÖN (spökmätningsskyddad: VÄNTAR-DEPLOY rapporteras som varning, ALDRIG fejkgrön; sviten bygger ALDRIG — prod-synkens ägo). KVD: R2 orörd (fakta-tal i befintlig metadata, ingen ny publiceringsyta) · data/blogg orörd · commit med pathspec (främmande ytor — bl.a. samtidigt pågående gränsnittsvaktsändringar — orörda). Protokoll: OPTIMERING/o148-bolag-metadata-kontrakt-s8.md (§7: dataset-aspekternas 100-tal = median-underlagsformuleringar, u2/o147:s yta, EJ denna klass). [fabrik]
`;

const msg = `studio: auto s8-u1 o148 bolagsmetadata-kontraktet — /bolag:s hårdkodade "100 bolag"-löften datadrivna (o146 §7 + o147 §6 kvarpost, bokförd av två oberoende källor, ytan disjunkt från syskonen): title "…100 bolag i tio branscher" + description "alla 100 bolag" mot verklighetens 249 bolag/10 branscher (ljuget ~2,5×; sekundärt vy-fallback "100-bolagsuniversum" + två lib-kommentarer); ROTORSAKA = o146:s glidningsklass i metadataform — talen hårdkodade vid våg 149 (då sanna) i stället för räknade ur källan vyn läser, och universumet växer per dataleverans (243→249 samma dag); KUR: page.tsx metadata→generateMetadata() räknar antalBolag/antalBranscher ur SAMMA publiceradeBolagSidor() som vyn (force-static+revalidate orörda, build+ISR-koherens) · vy-fallback→lasBolagsSidor().length (serverkedja verifierad) · lib-kommentarer talar ej längre 100; BEVIS: tsc 0 · svit testa-bolag-metadata-kontrakt.mjs 13 PASS/0 FAIL (grind strippar kommentarer så dokumentation FÅR citera historien — svitens första körning fångade egen citering = konstruktörens fångst, o145-precedensen) · FÖRE-facit i HTTP-sonden: prod-titeln bär fortfarande "100 bolag i tio branscher" mot kodens 249/10; EFTER-kvitto ett kommando vid nästa gröna bygge: node verktyg/testa-bolag-metadata-kontrakt.mjs ⇒ EFTER-GRÖN (spökmätningsskyddad, ALDRIG byggt av sviten); redispatch-notis: o145 levererat KLART av inkarnation 1 (28bff354+fd24a1ea) — detta pass duplikatskyddat omstart; R2 orörd · inget bygge · commit med pathspec; protokollpoolen: o148 reserverat här (protokollnummer.json), o145=s8-u1, o146=s8-u3, o147=s8-u2 [fabrik]
`;

fs.appendFileSync(path.join(ROT, "worklog.md"), post);
fs.writeFileSync(path.join(ROT, "verktyg", "_s8u1o148-commitmsg.txt"), msg);
console.log("worklog:", post.length, "tecken · commitmsg:", msg.length, "tecken");
