// Neutral granskning av PROD:s d22-version (efter konfliktval)
import fs from 'node:fs';
const j = JSON.parse(fs.readFileSync('data/bokmaster/the-hour-between-dog-and-wolf.json', 'utf8'));
const ny = j.chapters.at(-1);
const text = JSON.stringify(ny);
let fel = 0;
const ok = (n, v, d) => { console.log(`${v ? 'GRÖN' : 'RÖD'}  ${n}${d ? ' — ' + d : ''}`); if (!v) fel++; };
ok('chapterCount == len', j.chapterCount === j.chapters.length, `${j.chapterCount}/${j.chapters.length}`);
ok('totalMinutes == Σ', j.totalMinutes === j.chapters.reduce((a, k) => a + k.minutes, 0), `${j.totalMinutes}`);
ok('kap 15 titel+num+min', ny.num === 15 && ny.title === 'Från boken till egen analys' && ny.minutes >= 11 && ny.minutes <= 14, `num=${ny.num} min=${ny.minutes}`);
ok('quiz=3 + unika', ny.quiz.length === 3 && ny.quiz.every(q => q.q && q.alternativ.length === 4 && Number.isInteger(q.ratt) && q.ratt >= 0 && q.ratt <= 3 && q.tips) && new Set(ny.quiz.map(q => q.ratt)).size === 3, `ratt ${ny.quiz.map(q => q.ratt).join(',')}`);
ok('utmaning+insikt+tabell', ['utmaning', 'insikt', 'tabell'].every(t => ny.blocks.some(b => b.type === t)), ny.blocks.map(b => b.type).join(','));
const vm = JSON.parse(fs.readFileSync('data/varumarke.json', 'utf8'));
const traif = vm.forbjudnaFraser.filter(f => new RegExp(f.fran, 'i').test(text));
ok('varumärkesgrind 0/26', traif.length === 0, traif.join(';'));
const lagBland = ['2022:260', '2022:261', '1985:716', '2022:482', '2005:59'].filter(l => text.includes(l));
ok('lagrum endast 2007:528 ≥2', lagBland.length === 0 && (text.match(/2007:528/g) || []).length >= 2, `×${(text.match(/2007:528/g) || []).length}`);
const karn = ['testosteron', 'kortisol', 'winning effect', 'Coates', '100 000', '1 000 kr', '10 000 kr', '500 kr', '5 000 kr', '2 500 kr', '25 000 kr', '+200 kr', '−800 kr', '−400 kr', '−2 000 kr', '3V/7F', '7,5 %', '26 %', '2,5×', '+0,2 %', 'interoception', '2007:528'];
const saknas = karn.filter(t => !text.includes(t));
ok(`kärntal ${karn.length - saknas.length}/${karn.length}`, saknas.length <= 2, saknas.join(','));
const radgiv = [/\bköp\b[^.]*\baktie\b/i, /\bsälj\b[^.]*\baktie\b/i, /\bbör du köpa\b/i, /\brekommenderar (?:att )?köp/i].filter(re => re.test(text));
ok('inga köp/sälj', radgiv.length === 0);
ok('num-sekvens', j.chapters.every((k, i) => k.num === i + 1));
ok('deklaration (pappersform/inget råd/2007:528)', /pappersform|tankeexperiment/i.test(text) && /inget råd|inte.*råd|rekommendation/i.test(text));
console.log(fel === 0 ? '\nVALD d22 (prod): GRÖN' : `\nRÖD — ${fel}`);
process.exit(fel ? 1 : 0);
