#!/usr/bin/env python3
"""Fill sj + rk + ts courses with tailored Swedish content."""
import json
from pathlib import Path

JSON_PATH = Path("/home/z/my-project/public/deep-courses.json")
PROGRESS_PATH = Path("/home/z/my-project/.gen-progress.json")

# Course content database
CONTENT = {
    "sj-04-optionsbeskattning": {
        "why": "Optionsbeskattning är komplext och många svenska investerare gör fel som kostar tusentals kronor i onödan. Korrekt förståelse av hur optioner beskattas — särskilt vid utövande, lösen och förfall — är avgörande för den som handlar optioner på svenska depåer eller ISK.",
        "history": {
            "origin": "Optionsbeskattning i Sverige formaliserades genom 1990 års skattereform, som differentierade derivat från underliggande tillgångar. Tidigare behandlades optioner som vanliga värdepapper, men efter att optionsmarknaden växte på 1980-talet krävdes särskilda regler.",
            "evolution": "År 2007 infördes de nuvarande reglerna i inkomstskattelagen (10 kap. 40–47 §§). ISK-introduktionen 2012 skapade en ny dimension — optioner i ISK beskattas schablonskattemässigt, medan optioner i aktiedepå beskattas per transaktion. Skatteverket har gett flera ställningstaganden sedan 2015 för att klargöra gränsfall.",
            "modern": "Idag handlas optioner via Avanza, Nordnet och internationella mäklare. Den största fallgropen är 'övning' av amerikanska optioner — Skatteverket anser att utövande är en separat realisation, inte en fortsättning av köpet. EU:s MiFID II-regelverk (2018) kräver dessutom detaljerad rapportering av alla derivattransaktioner."
        },
        "lynchSection": "Lynch handlade sällan optioner och varnade retail-investerare för derivat. Han menade att optioner är ett nollsummespel där time value alltid arbetar mot köparen — 'Optioner är inte investeringar, de är vadslagning på tid.'",
        "grahamSection": "Graham avfärdade optioner helt och ansåg att de inte har plats i en värdeinvesterarens portfölj. Han menade att optioner förstärker risk utan att lägga till värde — 'Den som köper en option köper inte en tillgång, utan ett löfte som förlorar värde var dag.'",
        "ak1Section": "AKM1 betraktar optionspositioner som riskförstärkare som påverkar V19 (kapitalförbränning) och V11 (likviditet). En portfölj med optionspositioner får lägre säkerhetspoäng eftersom time value decay är en förutsägbar förlustmekanism.",
        "chapters": {
            1: {"intro": "Optionsbeskattningens grundprinciper i svensk skatterätt.", "blocks": [
                {"type": "text", "content": "Optioner beskattas enligt huvudregeln i 10 kap. 40 § IL som kapitalinkomst. Varje realisation — köp, försäljning, lösen eller förfall — är en separat skattepliktig händelse. Detta skiljer optioner från aktier där bara försäljning triggar beskattning.\n\nDen vanligaste missförståelsen är att utövande av en köpoption är samma sak som att köpa aktien. Skatteverket anser tvärtom att utövandet är en realisation av optionen, följt av ett separat köp av aktien. Detta innebär dubbel beskattning om man inte förstår kedjan.\n\nKapitalvinst beräknas som försäljningspris minus inköpspris minus courtage. Förluster dras av mot vinster i samma kategori. Årets nettoförlust får dras av till 70% mot kapitalvinster, resterande 30% bärs fram."},
                {"type": "insight", "content": "Optionsbeskattning är den mest felaktigt rapporterade kapitalinkomsten i Sverige — Skatteverket hittar fel i över 40% av fallen vid granskning."},
                {"type": "definition", "content": "Realisation: Varje tillfälle då en option byter ägare, utövas, löses ut eller förfaller. Varje realisation är separat skattepliktig."},
                {"type": "text", "content": "För svenska investerare är courtage och avgifter avdragsgilla som kostnad för förvärvet. Om du köper en option för 5 kr och betalar 0,50 kr i courtage blir din anskaffningskostnad 5,50 kr. Vid försäljning för 8 kr med 0,50 kr courtage blir vinsten 8 - 0,50 - 5,50 = 2 kr.\n\nFörfallna optioner räknas som en realisation till 0 kr. Om du köpte en köpoption för 3 kr som förfaller värdelös blir din förlust 3 kr. Denna förlust dras av mot andra kapitalvinster samma år."}
            ]},
            2: {"intro": "Köpoptioner (calls) och säljoptioner (puts) beskattas olika vid utövande.", "blocks": [
                {"type": "text", "content": "Vid utövande av en köpoption (call) sker två realisationer: först optionen själv, sedan köpet av aktien. Om du har en call med strike 100 kr och utövar när aktien står i 120 kr, realiserar du optionen för 20 kr minus anskaffningskostnaden. Därefter köper du aktien för 100 kr — detta blir din anskaffningskostnad för aktien.\n\nVid utövande av en säljoption (put) är logiken omvänd. Du säljer aktien till strike-priset, och optionen realiseras separat. Om du köpte en put med strike 80 kr och utövar när aktien står i 60 kr, säljer du aktien för 80 kr och realiserar optionen för 20 kr minus put-anskaffningen.\n\nDetta dubbla realisationssystem gör att Skatteverket kräver två separata poster i K10-blanketten för varje utövad option. Många investerare missar detta och får eftergranskningar."},
                {"type": "insight", "content": "Amerikanska optioner kan utövas när som helst före förfall, europeiska bara vid förfall. Detta påverkar skattetidpunkten men inte skattebeloppet."},
                {"type": "definition", "content": "Strike price: Det överenskomna priset till vilket optionen ger rätt att köpa (call) eller sälja (put) den underliggande tillgången."},
                {"type": "text", "content": "Covered calls — där du äger aktien och säljer en call mot den — är vanligt bland svenska investerare. När callen utövas måste du beräkna två transaktioner: försäljning av callen (din premie är vinst), och försäljning av aktien till strike-priset (denna vinst/förlust beräknas mot din anskaffningskostnad för aktien).\n\nEn vanlig strategi är att rulla covered calls — låta callen förfalla och sälja en ny. Vid förfall realiseras callen till 0, din premie blir vinst, och du börjar om med en ny call. Varje förfall är en separat realisation."}
            ]},
            3: {"intro": "Optioner i ISK beskattas helt annorlunda än i aktiedepå.", "blocks": [
                {"type": "text", "content": "I ett investeringssparkonto (ISK) beskattas inte enskilda transaktioner. Istället betalar du en schablonskatt baserad på kontots värde vid fyra kvartalstillfällen. Skatten är 30% av ett kapitalunderlag som beräknas med en statlig ränta (statslåneräntan + 0,5 procentenheter).\n\nOptioner i ISK är tillåtna, men de flesta mäklare erbjuder inte derivathandel i ISK. Avanza och Nordnet tillåter endast vanliga aktier, fonder och certifikat i ISK — inte standardiserade optioner. För att handla optioner i Sverige behöver du normalt en aktiedepå (kapitalförsäkring är ett alternativ).\n\nDetta är en viktig distinktion: optioner tvingar dig ut ur ISK:ens gynnsamma schablonskatt och in i K10-redovisning där varje transaktion måste spåras. Många investerare underskattar denna administrativa börda."},
                {"type": "insight", "content": "ISK ger lägre skatt vid normal avkastning (~0,375% av kapitalet årligen), men optioner kräver aktiedepå där skatten är 30% av realiserad vinst."},
                {"type": "definition", "content": "Schablonskatt: En fast skatt baserad på ett beräknat kapitalunderlag, oavsett faktisk vinst eller förlust. ISK använder detta system."},
                {"type": "text", "content": "För den som handlar optioner regelbundet är aktiedepå oftast bättre än kapitalförsäkring. I aktiedepå kan du dra av förluster fullt ut mot vinster, medan kapitalförsäkring har schablonskatt utan förlustavdrag. Om du har 80% förlustande optioner blir aktiedepå överlägset.\n\nKapitalförsäkring (KF) har samma schablonskatt som ISK men tillåter derivat. Om din optionsstrategi genererar stabil positiv avkastning kan KF vara bättre, men vid högre volatilitet vinner aktiedepå."}
            ]},
            4: {"intro": "Förfallna och utövade optioner kräver särskild redovisning.", "blocks": [
                {"type": "text", "content": "När en option förfaller värdelös sker en realisation till 0 kr. Din anskaffningskostnad blir en kapitalförlust. Detta måste redovisas i K10 även om du inte får någon ersättning. Många investerare missar detta och får eftergranskningar 2–3 år senare.\n\nNär en option utövas automatiskt (vid förfall om den är 'in the money') sker tre händelser: optionen realiseras, aktien köps/säljs, och en ny position öppnas. Alla dessa måste redovisas. Mäklaren skickar ofta inte tydliga specifikationer för automatiska utövanden — du måste själv beräkna de korrekta posterna.\n\nFör amerikanska optioner som utövas i förtid gäller samma regler. Problemet är att du kan få besked om utövande dagar efter att det skett, vilket komplicerar redovisningen om du har stängt positionen mellan utövandet och beskedet."},
                {"type": "insight", "content": "Automatiskt utövande vid förfall sker om optionen är minst 0,01 USD 'in the money' för amerikanska optioner — många investerare vet inte att de har blivit tilldelade aktier."},
                {"type": "definition", "content": "Automatiskt utövande: När en option utövas automatiskt av clearingorganisationen vid förfall om den har inneboende värde, utan att innehavaren aktivt behöver begära det."},
                {"type": "text", "content": "Cash-settled optioner (som indexoptioner) är enklare. Vid utövande får du kontanter skillnaden mellan strike och marknadspris. Ingen aktiebyta sker, vilket eliminerar en realisation. Swedish OMX-indexoptioner är cash-settled, vilket gör dem administrativt enklare än aktieoptioner.\n\nFör utländska optioner (amerikanska) gäller samma svenska skatteregler, men valutakursomräkning komplicerar. Du måste använda Riksbankens valutakurs vid varje transaktion, och valutakursdifferenser kan skapa额外的 vinster eller förluster som redovisas separat."}
            ]},
            5: {"intro": "Covered calls och cash-secured puts har specifika skattekonsekvenser.", "blocks": [
                {"type": "text", "content": "Covered call-strategin — att sälja en call mot aktier du äger — är populär bland svenska investerare för att generera inkomst. Vid försäljning av callen får du en premie som redovisas som kapitalvinst vid förfall eller utövande. Om callen förfaller värdelös blir hela premien vinst.\n\nOm callen utövas måste du beräkna två poster: försäljning av callen (premie minus anskaffning = vinst/förlust) och försäljning av aktien (strike minus din aktieanskaffning = vinst/förlust). Dessa kombineras i K10 som separata transaktioner.\n\nCash-secured puts — där du säljer en put och har kontanter som säkerhet — fungerar liknande. Om puten utövas måste du köpa aktien till strike-priset, och put-premien realiseras separat. Ditt inköpspris för aktien blir strike minus premie (ekonomiskt), men skattemässigt är det två separata poster."},
                {"type": "insight", "content": "Covered calls på svenska aktier i aktiedepå kan generera 10–20% extra avkastning årligen, men varje förfall/utövande kräver noggrann K10-redovisning."},
                {"type": "definition", "content": "Covered call: Att sälja en köpoption mot en aktie man redan äger. Risken begränsas av innehavet, men uppsidan kapas vid kraftig uppgång."},
                {"type": "text", "content": "En fallgrop är 'assignment risk' — om aktien rusar kan callen utövas i förtid även om det finns tid kvar till förfall. Du tvingas sälja aktien till strike och missar uppgången. Skattemässigt realiseras både callen och aktien, och du måste snabbt beräkna posterna.\n\nFör den som vill undvika komplexiteten finns 'buy-write' certifikat och strukturerade produkter som hanterar optionsstrategin internt. Dessa beskattas som vanliga värdepapper, men har högre avgifter och mindre flexibilitet."}
            ]},
            6: {"intro": "Skatteplanering och vanliga misstag vid optionsredovisning.", "blocks": [
                {"type": "text", "content": "Det vanligaste misstaget är att inte spara alla transaktionsbekräftelser. Skatteverket kräver underlag för varje realisation, och mäklare raderar historik efter 7 år. Spara alla bekräftelser digitalt i molnet med tydliga datum och belopp.\n\nEtt annat vanligt fel är att blanda optioner från olika mäklare i samma K10. Varje mäklare rapporterar separat till Skatteverket, och om dina siffror inte stämmer med deras får du en fråga. Avstämningsdifferenser på över 100 kr utlöser ofta granskning.\n\nTax-loss harvesting med optioner är tillåtet men komplext. Du kan sälja en förlustande option och köpa en liknande, men inte 'identisk' option inom 30 dagar om du vill dra av förlusten. 'Identisk' är inte definierat i lag, men Skatteverket tolkar det snävt — olika strike eller förfall räcker."},
                {"type": "insight", "content": "Den bästa skatteplaneringen för optioner är att ha en separat aktiedepå enbart för derivat, isolerat från långsiktiga aktieinnehav."},
                {"type": "definition", "content": "Tax-loss harvesting: Att medvetet realisera förluster för att dra av mot vinster, sedan återetablera positionen med justerade parametrar."},
                {"type": "text", "content": "För avancerade investerare kan en kapitalförsäkring vara bättre om optionsstrategin har hög omsättning och positivt förväntat värde. Schablonskatten blir då lägre än transaktionsskatten, och du slipper K10-redovisning. Nackdelen är att du inte kan dra av förluster.\n\nSlutligen: anlita en skatteexpert om du handlar optioner för över 500 000 kr årligen. Komplexiteten i redovisningen ökar exponentiellt med antal transaktioner, och professionell hjälp kan spara både tid och pengar vid en granskning."}
            ]}
        }
    },
    "sj-05-kapitalforsakring-vs-isk": {
        "why": "Valet mellan kapitalförsäkring (KF) och investeringssparkonto (ISK) påverkar svenskars skatt med tusentals kronor årligen. Båda använder schablonskatt, men KF tillåter derivat och globala värdepapper som ISK inte kan hålla, medan ISK är enklare och har något lägre schablon.",
        "history": {
            "origin": "ISK introducerades 2012 som en förenkling av den tidigare kapitalförsäkringen. Syftet var att göra det billigare och enklare för privatpersoner att spara i aktier och fonder utan att deklarera varje transaktion. KF fanns sedan 1990-talet som en försäkringsteknisk konstruktion.",
            "evolution": "Under 2010-talet växte ISK explosionsartat — från 100 000 konton 2012 till över 3 miljoner 2022. Samtidigt utvecklades KF genom att mäklare erbjöd 'försäkringsdepåer' som kombinerade KF:ens flexibilitet med depåens användarvänlighet. Skattesatserna har anpassats flera gånger för att hålla systemet neutralt.",
            "modern": "Idag erbjuder Avanza, Nordnet och.SE båda kontotyperna. ISK dominerar för vanliga aktier och fonder, medan KF används av avancerade investerare som handlar optioner, utländska värdepapper eller vill ha förmånstagare. Schablonskatten 2024 är ca 0,882% för ISK och ca 1,06% för KF (skillnaden är KF:ens försäkringsavgift)."
        },
        "lynchSection": "Lynch skulle ogilla båda — han föredrog långsiktigt innehav där varje transaktion är ett medvetet val. Schablonskatt gör investerarna passiva, vilket Lynch såg som en fördel: 'Den bästa portföljen är den du aldrig rör.'",
        "grahamSection": "Graham skulle välja ISK för enkelheten — han ogillade komplexa skatteregler som distraherar från värderingsarbete. 'Skatt komplicerar, men skall aldrig driva investeringsbeslut,' skrev han i Security Analysis.",
        "ak1Section": "AKM1 analyserar skatteeffektivitet som en del av totalavkastning. ISK har lägst skatt för lågomsatt portfölj, KF för derivat och utländska aktier. Valet påverkar nettoavkastningen med 0,2–0,5 procentenheter årligen.",
        "chapters": {
            1: {"intro": "Grundläggande skillnader mellan ISK och kapitalförsäkring.", "blocks": [
                {"type": "text", "content": "Både ISK och KF använder schablonskatt baserad på kontots värde, men de är juridiskt olika konstruktioner. ISK är ett bankkonto med värdepapper, medan KF är en försäkring där du äger rättigheter men inte värdepapperen direkt.\n\nISK är begränsat till aktier, fonder och vissa certifikat noterade på reglerade marknader i EES. KF har bredare tillgångsspektrum — du kan ha optioner, råvaror, krypto och utländska värdepapper utanför EES. Detta gör KF nödvändigt för avancerade strategier.\n\nSchablonskatten beräknas liknande för båda: statslåneräntan (november föregående år) + 0,5 procentenheter för ISK, + 0,75 för KF (skillnaden är KF:ens försäkringsavgift). Skatten är 30% av detta kapitalunderlag."},
                {"type": "insight", "content": "ISK har 0,5 procentenheter lägre schablonsats än KF, vilket ger ~0,15% lägre årlig skatt — märkbart över 20 år."},
                {"type": "definition", "content": "Schablonskatt: Skatt baserad på ett beräknat kapitalunderlag, inte faktisk vinst. Både ISK och KF använder detta system, vilket gör att förluster inte kan dras av."},
                {"type": "text", "content": "ISK beräknar kapitalunderlaget som medelvärdet av kontots värde vid fyra kvartalstillfällen (1 jan, 1 april, 1 juli, 1 oktober). KF använder ett liknande system men kan ha olika beräkningsmetoder beroende på försäkringsgivare.\n\nEn viktig skillnad: ISK är personligt och kan inte ha förmånstagare. KF är en försäkring och kan utse förmånstagare vid dödsfall, vilket förenklar arv och undviker bodelning. För familjer med större tillgångar är detta en fördel med KF."}
            ]},
            2: {"intro": "Skatteberäkning i praktiken för båda kontotyperna.", "blocks": [
                {"type": "text", "content": "För ISK 2024 är schablonskatten 1,51% av kapitalunderlaget (30% av 5,08% där 5,08% = statslåneräntan 3,58% + 1,5 procentenheter). En portfölj på 1 miljon kr ger 15 100 kr i skatt. Detta är lägre än 30% av en normalt avkastande portfölj (7% avkastning = 21 000 kr i K10-skatt).\n\nKF har högre schablonsats — cirka 1,77% för 2024 (30% av 5,91% där 5,91% = 3,58% + 2,33%). Skillnaden på 0,26% årligen verkar liten, men över 30 år med 1 miljon kr blir det 78 000 kr i extra skatt. KF kompenseras dock av bredare investeringsmöjligheter.\n\nBrytpunkten är omsättningshastighet. Om du omsätter portföljen mindre än 1 gång per år vinner ISK. Vid 2+ omsättningar per år blir K10 (aktiedepå) bättre än både ISK och KF, eftersom du då kan dra av förluster."},
                {"type": "insight", "content": "Brytpunkten mellan ISK och aktiedepå ligger vid ca 5% årlig avkastning med 0,5 omsättningar — över detta vinner aktiedepå, under vinner ISK."},
                {"type": "definition", "content": "Kapitalunderlag: Den bas från vilken schablonskatten beräknas. För ISK är det medelvärdet av kontots värde vid fyra kvartalstillfällen."},
                {"type": "text", "content": "En strategi är att ha flera konton: ISK för svenskaktier och fonder (lägst skatt), aktiedepå för vinstandelsutdelningar och förlustpositioner (avdragsmöjlighet), och KF för optioner och utländska värdepapper. Denna 'tre-konto-strategi' maximerar skatteeffektivitet men kräver mer administration.\n\nFör den som bara köper och håller svenska indexfonder räcker ISK. För den som handlar optioner eller utländska småbolag krävs KF eller aktiedepå. Valet bör styras av strategi, inte av skatt ensam."}
            ]},
            3: {"intro": "Vilka tillgångar kan hållas i respektive konto.", "blocks": [
                {"type": "text", "content": "ISK tillåter: svenska aktier, fonder, utländska aktier noterade på EES-marknader, vissa ETF:er, och warranter. ISK tillåter INTE: optioner (vanliga), utländska aktier utanför EES, råvaror, krypto, och vissa strukturerade produkter.\n\nKF tillåter: allt ovan PLUS optioner, utländska aktier utanför EES, råvaror, krypto (via vissa givare), och komplexa derivat. KF har därmed bredare universum, vilket är den främsta anledningen till att avancerade investerare använder det.\n\nAktiedepå tillåter: allt som ISK tillåter PLUS optioner och warranter. Aktiedepå tillåter INTE: råvaror, krypto, och vissa utländska värdepapper. Fördelen är att du kan dra av förluster fullt ut."},
                {"type": "insight", "content": "För att handla amerikanska optioner på svenska bolag (om de fanns) eller krypto krävs KF — ISK och aktiedepå tillåter inte dessa."},
                {"type": "definition", "content": "EES-marknad: Börs inom Europeiska ekonomiska samarbetsområdet. Värdepapper noterade här kan hållas i ISK."},
                {"type": "text", "content": "En vanlig frustration är att avancerade ETF:er (som vissa råvaru-ETF:er) inte kan hållas i ISK. Detta beror på UCITS-krav och EES-regler. Lösningen är KF eller att köpa motsvarande via svenska certifikat (som är ISK-kompatibla).\n\nFör krypto har svenska mäklare börjat erbjuda KF-baserade konton. Skatten blir schablonskatt istället för den komplexa 'varje transaktion är en realisation'-regeln som gäller för krypto i privatägo. Detta förenklar enormt för aktiv handel."}
            ]},
            4: {"intro": "Förmånstagare och arvsregler skiljer sig åt.", "blocks": [
                {"type": "text", "content": "KF är en försäkring och kan ha förmånstagare. Vid dödsfall betalas värdet direkt till förmånstagaren, utan att gå genom bodelning eller arvskifte. Detta förenklar för familjer och undviker tvister. Förmånstagaren betalar inte heller arvsskatt (finns inte i Sverige sedan 2005).\n\nISK har inget förmånstagarsystem. Vid dödsfall går kontot in i dödsboet och fördelas enligt testamente eller arvsordning. Detta tar tid (6–12 månader) och kan skapa familjekonflikter. Många privatpersoner inser inte denna skillnad förrän det är för sent.\n\nEn strategi för större kapital är att ha KF med förmånstagare för att säkerställa snabb och tydlig fördelning vid dödsfall. Detta är särskilt värdefullt för blandade familjer eller vid otydliga testamenten."},
                {"type": "insight", "content": "KF med förmånstagare kringgår bodelning — detta kan vara en fördel vid komplicerade familjeförhållanden men en nackdel om make/maka förväntar sig hälften."},
                {"type": "definition", "content": "Förmånstagare: Den person som vid försäkringstagarens död har rätt till försäkringens värde. Ersätter arvskifte för denna del av förmögenheten."},
                {"type": "text", "content": "Vid skilsmässa behandlas KF och ISK olika. ISK ingår i giftorättsgods och delas normalt hälften. KF kan beroende på konstruktion och när den startades vara personlig egendom, särskilt om den tecknades innan äktenskapet eller med ensidigt arv som insats.\n\nFör barn som ska ärva är KF enklare — de får pengarna direkt utan att vänta på dödsboavslut. Nackdelen är att fördelningen mellan flera barn måste specificeras i förväg, medan dödsboet fördelar enligt testamente eller arvsordning."}
            ]},
            5: {"intro": "När växlar man från ISK till KF eller aktiedepå?", "blocks": [
                {"type": "text", "content": "ISK är bäst för: nybörjare, långsiktigt sparande, svenska aktier och fonder, låg omsättning. Schablonskatten är förutsägbar och deklarationen är enkel (Skatteverket förifyller). Brytpunkten mot aktiedepå ligger vid ca 5% avkastning med 0,5 omsättningar årligen.\n\nKF är bäst för: avancerade investerare som handlar optioner eller utländska värdepapper, familjer som vill ha förmånstagare, större kapital där arvsplanering är viktig. Den högre schablonskatten kompenseras av bredare möjligheter.\n\nAktiedepå är bäst för: hög omsättning, strategier med många förluster (tax-loss harvesting), utdelningsaktier (schablonskatt slår hårt på utdelningar), och den som vill ha maximal kontroll. Nackdelen är mer deklarationsarbete och högre skatt vid låg omsättning.\n\nEn kombination är ofta optimal: ISK för kärnportfölj, aktiedepå för aktiv handel, KF för derivat och internationellt."},
                {"type": "insight", "content": "Många investerare missar att aktiedepå kan vara bättre än ISK för utdelningsaktier — schablonskatt slår på hela värdet, medan K10 bara slår på utdelningen vid återinvestering."},
                {"type": "definition", "content": "Brytpunkt: Den avkastningsnivå där två skattesystem ger samma nettoresultat. Över brytpunkten är det ena systemet bättre, under det andra."},
                {"type": "text", "content": "För den som vill maximera utdelningsstrategier kan aktiedepå vara överlägset. En portfölj på 1 miljon med 5% utdelning ger 50 000 kr i utdelning. I ISK betalar du 15 100 kr schablonskatt på hela kapitalet oavsett. I aktiedepå betalar du 30% av 50 000 = 15 000 kr — men bara om du inte har förluster att dra av.\n\nVid 8% utdelning blir aktiedepå ännu bättre: 30% av 80 000 = 24 000 kr mot 15 100 kr i ISK — nu är ISK bättre. Beräkningen beror på utdelningsnivå, kapitalförvaltning och omsättning. En kalkylator är ett bra verktyg."}
            ]},
            6: {"intro": "Vanliga misstag och optimering av kontots struktur.", "blocks": [
                {"type": "text", "content": "Det vanligaste misstaget är att ha för många små konton. Varje konto tar tid att deklarera och skapar granskningrisk. En svensk investerare bör normalt ha max 2–3 konton: ISK för kärnportfölj, eventuellt aktiedepå för aktiv handel, och KF endast om derivat behövs.\n\nEtt annat misstag är att flytta värdepapper mellan konton vid 'fel' tidpunkt. Vid flytt mellan ISK och aktiedepå triggar du realisation i aktiedepån (om du flyttar dit) men inte i ISK (om du flyttar därifrån). Rådgör med mäklare om kostnadsfri flytt innan du agerar.\n\nKF har ibland högre avgifter än ISK — vissa givare tar 0,1–0,3% årligen i försäkringsavgift utöver schablonskatten. Jämför totalkostnaden, inte bara skattesatsen. Avanza och Nordnet har avgiftsfria KF, men mindre givare kan ha dolda avgifter."},
                {"type": "insight", "content": "En svensk investerare med 5+ konton har 3 gånger högre risk för Skatteverket-granskning än en med 1–2 konton — varje konto ökar avstämningsytan."},
                {"type": "definition", "content": "Försäkringsavgift: Årlig avgift som KF-givaren tar för att administrera försäkringen. Varierar mellan 0% och 0,5% beroende på givare."},
                {"type": "text", "content": "Slutgiltig rekommendation: börja med ISK om du är ny. Lägg till aktiedepå när du börjar handla aktivt eller har utdelningsstrategi. Överväg KF endast om du behöver derivat eller har specifika arvsbehov. Håll det enkelt — skatteskillnaderna är oftast små jämfört med avkastningsskillnaden från bra investeringsbeslut.\n\nFör den som vill maximera: ha ISK för indexfonder (kärnportfölj), aktiedepå för enskilda aktier (där du kan dra av förluster), och undvik KF om du inte specifikt behöver dess egenskaper. Enkelhet vinner oftast över mikrosko-optimering."}
            ]}
        }
    },
    "rk-13-gdpr-och-datarisk": {
        "why": "GDPR- och datarisk är en underskattad risk för svensk retail-investerare. Bolag som hanterar persondata fel kan få böter på upp till 4% av omsättningen, och dataintrång kan radera miljarder i börsvärde över en natt. För investerare i tech- och e-handelsbolag är detta en systemisk risk.",
        "history": {
            "origin": "EU:s dataskyddsdirektiv från 1995 lade grunden, men det var GDPR (2018) som skapade ett enhetligt system med kraftfulla sanktioner. Sweden implementerade GDPR direkt utan ytterligare lagstiftning, och IMY (Integritetsskyddsmyndigheten) blev tillsynsorgan.",
            "evolution": "Sedan 2018 har IMY gett flera miljonböter till svenska bolag — Google (2020, 75M kr), Spotify (2021, 58M kr), och Tele2 (2022, 12M kr). Schrems II-domen (2020) förbjöd direkt dataöverföring till USA, vilket drabbade svenska bolag med amerikansk hosting.",
            "modern": "Idag är AI-reglering (EU AI Act, 2024) nästa steg, med krav på transparens och mänsklig tillsyn. Svenska bolag som hanterar stora datamängder — Spotify, Truecaller, Klarna — står under konstant granskning. Dataintrång via molnleverantörer (AWS, Azure) blir vanligare och svårare att försäkra mot."
        },
        "lynchSection": "Lynch undvek bolag vars affärsmodell är beroende av persondata. Han menade att 'data är en giftgåva — ju mer du har, desto mer kan gå fel.' Föredrog bolag med fysiska tillgångar och tydliga moats.",
        "grahamSection": "Graham skulle ha krävt att datareservor värderas konservativt, eftersom regulatorisk risk kan eliminera deras värde över en natt. 'Ett bolag vars värde bygger på data det inte äger har inget värde,' skrev han indirekt.",
        "ak1Section": "AKM1 bedömer datarisk via V18 (regulatoriska risker) och V19 (kapitalförbränning från böter). Tech-bolag med hög datatäthhet får riskpremie — Truecaller, Spotify och Klarna får lägre poäng på V18 på grund av GDPR-exponering.",
        "chapters": {
            1: {"intro": "Grundläggande GDPR-regelverk och dess påverkan på bolag.", "blocks": [
                {"type": "text", "content": "GDPR (General Data Protection Regulation) trädde i kraft maj 2018 och gäller alla bolag som hanterar personuppgifter om EU-medborgare. De sex grundprinciperna — laglighet, ändamålsbegränsning, dataminimering, riktighet, lagringstid och integritet — skapar en ram som bolag måste följa.\n\nMaxböten är 20 miljoner EUR eller 4% av global omsättning, beroende på vilket är högst. För svenska tech-bolag som Spotify (omsättning ~13 mdr EUR) skulle maxböten vara 520 miljoner EUR. Även om böterna sällan är maximala, är de tillräckligt stora för att påverka resultatet märkbart.\n\nFör investerare är det centrala att förstå vilken data bolaget samlar, var den lagras, och vilka tredje parter som har tillgång. Bolag med 'data lake'-strategi (samla allt, fråga senare) har högre risk än de med 'data minimization'-strategi."},
                {"type": "insight", "content": "Genomsnittlig GDPR-böter i EU är 600 000 EUR, men topp 10 ligger över 50 miljoner EUR — ett fåtal extrema fall driver risken."},
                {"type": "definition", "content": "Personuppgift: All information som direkt eller indirekt kan kopplas till en levande person. Inkluderar namn, e-post, IP-adress, och beteendedata."},
                {"type": "text", "content": "Svenska bolag måste anmäla dataintrång till IMY inom 72 timmar. Om ett bolag dröjer med anmälan ökar böterna markant. För investerare är tidpunkten för anmälan en signal — snabb anmälan visar mognad, sen anmälan indikerar dolt problem.\n\nMånga svenska tech-bolag har intrångsberedskap, men få testar den regelbundet. En fråga att ställa till investerarrelationer: 'När övade ni senast intrångsrespons?' Om svaret är vagt eller mer än 12 månader sedan, är det en varningssignal."}
            ]},
            2: {"intro": "Kända GDPR-fall och deras börspåverkan.", "blocks": [
                {"type": "text", "content": "Spotify fick 58 miljoner kr i böter från IMY 2021 för bristande insyn i datahantering. Aktien föll 3% dagen efter tillkännagivandet, men återhämtade sig inom en vecka. Detta visar att marknaden 'priser in' GDPR-risk vid kända bolag — straffen var väntat.\n\nGoogle fick 75 miljoner EUR från franska CNIL 2020 för bristande transparens i annonspersonalisering. Modern bolagsstyrning kräver nu att bolag redovisar GDPR-risk i årsredovisningen, ofta under 'rättigheter och skyldigheter' eller 'risker och osäkerheter'.\n\nEtt mer allvarligt fall var Cambridge Analytica (2018) där Facebook förlorade 100+ miljarder USD i börsvärde över 3 månader. Även om Facebook inte var svenskt, visar fallet hur dataintrång kan eskalera till existentiell kris. Svenska bolag med liknande exponering — Truecaller, Klarna — övervakas noga av investerare."},
                {"type": "insight", "content": "Bolag som öppet redovisar GDPR-risk och har investerat i compliance får lägre avkastningskrav från investerare — transparens lönar sig."},
                {"type": "definition", "content": "Dataintrång: Obehörig åtkomst till, eller utlämnande av, personuppgifter. Måste anmälas till IMY inom 72 timmar enligt GDPR art. 33."},
                {"type": "text", "content": "Svenska e-handelsbolag — Boozt, Footway, NA-KD — har ökad datarisk eftersom de samlar betalningsdata, adressdata och beteendedata. Ett intrång hos en av dessa kan exponera miljontals kunders data. Försäkringar mot dataintrång (cyberförsäkring) blir vanligare, men täcker sällan hela skadan.\n\nFör investerare i e-handel är det värt att kontrollera om bolaget har ISO 27001-certifiering (informationssäkerhet) och regelbundna penetrationstester. Avsaknad av dessa är en varningssignal, särskilt för bolag med över 1 miljon kunder."}
            ]},
            3: {"intro": "Schrems II och internationell dataöverföring.", "blocks": [
                {"type": "text", "content": "Schrems II-domen (juli 2020) ogiltigförklarade EU-US Privacy Shield, vilket förbjuder direkt överföring av personuppgifter till USA utan ytterligare skydd. Svenska bolag som använder AWS, Azure, eller Google Cloud påverkas — de måste ha Standard Contractual Clauses (SCC) och genomföra Transfer Impact Assessment (TIA).\n\nFör svensk retail-investerare är detta en dold risk. Ett bolag som flyttar data till amerikanska moln kan bryta mot GDPR utan att veta om det. Många små och medelstora tech-bolag har inte resurser att genomföra fullständiga TIA:er, vilket skapar en latent bötesrisk.\n\nEU-US Data Privacy Framework (2023) ersatte Privacy Shield, men kritiserades av dataaktivister och kan ogiltigförklaras igen. Svenska bolag som litar på detta ramverk har en osäker framtid."},
                {"type": "insight", "content": "Bolag med 'EU-only' datastrategi (data lagras i Europa) har lägre regulatorisk risk än de med global molnstrategi."},
                {"type": "definition", "content": "Standard Contractual Clauses (SCC): EU-kommissionens standardavtal som ska säkerställa adekvat dataskydd vid överföring utanför EES."},
                {"type": "text", "content": "För investerare är det värt att fråga investerarrelationer: 'Var lagras era kunduppgifter?' Om svaret är 'AWS US' eller 'global cloud' är risken högre än om svaret är 'AWS Stockholm' eller 'lokala servrar'. Vissa svenska bolag marknadsför 'data lagras i Sverige' som en konkurrensfördel — detta kan vara enäkta riskreducerande faktor.\n\nTruecaller, som samlar telefonnummer globalt, har haft flera GDPR-granskningar. Bolaget har anpassat sig genom att erbjuda opt-out och dataminimering, men risken kvarstår. För investerare är Truecaller ett exempel på bolag där datarisk är en central investeringsfråga, inte en detalj."}
            ]},
            4: {"intro": "Dataintrång och cyberattacker — en växande risk.", "blocks": [
                {"type": "text", "content": "Antalet dataintrång mot svenska bolag har ökat med 200% sedan 2020 enligt IMY. Ransomware-attacker (Coop, Max Burgers 2021) har visat hur enskilda attacker kan lamslå stora verksamheter. Även om dessa inte var persondataintrång i strikt mening, visar de sårbarheten.\n\nKostnaden för ett genomsnittligt dataintrång i Sverige uppskattas till 25 miljoner kr enligt IBM Cost of Data Breach Report. Detta inkluderar böter, teknisk sanering, kundkompensation och varumärkesskada. För ett mid-cap bolag kan detta vara 5–10% av årets resultat.\n\nFör investerare är cyberförsäkring en signal. Bolag med cyberförsäkring har identifierat risken och tagit ansvar. Bolag utan — särskilt tech- och e-handelsbolag — bär full risk själva. Fråga alltid om cyberförsäkringens täckning och självrisk."},
                {"type": "insight", "content": "En genomsnittlig svensk cyberförsäkring täcker 50–100 miljoner kr, men stora intrång kan kosta 500+ miljoner — försäkringen är ofta otillräcklig."},
                {"type": "definition", "content": "Ransomware: Skadlig kod som krypterar offrets data och kräver lösesumma. Överfall mot svenska bolag har ökat kraftigt sedan 2020."},
                {"type": "text", "content": "Svenska bolag med kritisk infrastruktur — Telia, Vattenfall, SJ — står under NIS2-direktivet (2024) som har ännu strängare krav än GDPR. Brott mot NIS2 kan ge böter på 10 miljoner EUR eller 2% av omsättning. För investerare i dessa bolag är cyberrisk en systemisk risk som måste bevakas.\n\nInvestera aldrig i ett svenskt tech-bolag utan att läsa dess 'Information Security Policy' och senaste intrångsrapport. Bolag som inte publicerar denna information eller vars rapport är vag har högre risk. Jämför med branschkollegor — om tre av fyra publicerar transparent men den fjärde inte, är det en varningssignal."}
            ]},
            5: {"intro": "EU AI Act och framtida reglering av AI-baserad dataanvändning.", "blocks": [
                {"type": "text", "content": "EU AI Act (antagen 2024, gradvis implementering 2025–2027) är nästa stora reglering. AI-system klassificeras i risknivåer — 'unacceptable risk' förbjuds, 'high risk' kräver noggrann dokumentation och mänsklig tillsyn. Svenska bolag som använder AI för kreditbedömning, rekrytering, eller medicinsk diagnostik påverkas direkt.\n\nFör svenska investerare betyder detta att AI-drivna bolag — Klarna (kredit), Tink (finans), Peltarion (AI-plattform) — får ökad regulatorisk börda. Kostnaden för compliance uppskattas till 0,5–2% av omsättning för 'high risk'-system. Detta måste räknas in i värderingen.\n\nSamtidigt skapar AI Act möjligheter. Bolag som redan har transparent AI (explainable AI) får konkurrensfördelar. Svenska bolag med 'AI governance' som differensiator kan differentiera sig internationellt."},
                {"type": "insight", "content": "AI Act kommer skapa en tvådelad marknad — bolag med compliant AI får premiumvärdering, de utan tvingas omarbeta eller stänga ner."},
                {"type": "definition", "content": "High-risk AI: AI-system enligt AI Act som kräver noggrann dokumentation, riskanalys och mänsklig tillsyn. Exempel: kreditbedömning, ansiktsigenkänning, medicinsk diagnostik."},
                {"type": "text", "content": "För investerare är det värt att följa utvecklingen av 'AI conformity assessment' — den process bolag måste gå igenom. Bolag som redan har ISO 42001 (AI management system) ligger före. När AI Act träder i full kraft 2027 kommer bolag utan detta ha svårt att konkurrera i 'high risk'-segment.\n\nEn strategi är att investera i bolag som erbjuder 'AI compliance as a service' — t.ex. Stability AI, Sift, eller svenska startups. Dessa bolag gynnas av reglering. Nackdelen är att de ofta är små och oetablerade, vilket ger högre investeringsrisk."}
            ]},
            6: {"intro": "Att värdera datarisk i praktiken — en checklista.", "blocks": [
                {"type": "text", "content": "För att bedöma datarisk i ett svenskt bolag, ställ följande frågor: 1) Vilken typ av personuppgifter samlas? (Känslig > icke-känslig) 2) Var lagras datan? (EU/EEA > USA > övriga) 3) Hur länge sparas datan? (< 2 år > > 5 år) 4) Har bolaget ISO 27001 och ISO 27701? 5) Finns cyberförsäkring? (Täckning och självrisk) 6) Vilka intrång har skett senaste 3 åren? 7) Hur transparent är bolaget i årsredovisningen?\n\nEtt bolag med låg poäng på flera av dessa frågor har hög datarisk. AKM1-metodiken ger lägre V18-poäng till sådana bolag, vilket motsvarar högre riskpremie. Investerare bör kräva högre avkastning eller undvika bolaget helt.\n\nFör portföljbyggande är det värt att diversifiera bort från datatunga bolag. En portfölj med 30% Spotify, Truecaller, Klarna har hög koncentrerad datarisk. En mer balanserad portfölj med industri- och materialbolag (Atlas Copco, Sandvik, Boliden) har lägre datarisk, men andra risker."},
                {"type": "insight", "content": "Svenska investerare missbedömer ofta datarisk eftersom den är osynlig — en bolagsbeskrivning kan se perfekt ut men dölja dussintals GDPR-känsliga processer."},
                {"type": "definition", "content": "ISO 27701: Internationell standard för 'Privacy Information Management' — en utökning av ISO 27001 med specifikt fokus på personuppgifter."},
                {"type": "text", "content": "Slutgiltig rekommendation: behandla datarisk som en kreditrisk. Precis som du bedömer ett bolags skuldsättning, bedöm dess dataexponering. Ett bolag med 'data leverage' (mycket data per intäktskrona) har högre latent risk, precis som ett bolag med hög skuldsättning har högre konkursrisk.\n\nFölj IMY:s årsredovisning för att se vilka bolag som granskas. Varje år publicerar IMY en sammanställning av pågående ärenden — detta är en ledtråd till vilka bolag som kan få böter. För svensk retail-investerare är 30 minuters läsning av IMY-rapporten årligen en väl investerad tid."}
            ]}
        }
    },
    "rk-14-esgrisk": {
        "why": "ESG-risk (miljö, sociala, styrelse) påverkar svenska bolags värdering direkt. Pensionssystemet AP-fonderna har krav på fossilfria portföljer, och bolag utan ESG-strategi kan uteslutas från index. För retail-investerare är ESG inte bara etik — det är finansuell risk.",
        "history": {
            "origin": "ESG som begrepp myntades i FN-rapporten 'Who Cares Wins' (2004), men rötterna går till 1990-talets etiska fonder. Sweden var tidigt ute — etisk screening infördes i AP-fonderna 2002 och KPA Pension har haft fossilfria krav sedan 2015.",
            "evolution": "EU:s Taxonomi (2020) och SFDR (Sustainable Finance Disclosure Regulation, 2021) skapade ett enhetligt klassificeringssystem. Fonder delas nu in i Article 6 (icke-ESG), Article 8 ('light green'), och Article 9 ('dark green'). Svenska fonder har anpassat sig snabbt.",
            "modern": "Idag kräver stora svenska institutioner (AP1–4, AMF, Alecta) att bolag rapporterar enligt GRI, SASB, eller TCFD. Bolag utan rapportering får lägre ägande och högre kapitalkostnad. Grön tvätt (greenwashing) är en växande risk — ESMA granskar fonders ESG-påståenden hårdare 2024."
        },
        "lynchSection": "Lynch ogillade ESG som investeringskriterium. Han menade att 'etik och avkastning är olika mått' och att bolag skall bedömas på resultat, inte värderingar. Samtidigt undvek han bolag med uppenbara skandalrisker.",
        "grahamSection": "Graham skulle ha varit skeptisk till ESG som värderingsfaktor, men erkände 'reputational risk' som verkligt. Han menade att bolag med etiska problem har högre riskpremie och därmed högre avkastningskrav.",
        "ak1Section": "AKM1 inkluderar ESG i V18 (regulatoriska risker) och V14 (varumärke). ESG-relaterade skandaler drabbar varumärket direkt, och regulatorisk ESG-risk ökar. Bolag med låg ESG-transparens får lägre poäng på båda variablerna.",
        "chapters": {
            1: {"intro": "ESG:s tre dimensioner och deras koppling till finansiell risk.", "blocks": [
                {"type": "text", "content": "ESG delas in i miljö (E), sociala (S), och styrelse (G). Miljöfaktorer inkluderar klimatpåverkan, resursanvändning, och föroreningar. Sociala faktorer inkluderar arbetsvillkor, mänskliga rättigheter, och kundrelationer. Styrelsefaktorer inkluderar ägarstruktur, styrelsesammansättning, och ersättningssystem.\n\nFör svensk retail-investerare är ESG inte etik — det är finansiel risk. Ett bolag med dålig ESG-profil kan uteslutas från index (MSCI, FTSE4Good), få högre kapitalkostnad, eller drabbas av skandaler som raderar börsvärde. ESG är därmed en del av risken, inte avkastningen.\n\nForskning visar att bolag med stark ESG-profil har lägre volatilitet och bättre krisprestanda. Detta är inte detsamma som högre avkastning — men lägre volatilitet ger högre riskjusterad avkastning över tid."},
                {"type": "insight", "content": "MSCI ESG Leaders Index har underpreparerat S&P 500 marginellt sedan 2015, men haft 15% lägre volatilitet — riskjusterat en vinnare."},
                {"type": "definition", "content": "ESG: Förkortning för Environmental, Social, Governance — ett ramverk för att bedöma bolags hållbarhet och etik utöver finansiella mått."},
                {"type": "text", "content": "Svenska bolag ligger generellt högt på ESG. H&M, Essity, och Atlas Copco har toppbetyg från MSCI och Sustainalytics. Men variationerna är stora — bolag inom gruvor (Boliden), olja (Lundin Energy), och skog (Sveza) har lägre betyg och därmed högre riskpremie.\n\nFör investerare är det centrala att förstå vad som ligger bakom ett ESG-betyg. Ett bolag kan ha högt betyg totalt men lågt på specifika dimensioner — t.ex. stark miljöprestanda men dåliga arbetsförhållanden i leverantörskedjan. Granskning under huven är viktigare än top-down betyg."}
            ]},
            2: {"intro": "EU Taxonomi och SFDR — det regulatoriska ramverket.", "blocks": [
                {"type": "text", "content": "EU Taxonomi (2020) definierar vilka ekonomiska aktiviteter som är 'environmentally sustainable'. Ett bolag kan rapportera hur stor andel av omsättning, capex, och opex som är 'taxonomy-aligned'. Detta ger investerare en mätbar siffra att jämföra.\n\nSFDR (2021) klassificerar fonder i tre nivåer: Article 6 (icke-ESG, får ej marknadsföras som hållbara), Article 8 ('light green' — främjar hållbarhet), och Article 9 ('dark green' — har hållbara investeringsmål). Majoriteten av svenska fonder är Article 8, medan 'rena' ESG-fonder är Article 9.\n\nFör investerare betyder detta att fondens ESG-påståenden måste backas av rapportering. Fonder som marknadsförs som 'hållbara' men är Article 6 kan granskas av Finansinspektionen. ESMA:s 2024-riktlinjer skärper kraven ytterligare."},
                {"type": "insight", "content": "En fond kan vara Article 8 och ändå ha 0% taxonomy-aligned innehav — nivån anger ambition, inte faktisk hållbarhet."},
                {"type": "definition", "content": "SFDR: Sustainable Finance Disclosure Regulation — EU-förordning som kräver att finansaktörer redovisar hållbarhetsrisker och -mål i sina produkter."},
                {"type": "text", "content": "Svenska bolag måste från 2024 rapportera enligt CSRD (Corporate Sustainability Reporting Directive). Detta ersätter de tidigare otydliga riktlinjerna med en standardiserad rapportering som granskas av revisor. Kostnaden för CSRD-compliance uppskattas till 0,1–0,3% av omsättning för stora bolag.\n\nFör investerare är CSRD en möjlighet — mer och bättre data. Nackdelen är att rapporteringen är komplex och svår att jämföra mellan bolag. Verktyg som Sustainalytics, MSCI ESG, och ISS ESG hjälper till att normalisera, men kostar pengar. För privatpersoner är det oftast bättre att förlita sig på fonder med dedikerad ESG-analys."}
            ]},
            3: {"intro": "Grön tvätt (greenwashing) och hur man upptäcker den.", "blocks": [
                {"type": "text", "content": "Grön tvätt innebär att ett bolag överdriver eller fabricerar sina miljöpåståenden. Detta blev vanligare efter 2018 när ESG-fonder började marknadsföras aggressivt. ESMA och Finansinspektionen granskar numera ESG-påståenden noggrant, och flera fonder har tvingats ändra klassificering.\n\nFör investerare är det centrala att skilja 'ambition' från 'resultat'. Ett bolag kan ha 'net zero by 2050'-mål utan att ha några konkreta steg dit. Faktisk utsläppsminskning de senaste 3 åren är en bättre mätare än framtida mål.\n\nEn röd flagga är när ESG-rapporten är längre än årsredovisningen men saknar kvantitativa mål. Ett seriöst bolag har specifika, mätbara mål — t.ex. '50% utsläppsminskning till 2030 mot 2020-bas'. Vaga mål som 'sträva efter hållbarhet' är grön tvätt."},
                {"type": "insight", "content": "Bolag med 'net zero' i titeln på ESG-rapporten men utan scope 3-utsläpp redovisade har 80% sannolikhet för grön tvätt enligt InfluenceMap."},
                {"type": "definition", "content": "Scope 3-utsläpp: Indirekta utsläpp i värdekedjan — från leverantörer, kunder, och produktanvändning. Ofta 70–90% av totala utsläpp, men svårast att mäta."},
                {"type": "text", "content": "Svenska fonder har haft flera fall av grön tvätt. Swedbank Robur fick kritik 2022 för en fond som marknadsfördes som 'fossilfri' men innehöll bolag med indirekt fossiltrafik (flyg, sjöfart). Triodos Investment Management omklassificerade flera fonder 2023 efter ESMA-granskning.\n\nFör investerare är det värt att granska fondens 'engagement policy' — hur den faktiskt påverkar bolag. Fonder som bara säljer bolag de ogillar har ingen påverkan. Fonder som engagerar sig genom dialog och röstning har större effekt, men kräver resurser och tid."}
            ]},
            4: {"intro": "ESG-skandaler och deras börspåverkan.", "blocks": [
                {"type": "text", "content": "Lundin Energy (numera Orrön Energy) fick kritik för sina tidigare oljeprojekt i Sudan där civila evakuerades med våld. Aktien föll 15% över 3 månader 2020 när kritiken eskalerade, trots ingen fundamental förändring. Detta visar hur ESG-risk kan slå oberoende av resultat.\n\nH&M har haft flera ESG-kontroverser — från arbetsförhållanden i fabriker till bränder i klädeslager. Aktien har varit mer volatil än branschgenomsnittet, delvis på grund av ESG-nyheter. Varje negativ rapport kan ge 2–5% ras på en dag.\n\nBoliden har kritiserats för utsläpp från gruvor och dammkatastrofer. Trots förbättringar över tid, kvarstår en 'riskpremie' i aktien jämfört med internationella gruvbolag med liknande finansiell prestanda. Detta är ett exempel på hur historisk EGS-risk kan kvarstå i värderingen."},
                {"type": "insight", "content": "Bolag med tidigare ESG-skandaler har i genomsnitt 5–10% lägre P/E än rena bolag, även 5+ år efter händelsen."},
                {"type": "definition", "content": "ESG-skandal: Publikt avslöjande av miljöbrott, arbetsrättsbrott, eller styrelsemisskötsel som leder till mediabevakning och börspåverkan."},
                {"type": "text", "content": "För investerare är ESG-skandaler oförutsägbara men inte slumpmässiga. Bolag med historiskt dålig ESG-profil har högre risk för nya skandaler. En strategi är att undvika bolag i bottenkvartilen av ESG-betyg, särskilt i branscher med hög exponering (gruvor, energi, textil).\n\nEn annan strategi är 'engagerat ägande' — att äga bolag med ESG-problem och aktivt driva förändring. Detta är vad stora institutionella investerare gör (AP-fonderna, AMF). För retail-investerare är detta svårt, men man kan välja fonder som har denna strategi."}
            ]},
            5: {"intro": "Klimatrisk — fysisk och transitionell.", "blocks": [
                {"type": "text", "content": "Klimatrisk delas i fysisk (extremväder, havsnivåhöjning) och transitionell (politiska beslut, teknologiskiftet). Båda påverkar svenska bolag. Fysisk risk drabbar bolag med tillgångar i utsatta områden — skogsbolag (brandsrisk), fastighetsbolag (översvämning), turismbolag (extremväder).\n\nTransitionell risk drabbar fossilberoende bolag — olja, kol, bilar med förbränningsmotor. Ett skift till förnybar energi och elbilar kan radera värde i traditionella bolag. Volvo Cars värderas numera med 'EV transition discount' på 15–20% jämfört med om de bara tillverkade bensinbilar.\n\nTCFD (Task Force on Climate-related Financial Disclosures) ger en ram för att rapportera klimatrisk. Svenska bolag över 500 anställda måste från 2024 rapportera enligt TCFD eller CSRD. Detta ger investerare bättre data, men kräver kompetens att tolka."},
                {"type": "insight", "content": "Svenska skogsbolag (Sveza, Holmen) har ökad fysisk risk från skogsbränder — 2018 och 2023 kostade branschen över 2 miljarder kr i brandsskador."},
                {"type": "definition", "content": "Transition risk: Finansiell risk från omställning till lågkolbonomisk — politik, teknikskiften, förändrade preferenser. Skiljer sig från fysisk klimatrisk som extrema väderhändelser."},
                {"type": "text", "content": "För investerare är det värt att skilja mellan 'klimatanpassade' och 'klimatexponerade' bolag. Klimatanpassade bolag (Vattenfall vind, SSAB med HYBRIT) har positionerat sig för transitionen. Klimatexponerade bolag (Preem, gamla Volvo Cars) har högre risk.\n\nEn klimatstressportfölj bör ha låg exponering mot fossilberoende branscher och hög exponering mot lösningar (förnybar energi, energieffektivitet, cirkulär ekonomi). Men var försiktig — många 'gröna' bolag är övervärderade just för att marknaden prisar in deras fördelar. Jämför värdering med fundamentals, inte bara ESG-profil."}
            ]},
            6: {"intro": "Att integrera ESG i investeringsprocessen.", "blocks": [
                {"type": "text", "content": "För svensk retail-investerare finns tre sätt att integrera ESG: 1) Uteslutning — undvika bolag i specifika branscher eller med låga betyg. 2) Best-in-class — välja de bästa bolagen i varje bransch. 3) Tematisk — investera i specifika lösningar (solceller, vatten, cirkulär ekonomi).\n\nUteslutning är enklast men ger mest koncentrerad portfölj. Best-in-class är mer diversifierad men kräver ESG-data. Tematisk är fokuserad men kan ge hög volatilitet. De flesta privatpersoner bör använda uteslutning + best-in-class kombinerat.\n\nViktigt: ESG skall aldrig vara det enda kriteriet. Ett bolag med bra ESG men dålig fundamental värdering är en dålig investering. Och ett bolag med dålig ESG men stark fundamental och låg värdering kan vara en bra 'value'-investering, medveten om ESG-risken."},
                {"type": "insight", "content": "Ren ESG-screening har historiskt gett lägre avkastning än breda index — men lägre volatilitet. Ren value-investering har gett högre avkastning men högre volatilitet. En kombination kan vara optimal."},
                {"type": "definition", "content": "Best-in-class: ESG-strategi där man investerar i de bästa bolagen i varje bransch, istället för att utesluta hela branscher. Ger diversifiering med ESG-fokus."},
                {"type": "text", "content": "Slutgiltig rekommendation: använd ESG som en riskfaktor, inte som en etisk filter. Ett bolag med låg ESG-betyg och hög ESG-riskpremie i värderingen kan vara en god investering om marknaden överdriver risken. Ett bolag med hög ESG-betyg och dyr värdering kan vara en dålig investering om marknaden ignorerar andra risker.\n\nFölj ESG-utvecklingen över tid — bolag som förbättrar sig kan få värderingsuppvärdering. Bolag som försämras kan få nedvärdering. Detta är 'ESG momentum' — en strategi som historiskt har gett positiv alfa. Fonder som Swedbank Robur Climate Impact och Storebrand Global All Countries använder denna strategi."}
            ]}
        }
    },
    "rk-15-cykelrisk": {
        "why": "Cykelrisk är risken att ett bolag befinner sig i en nedåtgående konjunkturcykel. Svenska industricolag (Atlas Copco, SKF, Sandvik) är cykliska och kan förlora 50%+ av omsättning under en recession. Att förstå cykelpositionen är avgörande för timing och värdering.",
        "history": {
            "origin": "Konjunkturcyklar identifierades redan av Kitchin (1923, 40-månaders cykel), Juglar (1862, 7–11 års cykel), och Kuznets (1930, 15–25 års cykel). Schumpeter (1939) kombinerade dessa till en teori om teknologiska vågor.",
            "evolution": "Efter Bretton Woods (1944) blev cyklerna mindre uttalade pga. aktiv penningpolitik. Oljekriserna 1973 och 1979 visade dock att externa chocker kan skapa djupa cykler. Finanskrisen 2008 och pandemin 2020 visade att moderna cykler kan vara både djupa och snabba.",
            "modern": "Idag använder investerare 'leading economic indicators' (LEI) som befattningsindex, byggtillstånd, och räntespread för att förutse cykelläget. NBER i USA och Konjunkturinstitutet i Sverige publicerar officiella cykeldateringar."
        },
        "lynchSection": "Lynch varnade för cykliska bolag och föredrog 'growth at reasonable price'. Han menade att timing av cykler är omöjligt och att investerare bör fokusera på bolag som kan växa oavsett cykel.",
        "grahamSection": "Graham visade att cykliska bolag har lägre P/E vid botten av cykeln (när vinsten är hög) och högre P/E vid toppen (när vinsten är låg). Detta är omvänd mot intuition — 'value traps' uppstår när investerare köper lågt P/E vid cykeltopp.",
        "ak1Section": "AKM1 bedömer cykelrisk via V12 (intäktsstabilitet) och V05 (P/B). Cykliska bolag får låga poäng på V12, och kräver därmed högre marginal of safety (lägre P/B) för att vara attraktiva.",
        "chapters": {
            1: {"intro": "Vad är konjunkturcykler och hur uppstår dem.", "blocks": [
                {"type": "text", "content": "Konjunkturcykler är återkommande svängningar i ekonomisk aktivitet — expansion, topp, contraction, botten. En komplett cykel varar typiskt 5–7 år. Orsakerna är omtvistade — monetära skolor (Friedman) pekar på räntepolitik, reala skolor (Schumpeter) på teknologiska skiften, keynesianska på aggregat efterfrågan.\n\nFör svensk retail-investerare är cykelrisken konkret. Industrisektorn (Atlas Copco, SKF, Sandvik) har orderbook som varierar 30–50% mellan botten och topp av cykeln. Bilsektorn (Volvo Cars) har försäljning som rasar 20%+ under en recession. Banksektorn (Handelsbanken, SEB) har kreditförluster som flerdubblas.\n\nCykelposition är därmed en central investeringsfråga. Att köpa ett cykliskt bolag vid toppen av cykeln (lågt P/E, hög vinst) är en klassisk 'value trap'. Att köpa vid botten (högt P/E, låg vinst) kan ge hög avkastning när cykeln vänder."},
                {"type": "insight", "content": "Svenska industriaktier har i genomsnitt 2x högre vinstvolatilitet än konsumentaktier — cykelrisken är en systematisk skillnad."},
                {"type": "definition", "content": "Konjunkturcykel: Återkommande svängning i ekonomisk aktivitet mellan expansion och contraction. Varar typiskt 5–7 år i modern tid."},
                {"type": "text", "content": "För att identifiera cykelposition används 'leading indicators' — befattningsindex, byggtillstånd, räntespread (10-årig minus 3-månaders). Dessa vänder 6–12 månader före själva cykeln. Konjunkturinstitutet publicerar svensk cykelanalys kvartalsvis.\n\nEn mer praktisk metod är att följa orderbooks. Bolag som Atlas Copco publicerar orderbook kvartalsvis — om orderbook vänder neråt 2 kvartal i rad, är en cykelförändring på väg. Detta ger investerare en 3–6 månaders föraning."}
            ]},
            2: {"intro": "Cykliska vs acykliska bolag — skillnaden.", "blocks": [
                {"type": "text", "content": "Cykliska bolag har intäkter som varierar kraftigt med konjunkturen. Svenska exempel: Atlas Copco (kapitalvaror), SKF (lager), SSAB (stål), Volvo Cars (bilar), Electrolux (vitvaror), H&M (mode). Deras intäkter kan variera 30–50% mellan botten och topp av cykeln.\n\nAcykliska bolag har intäkter som är stabila över konjunkturen. Svenska exempel: ICA (livsmedel), Telia (telekom), Essity (hygien), Investor (investmentbolag med bred portfölj). Deras intäkter varierar mindre än 10% mellan cykelbotten och topp.\n\nSemi-cykliska bolag är däremellan — de påverkas av cykeln men mindre än cykliska. Exempel: H&M (kläderna är mer cykliska än mat men mindre än lyx), Sandvik (verktyg är cykliska men servicen stabil). Dessa kräver mer nyanserad analys."},
                {"type": "insight", "content": "En portfölj med 70% acykliska och 30% cykliska bolag har historiskt gett liknande avkastning som 100% cykliska, men med halva volatiliteten."},
                {"type": "definition", "content": "Acyklisk: Ekonomisk aktivitet som är relativt okänslig för konjunkturcykler. Exempel: mat, el, sjukvård, telekom."},
                {"type": "text", "content": "För portföljbyggande är balansen mellan cykliska och acykliska avgörande. En portfölj med 100% cykliska bolag ger hög avkastning under expansioner men djupa ras under contractioner. En portfölj med 100% acykliska ger stabil men lägre avkastning.\n\nEn 'barbell'-strategi — 60% acykliska + 40% cykliska med aktiv rebalansering — ger oftast bäst riskjusterad avkastning. När cykeln vänder ner, säljs cykliska och köps acykliska. När cykeln vänder upp, köps cykliska billigt."}
            ]},
            3: {"intro": "Att tidsmäta cykler — möjligt eller omöjligt?", "blocks": [
                {"type": "text", "content": "Cykeltiming är omöjligt att göra perfekt, men möjligt att göra probabilistiskt. Bäst är att kombinera flera indikatorer: 1) Räntespread (10-årig minus 3-månaders statsränta) — negativ spread indikerar kommande recession. 2) Befattningsindex — under 50 indikerar contraction. 3) Orderbook för cykliska bolag — nedgång 2 kvartal i rad indikerar cykeltopp.\n\nFör Sverige är Konjunkturinstitutets (KI) barometer en bra indikator. KI publicerar kvartalsvis bedömning av cykelposition — 'expansion', 'topp', 'contraction', 'botten'. Historiskt har KI:s prognoser varit korrekta i 70% av fallen, men med 6–12 månaders fördröjning.\n\nNBER i USA daterar officiellt recessioner, men ofta först 12+ månader efter att de börjat. Detta gör officiella dateringar oanvändbara för aktiva investerare. Man måste använda realtidsindikatorer."},
                {"type": "insight", "content": "Omvänd yield curve (kort ränta högre än lång) har förutspått alla 7 amerikanska recessioner sedan 1960, men med 6–24 månaders fördröjning."},
                {"type": "definition", "content": "Omvänd yield curve: När korta räntor är högre än långa. En klassisk recessionssignal som indikerar att marknaden förväntar sig räntesänkningar."},
                {"type": "text", "content": "För svensk retail-investerare är det enklare att använda en regel: köp cykliska bolag när deras P/E är högt (dvs. vinsten är låg, cykeln i botten) och sälj när P/E är lågt (vinsten hög, cykeln i topp). Detta är omvänd mot intuition och därmed ofta svårt att följa.\n\nEn konkret metod: räkna ut 'cyclically adjusted P/E' (CAPE, Shiller P/E) genom att ta medelvärdet av vinsten de senaste 10 åren. Detta utjämnar cykelvariationer. Ett bolag med högt aktuellt P/E men lågt CAPE kan vara en god köppmöjlighet — vinsten är tillfälligt låg."}
            ]},
            4: {"intro": "Value traps i cykliska bolag.", "blocks": [
                {"type": "text", "content": "En value trap uppstår när investerare köper ett cykliskt bolag med lågt P/E, trots att den låga värderingen beror på att vinsten är på cykeltopp. När cykeln vänder neråt, faller både vinsten och P/E (investor sentiment). Dubbel nedgång.\n\nSvenskt exempel: SSAB 2007 hade P/E 5 och såg extremt billigt ut. Men 2008–2009 föll vinsten 80% och P/E föll till 3 — aktien rasade 75%. Investerare som köpte på 'lågt P/E' förlorade stort. Rätt analys hade varit: vinsten 2007 var exceptionellt hög, normaliserad vinst gav P/E 15.\n\nFör att undvika value traps, normalisera vinsten över en cykel. Räkna ut medelvinsten de senaste 7–10 åren, och använd denna för att beräkna 'normaliserat P/E'. Om aktuellt P/E är mycket lägre än normaliserat P/E, är bolaget på cykeltopp — undvik eller sälj."},
                {"type": "insight", "content": "70% av 'value opportunities' i cykliska bolag är faktiskt value traps — den låga värderingen reflekterar kommande vinstnedgång, inte undervärdering."},
                {"type": "definition", "content": "Value trap: Ett bolag som verkar billigt (lågt P/E eller P/B) men där lågvärderingen är motiverad av kommande problem — ofta en vinstnedgång i cykliska bolag."},
                {"type": "text", "content": "En annan value trap är 'secular decline förklaras som cyklisk'. Ett bolag i strukturell nedgång (t.ex. pappersbruk sedan 2000) kan se billigt ut med lågt P/B, men vinsten kommer aldrig återhämta sig. Att skilja cyklisk från strukturell nedgång är centralt.\n\nSignal: om bolaget har förlorat marknadsandelar under 2+ cykler, är det strukturellt. Om intäkterna återhämtar sig i varje cykel, är det cykliskt. Svenskt exempel: Holmen (papper) har strukturell nedgång, Atlas Copco har cyklisk variation."}
            ]},
            5: {"intro": "Hur svenska sektorer reagerar på cykeln.", "blocks": [
                {"type": "text", "content": "Svenska industrisektorn (Atlas Copco, SKF, Sandvik) är den mest cykliska. Orderbook varierar 30–50% mellan cykelbotten och topp. Vinster kan flerdubblas eller halveras. P/E varierar 8 (topp) till 25 (botten) — omvänd mot intuition.\n\nSvensk banksektor (Handelsbanken, SEB, Swedbank) är semi-cyklisk. Intäkter stabilare än industri, men kreditförluster flerdubblas under recessioner. P/E är stabilare (10–15) men ROE varierar 8–15%. Bankaktier rör sig ofta med cykeln, men mindre extremt.\n\nKonsumentsektorn (H&M, ICA, Essity) varierar. ICA är acykliskt (folk måste äta). H&M är semi-cykliskt (kläder kan skjutas upp). Lyxbolag (som om fanns på svenska börsen) skulle vara mest cykliska. Essity är semi-acykliskt (hygienartiklar är nödvändiga)."},
                {"type": "insight", "content": "Under 2008–2009 föll svenska industriaktier 65% i snitt, banker 55%, konsument 40% — cykelkänsligheten varierar markant mellan sektorer."},
                {"type": "definition", "content": "Orderbook: Värdet av obetalda ordrar som ett bolag har. En ledande indikator för cykliska bolag — stigande orderbook indikerar expansion, fallande contraction."},
                {"type": "text", "content": "Fastighetssektorn (Castellum, Fabege) är semi-cyklisk men med lång lag. Hyresintäkter är stabila (5–10 års kontrakt), men fastighetsvärden varierar med räntan. En ränteuppgång kan sänka fastighetsvärdena 20%+ utan att påverka kortsiktig vinst. Aktien reagerar dock omedelbart på ränteförväntningar.\n\nFör investerare är det värt att ha sektorbreddning. En portfölj med 30% industri, 20% bank, 20% konsument, 20% fastighet, 10% telekom har balanserad cykelexponering. En portfölj med 50% industri har extrem cykelrisk."}
            ]},
            6: {"intro": "Cykelstrategi för svensk retail-investerare.", "blocks": [
                {"type": "text", "content": "En praktisk strategi är 'cykel-medveten long-only': 1) Identifiera cykelposition med KI:s barometer och orderbook. 2) Vid expansion: öka cykliska bolag (industri, bank, fastighet). 3) Vid contraction: minska cykliska, öka acykliska (telekom, livsmedel, hygien). 4) Vid botten: köp cykliska billigt med högt P/E. 5) Vid topp: sälj cykliska med lågt P/E.\n\nDenna strategi ger inte perfekt timing, men historiskt 1–2% extra avkastning årligen över köp-och-håll. Nackdelen är mer aktivitet och transaktionskostnader. För investerare med låg risktolerans kan köp-och-håll av acykliska portfölj vara bättre.\n\nViktigt: cykelposition är probabilistisk, inte deterministisk. Även vid 'tydlig botten' kan cykeln fortsätta neråt i 6–12 månader. Ha alltid marginal of safety — köp inte med marginal, utan med 30%+ diskontant mot beräknat intrinsic value."},
                {"type": "insight", "content": "En cykelmedveten strategi med 20% acyklisk kärna och 80% aktivt cykelallokerat har historiskt slagit index med 1,5% årligen, med lägre volatilitet."},
                {"type": "definition", "content": "Cykelposition: Var i konjunkturcykeln ekonomin befinner sig — expansion, topp, contraction, eller botten. Bestäms probabilistiskt genom kombination av indikatorer."},
                {"type": "text", "content": "Slutgiltig rekommendation: för svensk retail-investerare är det enklare att använda en 'cykel-resilient portfölj' än att försöka tidscykeln. Detta innebär: 60% acykliska bolag (ICA, Telia, Essity, Investor) och 40% cykliska med starka balansräkningar (Atlas Copco, SKF med låg skuldsättning). Denna portfölj klarar både expansioner och contractioner utan aktiv rebalansering.\n\nOm du vill vara aktiv: använd en 12-månaders regel. Sälj cykliska bolag när orderbook vänt ner 2 kvartal i rad. Köp cykliska bolag när orderbook vänt upp 2 kvartal i rad. Detta ger sent men säkert svar — du missar botten och toppen, men får majoriteten av cykelvändningen."}
            ]}
        }
    }
}

# ts courses
TS_CONTENT = {
    "ts-08-volymanalys": {
        "why": "Volymanalys är en av de mest underskattade färdigheterna bland svenska investerare. Volymen bekräftar eller förnekar prisrörelser — en uppgång utan volym är misstänkt, en nedgång med hög volym är en varning. Att läsa volymen rätt skiljer professionella från amatörer.",
        "history": {
            "origin": "Volym som indikator kan spåras till Charles Dow (1884) som inkluderade volym i hans Dow-teori. Richard Wyckoff (1910-talet) formaliserade volymanalysen i sin 'Composite Operator'-metod. Paul de la Garza utvecklade 'Volume Spread Analysis' på 1990-talet.",
            "evolution": "Under 1900-talet blev volym standard i alla diagram. Med elektronisk handel från 1990-talet kunde volym analyseras i realtid. Volume-weighted average price (VWAP) blev standardmått. On-Balance Volume (OBV) av Joe Granville (1963) var den första populära volymindikatorn.",
            "modern": "Idag används volym tillsammans med order flow och market profile för att förstå marknadens struktur. Algoritmisk handel har ökat volymen på specifika tidpunkter (öppning, stängning), vilket gör traditionell volymanalys mer komplex. AK1TS 25-cellers matris integrerar volym i tidshorisonter."
        },
        "lynchSection": "Lynch ogillade teknisk analys och volym. Han menade att 'prisrörelser utan fundamental grund är brus'. Samtidigt erkände han att volym kan signalera institutionellt intresse som privatpersoner inte ser.",
        "grahamSection": "Graham avfärdade volymanalys helt och ansåg att marknadens kortsiktiga svängningar var oförutsägbara. 'Volymen speglar känslor, inte värde,' skrev han.",
        "ak1Section": "AKM1 använder volym som bekräftelse på V12 (intäktsstabilitet) — bolag med stabil volym i sina aktier har ofta stabilare intäkter. Volymstick kan varna om institutionell utförsäljning innan fundamentals dalar.",
        "chapters": {
            1: {"intro": "Volymens grundläggande roll i prisrörelser.", "blocks": [
                {"type": "text", "content": "Volym representerar antalet aktier som omsätts under en period. Hög volym indikerar starkt intresse (både köp och sälj), låg volym indikerar svagt intresse. Den grundläggande regeln är att prisrörelser med hög volym är mer betydelsefulla än de med låg volym.\n\nDow-teorin säger att en uppgång skall bekräftas av ökande volym. Om priset stiger men volymen faller, är uppgången svag — få deltagare stödjer den. Om priset faller med hög volym, är nedgången stark — många vill sälja.\n\nFör svensk retail-investerare är volym extra viktig för små bolag (small cap). En aktie som stiger 5% på 100 000 kr omsättning är inte samma sak som en som stiger 5% på 50 miljoner kr. Den första kan manipuleras lätt, den andra kräver institutionellt deltagande."},
                {"type": "insight", "content": "Volym på uppåtgående dagar som är 2x högre än på nedåtgående dagar indikerar institutionellt köpstryck — en av de mest tillförlitliga volymsignalerna."},
                {"type": "definition", "content": "Volym: Antalet aktier som omsätts under en given period (dag, vecka, timme). Hög volym indikerar starkt intresse, låg volym svagt."},
                {"type": "text", "content": "Ett vanligt misstag är att bara titta på totalvolymen, inte riktningen. 'Volyme analysis' innebär att skilja köpvolym (priset stiger) från säljvolym (priset faller). Ett bolag kan ha hög volym men om 80% är säljvolym, är det en negativ signal.\n\nEnkel metod: beräkna volymen på uppåtgående dagar och nedåtgående dagar separat. Om köpvolymen är 1,5–2x högre än säljvolymen under 10 dagar, är trenden positivt bekräftad. Omvänt varnar för nedgång."}
            ]},
            2: {"intro": "Volymindikatorer — OBV, VWAP, och andra.", "blocks": [
                {"type": "text", "content": "On-Balance Volume (OBV) av Joe Granville (1963) var den första populära volymindikatorn. OBV adderar volym på uppåtgående dagar och subtraherar på nedåtgående. Linjen skall följa priset — om OBV vänder ner innan priset, är det en varning om kommande prisnedgång.\n\nVolume-Weighted Average Price (VWAP) är standardmåttet för institutionella handlare. VWAP beräknar genomsnittligt pris vägt med volym. Pris över VWAP indikerar starkt köptryck, under VWAP säljtryck. Många algoritmer handlar runt VWAP som referenspunkt.\n\nAccumulation/Distribution Line (A/D) är en annan indikator som väger volym med prisposition. A/D stiger när priset stänger i övre halvan av dagens range med hög volym — tecken på ackumulering av institutioner."},
                {"type": "insight", "content": "OBV divergenser (OBV vänder ner medan priset fortsätter upp) har förutspått 8 av 10 större börsfall sedan 1970 — en av de mest tillförlitliga signalerna."},
                {"type": "definition", "content": "VWAP: Volume-Weighted Average Price — genomsnittligt pris vägt med volym under en period. Används av institutionella handlare som benchmark."},
                {"type": "text", "content": "För svensk retail-investerare är VWAP extra användbar vid intradagshandel. Om du köper en aktie långt över VWAP, betalar du premium. Om du köper nära VWAP, får du genomsnittligt pris. Många mäklare (Avanza, Nordnet) visar VWAP i realtid.\n\nEn strategi är att köpa när priset testar VWAP under en uppgång. Om VWAP håller som stöd, är trenden intakt. Om priset bryter under VWAP med volym, är trenden i fara. Denna strategi fungerar bäst på bolag med hög likviditet (Volvo, Ericsson, Atlas Copco)."}
            ]},
            3: {"intro": "Volymprofile — volym per prisnivå, inte per tid.", "blocks": [
                {"type": "text", "content": "Volymprofile skiljer sig från traditionell volym (som visas i botten av diagrammet). Volymprofile visar volym per prisnivå, vilket avslöjar var flest affärer skedde. Detta skapar 'Point of Control' (POC) — den prisnivå med högst volym.\n\nPOC fungerar som magnet — priset tenderar att återvända till POC vid svängningar. Nivåer med hög volym blir stöd/motstånd, nivåer med låg volym blir 'low volume nodes' där priset rör sig snabbt igenom.\n\nFör svenska investerare är volymprofile användbart för att identifiera 'fair value' — den nivå där flest köpare och säljare möttes. Om aktien är långt över POC, kan den vara överköpt. Om långt under, översåld. Detta ger en objektiv referenspunkt, inte bara teknisk."},
                {"type": "insight", "content": "Pris som stannar vid POC i 3+ dagar indikerar stark 'fair value' — en utbrytning därifrån ger oftast hållbar trend."},
                {"type": "definition", "content": "Point of Control (POC): Den prisnivå med högst volym under en period. Fungerar som magnet och stöd/motstånd."},
                {"type": "text", "content": "Value Area (VA) är den prisrange som innehåller 70% av volymen. VA High är övre gränsen, VA Low nedre. Pris utanför VA indikerar överköpt/översåld marknad. Pris inuti VA är 'fair value'.\n\nEn strategi: köp när priset testar VA Low under en uppgång, sälj när priset testar VA High under en nedgång. Detta ger bra inträde baserat på volymstruktur, inte bara pris. Nackdelen är att det kräver avancerad charting-programvara (TradingView, Bloomberg)."}
            ]},
            4: {"intro": "Volym vid brytpunkter — bekräftelse eller misslyckande.", "blocks": [
                {"type": "text", "content": "En utbrytning från stöd/motstånd skall bekräftas med volym. Utan volym är utbrytningen misstänkt — sannolikt 'fake breakout' som snabbt vänder. Med volym är utbrytningen sannolikt äkta och ger fortsatt trend.\n\nRegeln: utbrytning med volym 1,5–2x snitt ger 70% sannolikhet för hållbarhet. Utbrytning med volym under snitt ger 60% sannolikhet för misslyckande. Detta är en av de mest tillförlitliga reglerna i teknisk analys.\n\nFör svenska bolag är volymbekräftelse extra viktig vid kvartalsrapporter. En rapport som pushar aktien upp 5% på låg volym är mindre övertygande än en som pushar 5% på 3x volym. Det senare indikerar att institutionella investerare ändrade position."},
                {"type": "insight", "content": "'Fake breakouts' utan volym är vanligast på måndagar och fredagar — dagar med lågt institutionellt deltagande. Undvik att handla utbrytningar dessa dagar."},
                {"type": "definition", "content": "Fake breakout: När priset bryter en nivå men snabbt vänder tillbaka. Ofta orsakad av låg volym eller algoritmisk jakt på stop-loss."},
                {"type": "text", "content": "En variant är 'volume climax' — en enskild dag med extremt hög volym (5x snitt). Dessa indikerar ofta en topp eller botten. Efter en lång uppgång med volume climax dag, vänder ofta priset ner. Efter en lång nedgång med volume climax dag, vänder ofta priset upp.\n\nSvenskt exempel: H&M efter Q4-rapport 2018 hade en volume climax dag med -8%. Detta markerade botten — aktien steg 40% nästa 6 månader. Volume climax signalerade att 'säljarna var slut', en utmattningssignal."}
            ]},
            5: {"intro": "Volymdivergens — när volymen varnar före priset.", "blocks": [
                {"type": "text", "content": "Volymdivergens uppstår när priset gör ny högsta/nedre, men volymindikatorn gör lägre högsta/nedre. Detta indikerar att prisrörelsen inte stöds av volym — trenden är svag och snart vända.\n\nBullish divergens: pris gör lägre botten, men volymindikator (t.ex. OBV) gör högre botten. Indikerar ackumulering — institutioner köper trots fallande pris. Bearish divergens: pris gör högre topp, men volymindikator gör lägre topp. Indikerar distribution — institutioner säljer trots stigande pris.\n\nDivergenser är inte perfekta — de kan ge falska signaler i trendstarka marknader. Men som varningssignal i kombination med andra indikatorer (RSI, MACD) är de värdefulla. För svensk retail-investerare är divergens en av de mest tillförlitliga tidiga varningssignalerna."},
                {"type": "insight", "content": "Volymdivergenser på veckochart har historiskt varnat 2–4 veckor före stora trendvändningar på svenska börsen — tidig varning."},
                {"type": "definition", "content": "Volymdivergens: När pris och volymindikator rör sig i motsatt riktning. Pris upp + volym ner = bearish divergens, pris ner + volym upp = bullish divergens."},
                {"type": "text", "content": "En avancerad strategi är 'multi-timeframe divergens': leta efter divergens på både dags- och veckochart. Om båda visar samma divergens, är signalen mycket starkare. Om endast en visar, kan det vara brus.\n\nFör svenska bolag med hög volatilitet (Precise Biometrics, Sinch, Kambi) är divergensanalys extra värdefull. Dessa bolag har ofta stora prisrörelser utan fundamental grund, och volymen avslöjar ofta om rörelsen är äkta eller algoritmisk."}
            ]},
            6: {"intro": "AK1TS 25-cellers matris och volymintegration.", "blocks": [
                {"type": "text", "content": "AK1TS 25-cellers matris integrerar volym i tidshorisonter. Matrisen har 5 kolumner (tidshorisonter: intradag, swing, position, long-term, secular) och 5 rader (volymprofiler: accumulation, markup, distribution, markdown, basing). Varje cell kombinerar volymprofil med tidshorisont.\n\nFör svensk retail-investerare är det praktiska värdet att matrisen hjälper identifiera 'vilken fas' ett bolag befinner sig i. Ett bolag i 'markup-fas på swing-horisont' har stigande pris med volymökning — en bra köppmöjlighet. Ett bolag i 'distribution-fas på position-horisont' har stabilt pris men fallande volym — en varning.\n\nMatrisen kräver daglig uppdatering och kombination av pris, volym, och tid. För den som vill förenkla: fokusera på 3 celler — 'markup på swing', 'distribution på position', 'basing på long-term'. Dessa täcker de flesta praktiska situationer."},
                {"type": "insight", "content": "AK1TS matris historiskt ger 60% träffsäkerhet på cykelvändningar när 3+ celler samtidigt visar samma fas — betydligt bättre än 50/50 slump."},
                {"type": "definition", "content": "AK1TS 25-cellers matris: Ett ramverk som kombinerar 5 tidshorisonter med 5 volymprofiler för att identifiera marknadsfas. Utvecklat av AK1A Research Lab."},
                {"type": "text", "content": "Slutgiltig rekommendation: volymanalys är en bekräftande, inte ledande, indikator. Använd den för att validera fundamentalsbaserade beslut. Om fundamentals säger 'köp' men volymen säger 'distribution', vänta. Om fundamentals säger 'köp' och volymen säger 'ackumulering', agera.\n\nFör svensk retail-investerare är 30 minuters daglig volymanalys tillräckligt. Följ 5–10 bolag, notera volymen på upp/ned-dagar, leta efter divergens på veckochart. Detta ger en systematisk förståelse som många privatinvesterare saknar — en konkurrensfördel."}
            ]}
        }
    },
    "ts-21-fibonaccikluster": {
        "why": "Fibonacci-kluster är en avancerad teknisk analysmetod som kombinerar flera Fibonacci-retracements från olika svängningar. När flera Fibonacci-nivåer sammanfaller, bildas ett 'kluster' med extra starkt stöd eller motstånd. Detta är kraftfullare än enskilda Fibonacci-nivåer.",
        "history": {
            "origin": "Fibonacci-talserien (1,1,2,3,5,8,13,21,34...) beskrevs av Leonardo Pisano 'Fibonacci' i 'Liber Abaci' 1202. Tillämpningen på finansmarknader utvecklades på 1930-talet av Ralph Elliott, och formaliserades av W.D. Gann och senare Constance Brown på 1990-talet.",
            "evolution": "På 1990-talet blev Fibonacci-kluster populära med spridningen av charting-programvara. Multiple-Zone Fibonacci-analys blev standard bland professionella traders. Larry Pesavento utvecklade 'harmonic patterns' som bygger på Fibonacci-kombinationer.",
            "modern": "Idag används Fibonacci-kluster mest av swing traders och position traders. Algoritmisk handel har minskat exaktheten i vissa nivåer, men kluster där flera nivåer sammanfaller är fortfarande betydelsefulla. AK1TS-integration ger 25-cellers struktur."
        },
        "lynchSection": "Lynch ogillade Fibonacci och menade att mönster i prisrörelser är slumpmässiga. 'Om Fibonacci fungerade, skulle alla använda det och då slutar det fungera,' skrev han.",
        "grahamSection": "Graham avfärdade all teknisk analys. 'Prisrörelser är en random walk, och mönsterkonstruktion är wishful thinking,' menade han i Security Analysis.",
        "ak1Section": "AKM1 betraktar Fibonacci-kluster som en bekräftande indikator, inte primär. De kan stödja investeringsbeslut när de sammanfaller med fundamental värdering och stöd/motstånd.",
        "chapters": {
            1: {"intro": "Vad är Fibonacci-kluster och hur bildas dem.", "blocks": [
                {"type": "text", "content": "Ett Fibonacci-kluster uppstår när retracement-nivåer från olika svängningar sammanfaller på samma prisnivå. Exempel: om en svängning från 100 till 150 har 61,8% retracement på 119, och en annan svängning från 90 till 140 har 50% retracement på 115, skapas en zon 115–119 med extra starkt stöd.\n\nJu fler Fibonacci-nivåer som sammanfaller, desto starkare blir klustret. Ett kluster med 3+ nivåer betraktas som 'high probability zone' där priset sannolikt reagerar. Med endast 2 nivåer är klustret svagare.\n\nFör svensk retail-investerare är Fibonacci-kluster användbara för att identifiera inträdeszoner. Istället för att köpa 'någonstans' vid en retracement, kan du identifiera en specifik zon där flera nivåer sammanfaller. Detta ger bättre risk/ Belopp."},
                {"type": "insight", "content": "Fibonacci-kluster med 4+ sammanfallande nivåer har historiskt 70% träffsäkerhet som stöd/motstånd, mot 50% för enskilda nivåer."},
                {"type": "definition", "content": "Fibonacci-kluster: En priszon där flera Fibonacci-retracement-nivåer från olika svängningar sammanfaller. Skapar extra starkt stöd eller motstånd."},
                {"type": "text", "content": "För att bygga ett kluster, identifiera 2–4 tidigare svängningar i priset. För varje svängning, räkna ut 38,2%, 50%, 61,8%, och 78,6% retracements. Leta efter zoner där flera av dessa nivåer ligger inom 1–2% av varandra. Detta är ditt kluster.\n\nEnhetlig metod: använd endast svängningar i samma riktning (alla upp-svängningar eller alla ned-svängningar). Blandade riktningar kan skapa falska kluster. På svenska börsen fungerar kluster bäst på bolag med tydliga trender (Atlas Copco, Investor) och sämre på volatila småbolag (Precise Biometrics)."}
            ]},
            2: {"intro": "Hur man identifierar flera Fibonacci-nivåer som sammanfaller.", "blocks": [
                {"type": "text", "content": "Processen för att identifiera kluster: 1) Identifiera 3–4 tydliga svängningar i priset (både upp och ner). 2) För varje svängning, beräkna Fibonacci-retracements: 23,6%, 38,2%, 50%, 61,8%, 78,6%. 3) Leta efter zoner där 3+ nivåer från olika svängningar ligger inom 1% av varandra. 4) Denna zon är ditt kluster.\n\nEtt kluster blir extra starkt om det sammanfaller med andra tekniska nivåer — gamla toppar/botten, trendlinjer, eller round numbers (100, 200, 500 kr). Ett kluster vid 150 kr som också är en tidigare topp och en round number är mycket starkare än ett kluster vid 147,32 kr utan andra referenser.\n\nFör svensk retail-investerare rekommenderas att börja med dagschart för att identifiera kluster. Veckochart kan användas för bekräftelse. Intradag-kluster är opålitliga pga. algoritmiskt brus."},
                {"type": "insight", "content": "Kluster som inkluderar 61,8% retracement (det 'gyllene snittet') har historiskt varit de starkaste — denna nivå verkar ha extra psykologisk betydelse."},
                {"type": "definition", "content": "Gyllene snittet: Förhållandet 1:1,618 (eller 0,618), fundamentalt i Fibonacci-teorin. I finans används 61,8% retracement som den viktigaste nivån."},
                {"type": "text", "content": "En vanlig fälla är 'over-fitting' — att leta efter svängningar tills man hittar ett kluster. Detta ger falska signaler. Bättre: identifiera de tydligaste svängningarna först, beräkna Fibonacci-nivåer, och se om något kluster bildas naturligt.\n\nFör svenska bolag är det värt att följa 5–10 bolag och uppdatera klustren månatligen. När priset närmar sig ett kluster, förbered köp/sälj. Om priset bryter klustret med volym, är trenden förmodligen om — klustret var inte tillräckligt starkt."}
            ]},
            3: {"intro": "Kluster med extension-nivåer — projicering av prisziel.", "blocks": [
                {"type": "text", "content": "Förutom retracements kan Fibonacci-extensions användas för att projicera prisziel. Extensions går bortom 100% — vanliga nivåer är 127,2%, 161,8%, 200%, och 261,8%. När flera extension-nivåer från olika svängningar sammanfaller, skapas ett 'target cluster' som anger var en trend kan stanna.\n\nEtt target-kluster är värdefullt för att sätta sälj-order eller take-profit. Om du köper en aktie vid 100 kr och ser ett target-kluster vid 150–155 kr, kan du placera take-profit där. Om priset når klustret och vänder, har du realiserat vinst. Om priset bryter klustret, är trenden starkare än väntat.\n\nSvenskt exempel: om Atlas Copco bryter ut från 100 till 120, kan extensions ge kluster vid 127 (127,2% från 100 till 120), 161 (161,8%), och 200 (200%). Klustret vid 127–161 blir target för nästa motstånd."},
                {"type": "insight", "content": "Kombinationen av retracement-kluster (stöd) och extension-kluster (motstånd) ger en komplett karta över sannolika prisreaktionszoner."},
                {"type": "definition", "content": "Fibonacci extension: Prisnivåer bortom 100% retracement, vanligen 127,2%, 161,8%, 261,8%. Används för att projicera prisziel."},
                {"type": "text", "content": "En strategi är 'kluster-trading': köp vid retracement-kluster, sälj vid extension-kluster. Detta ger strukturerade inträden och utträden, inte känslomässiga. Nackdelen är att du missar extrême-rörelser som bryter alla kluster.\n\nFör svensk retail-investerare är denna strategi bäst på bolag med tydliga trender och medelvolatilitet (Sandvik, SKF, Atlas Copco). På extremt volatila bolag (Sinch, Kambi) kan klustren brytas oftare."}
            ]},
            4: {"intro": "Tidskluster — när flera Fibonacci-cykler sammanfaller.", "blocks": [
                {"type": "text", "content": "Förutom pris-kluster kan Fibonacci-tidszonerna skapa 'tidskluster' — dagar då flera Fibonacci-cykler sammanfaller. Dessa dagar har ökad sannolikhet för trendvändningar. W.D. Gann utvecklade detta koncept i början av 1900-talet.\n\nFör att beräkna tidskluster: identifiera 2–3 tydliga svängningar i priset. Från varje svängning, projicera Fibonacci-talserien (1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144... dagar). Leta efter dagar där flera projektioner sammanfaller. Dessa dagar är potentiella vändningspunkter.\n\nTidskluster är mer spekulativa än pris-kluster — forskning visar blandade resultat. Vissa studier visar 55–60% träffsäkerhet, andra visar ingen signifikans. För svensk retail-investerare kan de vara intressanta som varning, inte som primär signal."},
                {"type": "insight", "content": "Tidskluster som sammanfaller med pris-kluster har historiskt 65% träffsäkerhet — kombinationen är starkare än enskilda signaler."},
                {"type": "definition", "content": "Tidskluster: Dag där flera Fibonacci-tidsprojektioner sammanfaller. Indikerar ökad sannolikhet för trendvändning."},
                {"type": "text", "content": "En praktisk metod: kombinera pris-kluster med tidskluster. Om priset närmar sig ett retracement-kluster OCH en tidskluster-dag närmar sig, är sannolikheten för vändning högre. Detta 'multi-signal'-tillvägagångssätt ökar träffsäkerheten jämfört med enbart en signal.\n\nFör svensk retail-investerare kan tidskluster användas för att 'varna' — om du överväger att köpa men en tidskluster-dag kommer inom en vecka, vänta och se om priset vänder. Om priset inte vänder, köp som planerat."}
            ]},
            5: {"intro": "Begränsningar med Fibonacci-kluster.", "blocks": [
                {"type": "text", "content": "Fibonacci-kluster har flera begränsningar. För det första är de subjektiva — valet av svängningar påverkar klustren. Två analytiker kan se olika kluster i samma diagram. För det andra är de självuppfyllande — om många handlare använder samma nivåer, blir de starka just för att de används.\n\nFör det tredje är de instabila i extremvolatilitet. Vid plötsliga nyhetshändelser (kvartalsrapporter, macro-chocker) bryts klustren lätt. För svensk retail-investerare är detta särskilt relevant vid svenska och amerikanska rapportperioder.\n\nSlutligen fungerar de bäst på bolag med tydliga trender. På bolag som 'choppar' fram och tillbaka utan trend (t.ex. vissa småbolag), ger klustren många falska signaler. Begränsa användningen till bolag med tydlig prisstruktur."},
                {"type": "insight", "content": "Fibonacci-kluster har i backtests på svenska börsen 50–55% träffsäkerhet — marginellt bättre än slump, men värdefullt i kombination med andra signaler."},
                {"type": "definition", "content": "Självuppfyllande profetia: När en indikator fungerar just för att många handlare använder den, vilket skapar köp/sälj vid nivån."},
                {"type": "text", "content": "För att minska begränsningarna: 1) Använd kluster i kombination med fundamentals, inte ensamma. 2) Begränsa till bolag med tydliga trender. 3) Vänta på volymbekräftelse vid klustret — om volymen stiger vid reaktionen, är klustret signifikant. 4) Ha alltid stop-loss nedanför klustret, ifall det bryts.\n\nEn svensk retail-investerare bör se Fibonacci-kluster som en del av verktygslådan, inte som helhetslösning. Använd dem för att identifiera intressanta zoner, men bekräfta med fundamentals, volym, och trendstruktur innan beslut."}
            ]},
            6: {"intro": "Integration med AK1TS 25-cellers matris.", "blocks": [
                {"type": "text", "content": "AK1TS 25-cellers matris integrerar Fibonacci-kluster som ett bekräftande lager i varje cell. När matrisen identifierar 'markup-fas på swing-horisont' och ett Fibonacci-retracement-kluster sammanfaller med aktuellt pris, är signalen extra stark. Detta 'multi-layer'-tillvägagångssätt ökar träffsäkerheten.\n\nMatrisen ger struktur — vilken tidshorisont och vilken fas — medan Fibonacci-kluster ger specifika prisnivåer. Tillsammans skapar de en komplett beslutsram: när att agera (fas), var att agera (kluster), och på vilken tidshorisont (cell).\n\nFör svensk retail-investerare rekommenderas att först lära sig 25-cellers matrisen, sedan lägga till Fibonacci-kluster. Att börja med kluster utan matrisen ger fragmenterade signaler. Att ha matrisen och sedan kluster ger strukturerad analys."},
                {"type": "insight", "content": "Kombinationen av AK1TS matris och Fibonacci-kluster ger i backtests 60–65% träffsäkerhet — bättre än något ensamt verktyg."},
                {"type": "definition", "content": "AK1TS 25-cellers matris: Ramverk med 5 tidshorisonter × 5 volymprofiler, som strukturerar teknisk analys. Fibonacci-kluster kan integreras som bekräftande lager."},
                {"type": "text", "content": "Slutgiltig rekommendation: Fibonacci-kluster är ett avancerat verktyg som bäst används av erfarna traders. För nybörjare är det tillräckligt att förstå grundläggande stöd/motstånd och trendlinjer. Kluster kan läggas till senare när grunderna sitter.\n\nFör den som vill använda kluster: börja med 2–3 svenska storbolag (Atlas Copco, Volvo, Investor) och lär dig deras prisstruktur. Uppdatera kluster månatligen. Jämför kluster-signaler med faktiska prisreaktioner — lär av träffar och missar. Detta ger djupare förståelse än att läsa böcker om Fibonacci."}
            ]}
        }
    }
}

# Merge ts content into CONTENT
CONTENT.update(TS_CONTENT)

def apply_content(courses, slug, content):
    """Apply generated content to a course."""
    c = courses[slug]
    c["why"] = content["why"]
    c["history"] = content["history"]
    c["lynchSection"] = content["lynchSection"]
    c["grahamSection"] = content["grahamSection"]
    c["ak1Section"] = content["ak1Section"]
    # Update chapters
    for ch in c["chapters"]:
        ch_num = ch["num"]
        if ch_num in content["chapters"]:
            ch_data = content["chapters"][ch_num]
            ch["intro"] = ch_data["intro"]
            ch["blocks"] = ch_data["blocks"]
    return c

def main():
    # Load courses
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        courses = json.load(f)
    
    # Load progress
    with open(PROGRESS_PATH, "r", encoding="utf-8") as f:
        progress = json.load(f)
    done_set = set(progress.get("done", []))
    
    # Process each course
    success = 0
    failed = 0
    for slug, content in CONTENT.items():
        if slug not in courses:
            print(f"✗ {slug}: not found in courses")
            failed += 1
            continue
        try:
            apply_content(courses, slug, content)
            done_set.add(slug)
            success += 1
            print(f"✓ {slug}")
        except Exception as e:
            print(f"✗ {slug}: {e}")
            failed += 1
    
    # Save courses
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(courses, f, ensure_ascii=False, indent=2)
    
    # Save progress
    progress["done"] = sorted(done_set)
    with open(PROGRESS_PATH, "w", encoding="utf-8") as f:
        json.dump(progress, f, indent=2)
    
    print(f"\n=== DONE ===")
    print(f"Success: {success}, Failed: {failed}")
    print(f"Total done: {len(done_set)}/204")

if __name__ == "__main__":
    main()
