/**
 * Seed 400+ fallstudier + 200+ indikator-kombinationer.
 * Kör: bun run src/lib/ak1a/seed-cases-combinations.ts
 */
import { db } from "@/lib/db";

// ── 210+ lyckade fallstudier ──
const SUCCESS_CASES: Array<[string, string, string, string, number, string, string, number, string, string, boolean?]> = [
  // [company, ticker, title, description, akm1Score, decisiveVars, sector, year, outcome, lesson, isIllustrative?]
  ["Apple", "AAPL", "Moat-stack — varumärke + ekosystem + services", "Apple kombinerar tre moats: varumärke (premium-pris), ekosystem (iPhone→Mac→iPad→Watch lås-in) och services (App Store 30% take rate). AKM1: hög på nästan alla variabler, särskilt V14 (varumärke), V15 (nätverk), V20 (buybacks).", 88, "V14,V15,V20", "Teknologi", 2012, "+1500% på 10 år", "Tre moats tillsammans är starkare än summan av delarna."],
  ["Microsoft", "MSFT", "Cloud-transformation under Nadella", "Microsoft 2014: stagnerande, värt 300 Mdr USD. Satya Nadella blev VD → satsade på Azure, Office 365, GitHub. 2024: värt 3,1 biljoner USD. Cloud-intäkter 100+ Mdr USD/år. AKM1: V13 (ledning) avgörande.", 85, "V13,V16,V20", "Teknologi", 2014, "+900% på 10 år", "Rätt VD kan vända ett stagnerande bolag — ledning (V13) betyder allt."],
  ["Amazon", "AMZN", "Långsiktig tänkande — Bezos 'det är dag 1'", "Amazon 1997-2024: Bezos brände pengar i 7 år, växte 30%/år. AWS lanserades 2006 = moln-industrin skapades. Long-term thinking + reinvestment. AKM1: V01 (tillväxt) 5, V19 (burn) 1, men 'bra bränning'.", 82, "V01,V15,V19", "Konsument", 1997, "+200000% på 25 år", "Långsiktigt tänkande slår kortsiktig vinst — om tillväxten är äkta."],
  ["Tesla", "TSLA", "Katalysator-stackning — flera händelser bygger på varandra", "Tesla hade flera katalysatorer: Model S (2012), Model 3 (2017), Shanghai-fabrik (2019), S&P 500-inklusion (2020). Varje katalysator byggde på den föregående. AKM1: V16 (katalysatorer) extremt hög.", 78, "V16,V01,V15", "Konsument", 2012, "+2000% på 8 år", "Flera katalysatorer i sekvens skapar exponentiellt värde."],
  ["Nvidia", "NVDA", "AI-disruption — från GPU till AI-infrastruktur", "Nvidia gick från grafikkort till AI-beräkningsinfrastruktur. CUDA-plattformen (2006) skapade nätverkseffekt. AI-boomen 2023-2024 gjorde dem till världens mest värdefulla bolag. AKM1: V15 (nätverk) + V16 (katalysator) + V01 (tillväxt).", 86, "V15,V16,V01", "Teknologi", 2016, "+3000% på 7 år", "Nätverkseffekt + katalysator + tillväxt = exponentiell värdeskapande."],
  ["Berkshire Hathaway", "BRK.A", "Compounder-ideal — Buffett & Munger", "Warren Buffett byggde Berkshire från en textilfabrik till ett 800 Mdr USD-holdingbolag. Kapitalallokering + moat-innehav + tid. AKM1: alla variabler stabila över 50+ år. V20 (buybacks) vid rätt pris.", 90, "V13,V20,V12", "Finans", 1965, "+2000000% på 60 år", "Tid + kapitalallokering + moat = compounder-ideal."],
  ["Visa", "V", "Nätverkseffekt — duopoly med Mastercard", "Visa och Mastercard bildar ett duopoly i globala betalningsnätverket. Fler användare → fler handlare → fler användare. AKM1: V15 (nätverk) maximal, V07 (bruttomarginal) ~80%, V12 (stabilitet) hög.", 87, "V15,V07,V12", "Finans", 2008, "+600% på 15 år", "Nätverkseffekt + hög bruttomarginal = trygg compounder."],
  ["Costco", "COST", "Medlemskap-moat — låg pris + volym", "Costco säljer nästan till självkostnad och tjänar på medlemskap. Medlemmar förnyar år efter år = stabil ARR. AKM1: V12 (stabilitet) + V14 (varumärke) + V01 (tillväxt, långsam men stabil).", 84, "V12,V14,V01", "Konsument", 2005, "+800% på 18 år", "Medlemskap-modell skapar stabil återkommande intäkt."],
  ["Atlas Copco", "ATCO-A.ST", "Industri-moat — premium-pris i 40+ år", "Atlas Copco = svensk industri-moat. Verktyg, kompressorer, vacuum. Premium-pris (40% över snitt) genom kvalitet + service-nätverk. ROE >20% i 30+ år. Utdelning höjd 40+ år i rad. AKM1 klassisk compounder.", 86, "V13,V09,V20", "Industri", 2000, "+1000% på 20 år", "Premium-pris + service-nätverk = varaktig industri-moat."],
  ["Investor AB", "INVE-B.ST", "Holding-bolag — Wallenberg 100-årig compounder", "Investor AB = Wallenberg-familjens investmentbolag. Huvudinnehav: AstraZeneca, Ericsson, Atlas Copco, SEB, Saab. Handlas 25-30% under NAV. Långsiktig strategi, aktivt ägande. AKM1: moat = nätverk + tid.", 85, "V12,V14,V20", "Finans", 1995, "+2000% på 25 år", "Holding-rabatt + långsiktigt ägande = compounder."],
  ["AstraZeneca", "AZN", "Onkologi-pipeline — patentklipp brutet", "AstraZeneca 2014: patentklipp-kris, EPS fallande. Pascal Soriot blev VD → satsade på onkologi (Enhertu, Tagrisso). 2024: pipeline stark, patentklipp cykel brutit. AKM1: V13 (ledning) + V16 (katalysatorer = läkemedelsgodkännanden).", 82, "V13,V16,V13", "Hälsovård", 2014, "+400% på 10 år", "Rätt VD + stark pipeline kan bryta patentklipp-cykel."],
  ["Novo Nordisk", "NOVO-B.CO", "GLP-1 revolutionen — Ozempic + Wegovy", "Novo Nordisk dominerar diabetes-marknaden. 2017: Ozempic (semaglutide). 2021: Wegovy (viktnedgång). GLP-1 revolutionerar vikt-marknaden = 100+ Mdr USD potentiell marknad. AKM1: extrem moat via patent + nätverk.", 88, "V13,V14,V16", "Hälsovård", 2017, "+500% på 7 år", "Patent-moat + massmarknad-katalysator = extrem värdeskapande."],
  ["Volvo AB", "VOLV-B", "Elförskjutning i tunga fordon", "Volvo Trucks & Construction Equipment i ledande position för elförskjutning. Batteri-teknik + service-nätverk. AKM1: V13 (ledning) + V16 (katalysatorer = nya produkter).", 82, "V13,V16,V14", "Industri", 2016, "+300% på 8 år", "Tidig positionering i teknikskifte skapar varaktig fördel."],
  ["Spotify", "SPOT", "Streaming-pionjär — nätverk + data", "Spotify skapade musikstreaming-marknaden. Fördel: first-mover + data om lyssnande + personliga spellistor. AKM1: V15 (nätverk) + V03 (diversifiering, annons + prenumeration).", 72, "V15,V03,V01", "Teknologi", 2018, "+150% på 5 år", "First-mover + data-moat kan övervinna låga marginaler."],
  ["ASML", "ASML", "Monopol i EUV-litografi", "ASML är enda bolaget som tillverkar EUV-litografimaskiner (för avancerade chip). Monopol. Intel, TSMC, Samsung måste köpa från ASML. AKM1: V13 (patent) maximal + V15 (nätverk).", 89, "V13,V15,V14", "Teknologi", 2015, "+1500% på 8 år", "Monopol via patentskyddad teknik = ultimat moat."],
  ["McDonald's", "MCD", "Franchise-moat — fastigheter + varumärke", "McDonald's äger fastigheterna under restaurangerna. Franchisees betalar hyra + royalty. AKM1: V14 (varumärke) + V12 (stabilitet, franchise-avtal) + V07 (bruttomarginal, franchise-modell).", 83, "V14,V12,V07", "Konsument", 2005, "+500% på 18 år", "Fastighets-ägande + franchise = stabil högavkastning."],
  ["Coca-Cola", "KO", "Varumärke-moat — 130+ år", "Coca-Cola = ett av världens starkaste varumärken. Distribution i 200+ länder. AKM1: V14 (varumärke) maximal + V12 (stabilitet) + V03 (diversifiering, 500+ varumärken).", 82, "V14,V12,V03", "Konsument", 1990, "+1000% på 30 år", "Ett starkt varumärke varar i generationer."],
  ["Nike", "NKE", "Varumärke + sponsring-moat", "Nike sponsrar topp-atleter (Michael Jordan, LeBron, Ronaldo). Varumärke-styrka driver premium-pris. AKM1: V14 (varumärke) + V16 (katalysatorer = nya sponsringar).", 78, "V14,V16,V01", "Konsument", 2010, "+400% på 12 år", "Varumärke + kända sponsringar = premium-pris-makt."],
  ["Salesforce", "CRM", "SaaS-pionjär — ARR + nätverk", "Salesforce skapade SaaS-marknaden. ARR-modell = stabil återkommande intäkt. Moln-plattform (MuleSoft, Tableau, Slack) skapar ekosystem. AKM1: V02 (ARR) + V15 (nätverk).", 79, "V02,V15,V01", "Teknologi", 2010, "+800% på 12 år", "ARR + ekosystem = stabil compounder-tillväxt."],
  ["Adobe", "ADBE", "SaaS-transformation — Creative Cloud", "Adobe gick från box-produkter till Creative Cloud (prenumeration). ARR ökade dramatiskt. AKM1: V02 (ARR) + V14 (varumärke) + V15 (nätverk, fil-format standard).", 84, "V02,V14,V15", "Teknologi", 2012, "+1500% på 12 år", "SaaS-transformation av etablerat varumärke = kraftfull."],
  ["Johnson & Johnson", "JNJ", "Diversifierad pharma-moat", "J&J = diversifierad hälsovård (pharma + medical devices + consumer). Patent-portfölj + varumärken (Tylenol, Band-Aid). AKM1: V03 (diversifiering) + V13 (patent) + V12 (stabilitet).", 80, "V03,V13,V12", "Hälsovård", 2000, "+300% på 22 år", "Diversifiering över 3 segment = stabil compounder."],
  ["Procter & Gamble", "PG", "Konsument-varumärken-moat", "P&G äger 65+ varumärken (Tide, Pampers, Gillette). Stark distribution + varumärken. AKM1: V14 (varumärke) + V12 (stabilitet) + V03 (diversifiering).", 79, "V14,V12,V03", "Konsument", 2000, "+250% på 22 år", "Portfölj av starka varumärken = stabil inflationsskydd."],
  ["Walmart", "WMT", "Skala-moat — lågpris-ledare", "Walmart = världens största återförsäljare. Skala ger lägre inköpspriser = lägre försäljningspriser. AKM1: V15 (nätverk, skala) + V12 (stabilitet) + V03 (diversifiering).", 78, "V15,V12,V03", "Konsument", 2000, "+400% på 22 år", "Skala + lågpris-position = varaktig moat."],
  ["Disney", "DIS", "IP-moat — franchises + parks + streaming", "Disney äger franchises (Marvel, Star Wars, Pixar, Mickey) + tema-parker + streaming. AKM1: V14 (varumärke/IP) maximal + V15 (nätverk, franchises) + V03 (diversifiering).", 77, "V14,V15,V03", "Konsument", 2010, "+200% på 12 år", "IP-portfölj över plattformar = mångfacetterad moat."],
  ["Mastercard", "MA", "Duopoly-nätverk med Visa", "Mastercard bildar duopoly med Visa i globala betalningar. Nätverkseffekt + hög bruttomarginal (~80%). AKM1: V15 (nätverk) + V07 (bruttomarginal) + V12 (stabilitet).", 86, "V15,V07,V12", "Finans", 2008, "+1200% på 15 år", "Duopoly-nätverk + hög marginal = trygg compounder."],
  ["Oracle", "ORCL", "Enterprise-databas-moat", "Oracle dominerar enterprise-databaser. Switching costs enorma (migration av kritiska system). AKM1: V15 (nätverk, lås-in) + V12 (stabilitet, kontrakt) + V02 (ARR, support-avtal).", 76, "V15,V12,V02", "Teknologi", 2005, "+500% på 18 år", "Switching costs = en av de starkaste moats."],
  ["Cisco", "CSCO", "Nätverks-infrastruktur-monopol (tidigt)", "Cisco dominerade nätverksutrustning under internet-boomen. Switching costs + patenterad IOS. AKM1: V15 (nätverk) + V13 (patent).", 75, "V15,V13,V12", "Teknologi", 1995, "+1000% på 10 år (sedan platt)", "Infrastruktur-moat är stark men hotas av molnet."],
  ["TSMC", "TSM", "Halvledare-foundry-monopol", "TSMC tillverkar chip för Apple, Nvidia, AMD, Qualcomm. Monopol i avancerad foundry. AKM1: V13 (patent/process) + V15 (nätverk, ekosystem).", 85, "V13,V15,V14", "Teknologi", 2012, "+800% på 12 år", "Process-monopol i halvledare = strategisk moat."],
  ["Samsung", "005930.KS", "Vertikal integration — minne + skärmar + telefoner", "Samsung tillverkar minne, skärmar, processorer OCH telefoner. Vertikal integration ger kostnadsfördel. AKM1: V03 (diversifiering) + V13 (patent).", 76, "V03,V13,V15", "Teknologi", 2010, "+300% på 12 år", "Vertikal integration i halvledare = kostnadsfördel."],
  ["Toyota", "7203.T", "Hybrid-pionjär — Prius + lean production", "Toyota ledde hybrid-bilen (Prius 1997) + lean production. Starkt varumärke för kvalitet. AKM1: V14 (varumärke) + V13 (process-patent) + V07 (bruttomarginal).", 77, "V14,V13,V07", "Konsument", 2005, "+200% på 18 år", "Process-innovation + varumärke = varaktig fördel."],
  ["Sony", "6758.T", "IP-moat — PlayStation + musik + film", "Sony äger PlayStation, Sony Music, Sony Pictures. IP-portfölj över plattformar. AKM1: V14 (varumärke/IP) + V03 (diversifiering) + V15 (nätverk, PS-ekosystem).", 74, "V14,V03,V15", "Konsument", 2012, "+500% på 12 år", "IP-portfölj + plattform-ekosystem = mångfacetterad moat."],
  ["Nintendo", "7974.T", "Franchise-moat — Mario + Zelda + Pokémon", "Nintendo äger de mest ikoniska franchise i spel. Mario, Zelda, Pokémon, Animal Crossing. AKM1: V14 (varumärke) maximal + V15 (nätverk, IP).", 76, "V14,V15,V12", "Konsument", 2017, "+200% på 6 år", "Ägda IP-franchises = evig moat."],
  ["Netflix", "NFLX", "Streaming-pionjär — data + originalinnehåll", "Netflix skapade streaming-marknaden. Data om tittarbeteende + originalinnehåll (House of Cards, Stranger Things). AKM1: V15 (nätverk, data) + V01 (tillväxt).", 72, "V15,V01,V14", "Konsument", 2012, "+800% på 10 år (sedan volatil)", "First-mover + data = fördel, men konkurrens ökar."],
  ["Meta", "META", "Social graph-moat — 3 miljarder användare", "Meta (Facebook, Instagram, WhatsApp) har 3+ miljarder användare. Social graph = omöjlig att replikera. AKM1: V15 (nätverk) maximal + V01 (tillväxt, annons-intäkter).", 81, "V15,V01,V14", "Teknologi", 2012, "+600% på 12 år (med 2022-krasch)", "Social graph-nätverkseffekt = en av de starkaste moats."],
  ["Google/Alphabet", "GOOGL", "Sök-monopol + annons-nätverk", "Google dominerar sök (90% marknadsandel). Annons-intäkter drivs av sök-data. AKM1: V15 (nätverk, data) maximal + V14 (varumärke).", 85, "V15,V14,V07", "Teknologi", 2005, "+1500% på 18 år", "Data-nätverk + varumärke = sök-monopol."],
  ["AMD", "AMD", "Comeback under Lisa Su", "AMD 2014: nära konkurs, marknadsandel 20% mot Intel. Lisa Su blev VD → Ryzen (2017), EPYC (server). 2024: marknadsandel 35%. AKM1: V13 (ledning) avgörande + V16 (katalysatorer = produkter).", 80, "V13,V16,V01", "Teknologi", 2015, "+3000% på 8 år", "Rätt VD + stark produkt-pipeline = dramatisk comeback."],
  ["Intel", "INTC", "x86-monopol (tidigt — fram till 2018)", "Intel dominerade x86-processorer i 30+ år. Patenterad arkitektur + fabriker. AKM1: V13 (patent) + V15 (nätverk, x86-ekosystem).", 70, "V13,V15,V12", "Teknologi", 1995, "+1000% på 20 år (sedan fall)", "Monopol + patent = moat, men förnyelse krävs."],
  ["Cisco (senare)", "CSCO", "Switching costs i enterprise", "Cisco's enterprise-nätverk har enorma switching costs. AKM1: V15 (nätverk) + V12 (stabilitet).", 72, "V15,V12,V14", "Teknologi", 2010, "+50% på 12 år (stabil utdelning)", "Switching costs ger stabil men långsam tillväxt."],
  ["SKF", "SKF-B.ST", "Kullager-moat — 100+ år", "SKF = svensk kullager-jätte. Grundades 1907. Teknisk moat + global distribution. AKM1: V14 (varumärke) + V13 (patent) + V12 (stabilitet).", 76, "V14,V13,V12", "Industri", 2000, "+400% på 22 år", "Teknisk moat + tid = varaktig industri-investering."],
  ["Sandvik", "SAND.ST", "Verktyg + materialteknik-moat", "Sandvik = svensk verktygs- och materialteknik-jätte. Premium-pris via kvalitet. AKM1: V14 (varumärke) + V13 (patent).", 77, "V14,V13,V09", "Industri", 2005, "+500% på 18 år", "Premium-verktyg + patent = industri-moat."],
  ["Electrolux", "ELUX-B.ST", "Vitvaru-varumärke (tidigt)", "Electrolux = globalt vitvaru-varumärke. AKM1: V14 (varumärke) + V03 (diversifiering).", 68, "V14,V03,V12", "Konsument", 2000, "+100% på 22 år (volatil)", "Varumärke-moat urholkas av konkurrens över tid."],
  ["Boliden", "BOL.ST", "Koppar/zink-gruvor + integrerad raffinering", "Boliden = svensk gruv-jätte. Integrerad gruva + raffinering. AKM1: V03 (diversifiering, metaller) + V16 (katalysatorer = metallpriser).", 72, "V03,V16,V12", "Material", 2010, "+500% på 14 år", "Cyklisk moat — köp när metallpriser är låga."],
  ["SKB", "PRIVATE", "Svensk bank-moat — stor marknadsandel", "Svenska Handelsbanken = stabil svensk bank med låg risk. AKM1: V12 (stabilitet) + V10 (låg skuldsättning för bank) + V09 (ROE).", 75, "V12,V10,V09", "Finans", 2005, "+400% på 18 år", "Konservativ bank-moat = stabil över cykler."],
  ["Swedbank", "SWED-A.ST", "Bank-moat med utdelning", "Swedbank = en av Norden mest lönsamma banker. ROE 15%, direktavkastning 6%, P/E 9x. Cyklisk exponering mot bostad + Baltikum. AKM1: V09 + V12.", 75, "V09,V12,V10", "Finans", 2016, "+200% på 8 år", "Hög ROE + utdelning = bank-compounder (med cykelrisk)."],
  ["SEB", "SEB-A.ST", "Corporate bank-moat", "SEB = stark position i svensk corporate banking. AKM1: V14 (varumärke) + V12 (stabilitet).", 73, "V14,V12,V09", "Finans", 2010, "+300% på 14 år", "Corporate bank-moat = stabil över cykler."],
  ["ICA Gruppen", "ICA.ST", "Svensk dagligvaru-moat", "ICA = svensk dagligvaru-ledare. Franchise-modell + skala. AKM1: V14 (varumärke) + V15 (nätverk, skala).", 74, "V14,V15,V12", "Konsument", 2013, "+250% på 11 år", "Dagligvaru-moat = inflationsskyddad."],
  ["Hennes & Mauritz (tidigt)", "HM-B.ST", "Fast fashion-pionjär (1998-2015)", "H&M växte från svensk butik till global fast fashion-kedja. AKM1: V14 (varumärke) + V01 (tillväxt).", 72, "V14,V01,V03", "Konsument", 1998, "+800% på 17 år (sedan fall)", "Fast fashion-moat hotas av online-konkurrens."],
  ["Cloetta", "CLB-B.ST", "Svensk konfektyr-varumärke", "Cloetta = svensk konfektyr-jätte (Kexchoklad, Läkerol). Varumärke-moat. AKM1: V14 (varumärke) + V12 (stabilitet).", 68, "V14,V12,V03", "Konsument", 2010, "+200% på 14 år", "Svenska klassiker-varumärken = stabila."],
  ["Knowit", "KNOW.ST", "IT-konsult-moat", "Knowit = svensk IT-konsult. Offentlig sektor + industri. AKM1: V12 (stabilitet, kontrakt) + V03 (diversifiering).", 65, "V12,V03,V09", "Teknologi", 2015, "+150% på 9 år", "IT-konsult-stabilitet via långa kontrakt."],
  ["Bure Equity", "BURE.ST", "Svenskt investmentbolag", "Bure Equity = svenskt investmentbolag. Rabatt mot NAV. AKM1: V12 (stabilitet) + V14 (varumärke).", 70, "V12,V14,V20", "Finans", 2012, "+300% på 12 år", "Investmentbolag-rabatt + tid = compounder."],
  ["Cardo", "CARDI.ST", "Industri-dörrar-moat (före uppköp)", "Cardo = industri-dörrar och pumpar. Teknisk moat. Uppköpt av Assa Abloy 2011. AKM1: V13 (patent) + V14 (varumärke).", 72, "V13,V14,V09", "Industri", 2005, "+400% på 6 år (uppköp)", "Nisch-moat + uppköpskandidat = bra utfall."],
  ["Assa Abloy", "ASS-B.ST", "Lås-moat — global ledare", "Assa Abloy = global ledare i lås och dörr-lösningar. AKM1: V14 (varumärke) + V13 (patent) + V03 (diversifiering).", 78, "V14,V13,V03", "Industri", 2010, "+800% på 14 år", "Nisch-moat + global expansion = compounder."],
  ["MTG (före Viaplay)", "MTG-B.ST", "Medie-moat (före split)", "MTG = svensk medie-jätte (TV4, Viasat). Före split 2018. AKM1: V14 (varumärke) + V15 (nätverk).", 70, "V14,V15,V12", "Konsument", 2010, "+200% på 8 år (före fall)", "Medie-moat hotas av streaming-disruption."],
  ["Lundin Petroleum/Orrön", "LUND.ST", "Olje-upptäckt-moat", "Lundin Petroleum = svensk olje-bolag. Upptäckte Edvard Grieg-fältet. AKM1: V16 (katalysator = upptäckt) + V03 (diversifiering).", 72, "V16,V03,V12", "Energi", 2015, "+500% på 6 år", "Resurs-upptäckt = kraftfull katalysator."],
  ["Sinch", "SINCH.ST", "CPaaS-moat (tidigt — 2017-2020)", "Sinch = svensk cloud-communications. Tidigt ledande i CPaaS. AKM1: V15 (nätverk) + V01 (tillväxt).", 68, "V15,V01,V16", "Teknologi", 2017, "+2000% på 3 år (sedan krasch)", "Nätverk + tillväxt = kraftfull, men risk för övervärdering."],
  ["Electrolux Professional", "EPRO-B.ST", "Professional-vitvaru-nisch", "Electrolux Professional = professional-vitvaror (restaurang, tvätt). Nisch-moat. AKM1: V14 (varumärke) + V12 (stabilitet).", 75, "V14,V12,V09", "Konsument", 2018, "+200% på 6 år", "Nisch-moat i professional-segment = stabil."],
  ["Öresund", "ÖRES.ST", "Investmentbolag-rabatt", "Öresund = svenskt investmentbolag. Handlas med rabatt mot NAV. AKM1: V12 (stabilitet) + V14 (varumärke).", 68, "V12,V14,V20", "Finans", 2015, "+150% på 9 år", "Investmentbolag-rabatt + tålamod = avkastning."],
  ["Beijer Alma", "BEIA-B.ST", "Industri-holding-moat", "Beijer Alma = industri-holding (Lesjöfors, Hedströms). AKM1: V12 (stabilitet) + V03 (diversifiering).", 72, "V12,V03,V09", "Industri", 2010, "+400% på 14 år", "Industri-holding + diversifiering = stabil."],
  ["Karo Pharma", "KARO.ST", "Pharma-uppköpskandidat", "Karo Pharma = svenskt pharma-bolag. Uppköpt av Karo Intressenter 2022. AKM1: V13 (patent) + V16 (katalysator = uppköp).", 70, "V13,V16,V09", "Hälsovård", 2018, "+150% på 4 år (uppköp)", "Nisch-pharma + uppköpskandidat = bra utfall."],
  ["NIBE", "NIBE-B.ST", "Värmepump-moat (2015-2021)", "NIBE = svensk värmepump-ledare. Tidig positionering i grönn omställning. AKM1: V16 (katalysator = grönn omställning) + V01 (tillväxt).", 75, "V16,V01,V14", "Industri", 2015, "+1500% på 6 år (sedan fall)", "Grönn katalysator + tillväxt = kraftfull, men risk för övervärdering."],
  ["Pfizer", "PFE", "Covid-vaccin-katalysator", "Pfizer utvecklade Covid-vaccinet (Comirnaty med BioNTech). AKM1: V16 (katalysator = pandemi) + V13 (patent).", 75, "V16,V13,V12", "Hälsovård", 2020, "+100% på 2 år (sedan fall)", "Pandemi-katalysator = engångs-intäkt, inte varaktig."],
  ["Moderna", "MRNA", "mRNA-pionjär (2020-2021)", "Moderna skapade mRNA-vaccin. AKM1: V13 (patent) + V16 (katalysator = pandemi).", 68, "V13,V16,V01", "Hälsovård", 2020, "+400% på 2 år (sedan -80%)", "Pandemi-katalysator = volatil, inte varaktig moat."],
  ["Eli Lilly", "LLY", "GLP-1 + Alzheimer-pipeline", "Eli Lilly = GLP-1 (Mounjaro/Zepbound) + Alzheimer (donanemab). AKM1: V16 (katalysatorer) + V13 (patent).", 83, "V16,V13,V14", "Hälsovård", 2018, "+500% på 6 år", "Stark pipeline + patent = pharma-compounder."],
  ["JPMorgan Chase", "JPM", "Bank-moat genom skala + diversifiering", "JPMorgan = största USA-banken. Skala + diversifiering. AKM1: V15 (nätverk, skala) + V03 (diversifiering).", 78, "V15,V03,V12", "Finans", 2010, "+400% på 14 år", "Storbank-moat = stabil över cykler."],
  ["Goldman Sachs", "GS", "Investment bank-moat", "Goldman Sachs = ledande investment bank. Varumärke + nätverk. AKM1: V14 (varumärke) + V15 (nätverk).", 75, "V14,V15,V09", "Finans", 2012, "+300% på 12 år", "Investment bank-varumärke = moat."],
  ["BlackRock", "BLK", "Asset management-moat — iShares ETF", "BlackRock = största asset manager (10 biljoner USD AUM). iShares ETF-plattform. AKM1: V15 (nätverk, AUM) + V02 (ARR, förvaltningsavgift).", 82, "V15,V02,V12", "Finans", 2010, "+500% på 14 år", "AUM-nätverk + ARR = asset management-compounder."],
  ["Exxon Mobil", "XOM", "Olje-major-moat", "Exxon = olje-major med integrerad verksamhet. AKM1: V03 (diversifiering) + V12 (stabilitet) + V16 (katalysator = oljepris).", 72, "V03,V12,V16", "Energi", 2010, "+200% på 14 år (med 2020-dipp)", "Olje-major = cyklisk men stabil."],
  ["Chevron", "CVX", "Olje-major med utdelning", "Chevron = olje-major med stark utdelning. AKM1: V12 (stabilitet) + V16 (katalysator = oljepris).", 73, "V12,V16,V09", "Energi", 2010, "+250% på 14 år", "Olje-major + utdelning = cyklisk compounder."],
  ["NextEra Energy", "NEE", "Förnybar energi-utility-moat", "NextEra = största förnybar energi-utility i USA. AKM1: V16 (katalysator = grönn omställning) + V12 (stabilitet, utility).", 78, "V16,V12,V02", "Utility", 2010, "+500% på 14 år", "Förnybar + utility = stabil compounder."],
  ["American Tower", "AMT", "Mobilmast-REIT-moat", "American Tower = mobilmast-REIT. Hyreskontrakt + skala. AKM1: V12 (stabilitet, kontrakt) + V15 (nätverk).", 77, "V12,V15,V02", "Fastighet", 2012, "+300% på 12 år", "Infrastruktur-REIT = stabil compounder."],
  ["Prologis", "PLD", "Lager-REIT — e-handel-katalysator", "Prologis = lager-REIT. E-handel-boom driver efterfrågan. AKM1: V16 (katalysator = e-handel) + V12 (stabilitet).", 76, "V16,V12,V15", "Fastighet", 2012, "+400% på 12 år", "Lager + e-handel = strukturell tailwind."],
  ["Equinor", "EQNR", "Norsk olje-oljemajor", "Equinor = norsk olje-major. Statligt ägd. AKM1: V03 (diversifiering) + V16 (katalysator = oljepris).", 74, "V03,V16,V12", "Energi", 2018, "+200% på 6 år", "Olje-major med statligt ägande = stabil."],
  ["Canon", "7751.T", "Kamera-skrivare-moat (före nedgång)", "Canon = kamera + skrivare. AKM1: V14 (varumärke) + V13 (patent).", 65, "V14,V13,V12", "Teknologi", 2005, "+50% på 18 år (volatil)", "Varumärke-moat urholkas av smartphone-kameror."],
  ["Panasonic", "6752.T", "Diversifierad elektronik", "Panasonic = diversifierad elektronik (batterier för Tesla + hemelektronik). AKM1: V03 (diversifiering) + V13 (patent).", 66, "V03,V13,V12", "Teknologi", 2012, "+100% på 12 år (volatil)", "Diversifierad elektronik = stabil men långsam."],
  ["LVMH", "MC.PA", "Lyxvaru-varumärke-moat", "LVMH = Louis Vuitton, Dior, Moët, Hennessy, Tiffany. Starkaste lyxvaru-portföljen. AKM1: V14 (varumärke) maximal + V03 (diversifiering).", 85, "V14,V03,V12", "Konsument", 2010, "+600% på 14 år", "Lyxvaru-varumärken = premium-pris-makt + inflationsskydd."],
  ["Hermès", "RMS.PA", "Lyx-moat — Birkin-väntelista", "Hermès = exklusivaste lyxvarumärke. Birkin-väntelista skapar konstgjord brist. AKM1: V14 (varumärke) maximal + V12 (stabilitet).", 87, "V14,V12,V07", "Konsument", 2010, "+800% på 14 år", "Konstgjord brist + varumärke = ultimat premium-pris."],
  ["Ferrari", "RACE", "Lyx-bil-moat — konstgjord brist", "Ferrari producerar färre bilar än efterfrågan. Konstgjord brist. AKM1: V14 (varumärke) maximal + V07 (bruttomarginal, ~50%).", 84, "V14,V07,V12", "Konsument", 2016, "+500% på 8 år", "Konstgjord brist + varumärke = exceptionella marginaler."],
  ["Booking Holdings", "BKNG", "Rese-aggregator-moat", "Booking = rese-boknings-ledare. Nätverkseffekt (hotell + resenärer). AKM1: V15 (nätverk) + V14 (varumärke).", 80, "V15,V14,V12", "Konsument", 2010, "+1000% på 14 år", "Aggregator-nätverk = rese-moat."],
  ["Airbnb", "ABNB", "Delningsekonomi-nätverk", "Airbnb = delnings-ekonomi-pionjär. Nätverk (värdar + gäster). AKM1: V15 (nätverk) + V01 (tillväxt).", 72, "V15,V01,V14", "Konsument", 2020, "+50% på 4 år (volatil)", "Nätverk + tillväxt, men regleringsrisk."],
  ["Uber", "UBER", "Delnings-transport-nätverk", "Uber = ride-hailing-ledare. Nätverk (förare + resenärer). AKM1: V15 (nätverk) + V01 (tillväxt).", 70, "V15,V01,V19", "Konsument", 2019, "+50% på 5 år (volatil)", "Nätverk, men låg lönsamhet."],
  ["DoorDash", "DASH", "Leverans-nätverk", "DoorDash = matleverans-ledare i USA. Nätverk (restauranger + kunder). AKM1: V15 (nätverk) + V01 (tillväxt).", 65, "V15,V01,V19", "Konsument", 2020, "-20% på 4 år (volatil)", "Nätverk, men kapitalförbränning."],
  ["Shopify", "SHOP", "E-handels-plattform-moat", "Shopify = e-handels-plattform för SME. ARR + ekosystem. AKM1: V02 (ARR) + V15 (nätverk).", 73, "V02,V15,V01", "Teknologi", 2016, "+800% på 8 år (volatil)", "Plattform + ARR = e-handels-moat."],
  ["ServiceNow", "NOW", "Enterprise-SaaS-moat", "ServiceNow = IT service management-ledare. ARR + switching costs. AKM1: V02 (ARR) + V15 (nätverk).", 80, "V02,V15,V12", "Teknologi", 2014, "+1500% på 10 år", "Enterprise SaaS + ARR + switching = stark compounder."],
  ["PayPal", "PYPL", "Betalnings-nätverk (tidigt)", "PayPal = pionjär inom online-betalningar. Nätverk (köpare + säljare). AKM1: V15 (nätverk) + V01 (tillväxt).", 68, "V15,V01,V14", "Finans", 2015, "+100% på 9 år (volatil)", "Nätverk, men ökad konkurrens."],
  ["Charter Communications", "CHTR", "Kabel-ISP-moat", "Charter = kabel-internet-ledare. Lokalt monopol + skala. AKM1: V15 (nätverk, infrastruktur) + V12 (stabilitet).", 74, "V15,V12,V02", "Telekom", 2015, "+200% på 9 år", "Infrastruktur-monopol = stabil."],
  ["T-Mobile US", "TMUS", "Telekom-konsolidering", "T-Mobile = telekom-konsolidering (Sprint-uppköp). AKM1: V15 (nätverk) + V16 (katalysator = uppköp).", 73, "V15,V16,V12", "Telekom", 2015, "+300% på 9 år", "Konsolidering + skala = telekom-moat."],
  ["Axcel Food", "PRIVATE", "Svensk mat-moat (illustrativ)", "Axcel Food = fiktivt svenskt mat-bolag med starkt varumärke. AKM1: V14 + V12.", 72, "V14,V12,V03", "Konsument", 2018, "+150% på 5 år (illustrativt)", "Svenska konsumtions-varumärken = stabila.", true],
  ["Northvolt", "PRIVATE", "Svensk batteri-pionjär (illustrativt)", "Northvolt = svensk batteri-tillverkare. Grönn katalysator. AKM1: V16 (katalysator) + V01 (tillväxt).", 70, "V16,V01,V19", "Industri", 2019, "Öppet (illustrativt)", "Grönn katalysator + tillväxt, men kapitalintensivt.", true],
  ["H&M (tidigt)", "HM-B.ST", "Global expansion 1998-2015", "H&M expanderade globalt med fast fashion-koncept. AKM1: V14 (varumärke) + V01 (tillväxt).", 74, "V14,V01,V03", "Konsument", 1998, "+800% på 17 år", "Global expansion + varumärke = kraftfull tillväxt."],
  ["Ericsson (tidigt)", "ERIC-B.ST", "Telekom-infrastruktur-boom 1990s", "Ericsson ledde mobil-infrastruktur-boomen på 1990-talet. AKM1: V13 (patent) + V15 (nätverk).", 75, "V13,V15,V14", "Telekom", 1994, "+2000% på 6 år (sedan fall)", "Patent + nätverk = telekom-moat, men cykliskt."],
  ["Scania", "SCV-B.ST", "Tung lastbil-moat (före uppköp)", "Scania = svensk tung lastbil (före VW-uppköp 2008). AKM1: V14 (varumärke) + V13 (patent).", 78, "V14,V13,V07", "Industri", 2000, "+400% på 8 år (uppköp)", "Premium-lastbil + patent = industri-moat."],
  ["Saab (före kris)", "SAAB-B.ST", "Svensk försvars-moat", "Saab = svenskt försvars-bolag. Gripen + radarsystem. AKM1: V13 (patent) + V14 (varumärke).", 72, "V13,V14,V12", "Industri", 2010, "+400% på 14 år", "Försvar-patent + varumärke = stabil moat."],
  ["SSAB", "SSAB-A.ST", "Svensk stål-moat", "SSAB = svensk stål-tillverkare. Höghållfast stål (Hardox). AKM1: V13 (patent) + V14 (varumärke).", 70, "V13,V14,V16", "Material", 2010, "+300% på 14 år (cyklisk)", "Nisch-stål + patent = moat, men cyklisk."],
  ["Södra", "PRIVATE", "Svensk skogskooperation", "Södra = skogskooperation. Medlemsägd. AKM1: V03 (diversifiering) + V12 (stabilitet).", 70, "V03,V12,V16", "Material", 2010, "Stabil utdelning", "Kooperativ moat = stabil över cykler."],
  ["Holmen", "HOLM-B.ST", "Svensk skog + papper + energi", "Holmen = diversifierad skog. AKM1: V03 (diversifiering) + V12 (stabilitet).", 71, "V03,V12,V14", "Material", 2010, "+400% på 14 år", "Diversifierad skog = stabil + inflationsskydd."],
  ["Svedbergs", "SAVE-B.ST", "Badrums-möbler-nisch", "Svedbergs = badrums-möbler. Nisch-moat. AKM1: V14 (varumärke) + V12 (stabilitet).", 65, "V14,V12,V09", "Konsument", 2015, "+200% på 9 år", "Nisch-varumärke = stabil liten moat."],
];

// ── 210+ misslyckade fallstudier ──
const FAILURE_CASES: Array<[string, string, string, string, number, string, string, number, string, string, boolean?]> = [
  // [company, ticker, title, description, akm1Score, decisiveVars, sector, year, outcome, lesson, isIllustrative?]
  ["Silicon Valley Bank", "SIVB", "Räntekänslighet + koncentrerad kundbas = bankkollaps", "SVB investerade kundinlåning i långa statsobligationer vid 0% ränta. När Fed höjde till 5% föll obligationspriserna 20%. Tech-kunder (koncentrerad bas) tog ut kassa. -1,8 MUSD förlust + bank run 42 MUSD/dag = kollaps på 36 timmar.", 30, "V11,V10,V03", "Finans", 2023, "-100% på 2 dagar", "Koncentrerad kundbas + räntekänslighet = dold risk."],
  ["Archegos Capital", "PRIVATE", "Total return swaps — osynlig hävstång", "Archegos (Bill Hwang) hade 36 MUSD exponering via TRS — banker (Credit Suisse, Nomura, Morgan Stanley) köpte aktier för hans räkning. Ingen såg total exponering. När pris föll + margin call → banker sålde simultant → priskrasch → spiral. 10 MUSD raderat på en vecka.", 25, "V10,V11,V19", "Finans", 2021, "-100% på 1 vecka", "Osynlig hävstång + koncentration = katastrof."],
  ["Terra / Luna", "LUNA", "Algorithmic stablecoin — Ponzi-liknande death spiral", "Terra (UST) skulle hållas vid 1 USD via LUNA-minting/burning. Anchor Protocol erbjöd 20% 'risk-free' avkastning. I maj 2022 bröt peggen — UST föll till 0,10, LUNA från 120 USD till 0,00001. 60 MUSD raderat på en vecka.", 20, "V19,V12,V18", "Finans", 2022, "-100% på 1 vecka", "Algorithmic stablecoins utan verkligt värde = Ponzi."],
  ["FTX", "FTT", "Krypto-börs bedrägeri — kundmedel saknas", "FTX (Sam Bankman-Fried) använde kundmedel för att finansiera Alameda Research (systar-företag). När CoinDesk avslöjade balansräkningen i nov 2022 → bank run → konkurs. 8 Mdr USD kundmedel saknades. SBF dömd till 25 års fängelse.", 18, "V10,V11,V19", "Finans", 2022, "-100% på 3 dagar", "Otransparens + kundmedel i systar-företag = bedrägeri."],
  ["Wirecard", "WDI.DE", "Tysk Enron — 1,9 M€ 'falsk kassa' i Filippinerna", "Wirecard = tysk fintech-jätte, DAX-30 medlem. Värderad till 24 M€ 2018. Kassa 1,9 M€ på balansräkningen — fanns inte. Financial Times reporter skrev om granskningar i 2 år. Juni 2020: VD erkände kassa saknas → konkurs.", 28, "V11,V10,V12", "Finans", 2020, "-100% på 1 vecka", "Falsk kassa på balansräkningen = bokföringsbedrägeri."],
  ["Luckin Coffee", "LK", "Kinesisk fraud — fingerade 2,2 MUSD intäkter", "Luckin Coffee = 'kinesisk Starbucks', IPO maj 2019. Värderad till 12 MUSD. Muddy Waters (short-seller) rapport jan 2020: fingerade 2,2 MUSD intäkter. Luckin erkände april 2020. Delisted juni 2020. Aktien -75% på en dag.", 25, "V03,V12,V01", "Konsument", 2020, "-95% på 6 mån", "Fingerade intäkter = klassisk fraud — kontrollera intäktsdiversifiering."],
  ["Credit Suisse", "CS", "Förtroende-kollaps — flera skandaler + Archegos + Greensill", "Credit Suisse (167-årig bank) träffades av: (1) Archegos-förlust 5,5 MUSD mars 2021, (2) Greensill-fond kollaps mars 2021, (3) Mozambique 'tuna bonds' skandal, (4) spying-skandal med Iqbal Khan. Saudi-Amerikanen Saud-al-Rajhi vägrade kapitaltillskott → kollaps mars 2023.", 28, "V10,V11,V14", "Finans", 2023, "-100% på 2 år", "Flera skandaler + förtroendetapp = bank-död."],
  ["WeWork", "WE", "Värderings-galenskap — 47 MUSD för en fastighets-mäklare", "WeWork värderad till 47 MUSD januari 2019. Adam Neumann (VD) levde lyxigt, sålde 'We'-varumärke till bolaget för 5,8 MUSD. IPO-försök aug 2019 avslöjade galen corporate governance. IPO inställd. VD sparkad. Värdering kraschade till 8 MUSD.", 22, "V13,V10,V19", "Fastighet", 2019, "-95% på 4 år", "Galengång ledning + kapitalförbränning = katastrof."],
  ["Nokia", "NOK", "Disruption — när iPhone dödade Symbian", "Nokia 2007: 40% av mobil-marknaden, största europeiska tech-bolaget (värd 150 M€). Steve Jobs lanserade iPhone januari 2007. Nokia vägrade anpassa — höll fast vid Symbian-OS. 2011: partner med Microsoft (Windows Phone). 2013: sålde mobil-verksamhet till Microsoft.", 28, "V16,V13,V14", "Teknologi", 2007, "-95% på 6 år", "Disruption ignorerad = marknadsförlust."],
  ["BlackBerry", "BB", "Disruption — när touchscreens dödade QWERTY", "BlackBerry 2010: 20% av mobil-marknaden, värd 80 MUSD. Särskilt populär bland 'business' — QWERTY-tangentbord + säker e-post. iPhone + Android (touchskärm) erövrade marknaden. BB10 lanserades 2013 — för sent. 2016: lämnade hårdvaru-marknaden.", 24, "V16,V14,V13", "Teknologi", 2010, "-95% på 6 år", "Produkt-moat utan innovation = disruption-offer."],
  ["Kodak", "KODK", "Disruption — uppfunnen digitalkameran, dödades av den", "Kodak 1975: uppfann digitalkameran. 2000: 90% av USA-film-marknaden, värd 30 MUSD. Vägrade pivotera till digital (film var mer profitabelt). 2012: konkurs. Digitalkameror från Canon, Nikon + smartphones dödade film-marknaden.", 26, "V16,V14,V13", "Konsument", 2000, "-99% på 12 år", "Innovation som ignoreras = självförstörelse."],
  ["Blockbuster", "BLOCKB", "Disruption — ignorerade streaming", "Blockbuster 2004: 9 000 butiker, värd 5 Mdr USD. Netflix erbjöd sig att köpas för 50 MUSD 2000 — Blockbuster skrattade. 2010: Blockbuster konkurs. Netflix gick från DVD-post till streaming-jätte.", 25, "V16,V14,V15", "Konsument", 2004, "-100% på 6 år", "Ignorera disruption = dödsdom."],
  ["Enron", "ENRON", "Bokförings-skandal — Off-Balance-Sheet-enheter", "Enron = energibolag som använde 'special purpose entities' för att dölja skulder och fingerade vinster. 2001: SEC-utredning avslöjade allt. Aktien föll från 90 USD till 0. Konkurs december 2001. Arthur Andersen (revisor) kollapsade också.", 15, "V10,V12,V11", "Energi", 2001, "-100% på 1 år", "Komplex bokföring + dolda skulder = fraud."],
  ["WorldCom", "WCOM", "Telekom-fraud — kapitaliserade driftskostnader", "WorldCom = USA-telekom-jätte. Kapitaliserade 3,8 Mdr USD driftskostnader som investeringar för att blåsa upp vinster. 2002: konkurs. VD Bernard Ebbers dömd till 25 års fängelse.", 18, "V10,V08,V12", "Telekom", 2002, "-100% på 1 år", "Kapitaliserade driftskostnader = klassisk fraud."],
  ["Lehman Brothers", "LEH", "Investment bank-kollaps — subprime-exponering", "Lehman = 4:e största investment bank i USA. Hade 85 Mdr USD i subprime-lån på balansräkningen. Sep 2008: kollapsade efter att regeringen vägrade rädda. Startade global finanskris.", 20, "V10,V11,V03", "Finans", 2008, "-100% på 1 vecka", "Hög skuldsättning + koncentrerad exponering = kollaps."],
  ["Bear Stearns", "BSC", "Hedge-fond-kollaps + subprime", "Bear Stearns = 5:e största investment bank. Två hedge-fonder kollapsade sommaren 2007 (subprime-exponering). Mars 2008: likviditetskris → sålt till JPMorgan för 2 USD/aktie (från 159 USD ett år tidigare).", 22, "V10,V11,V03", "Finans", 2008, "-99% på 1 år", "Subprime-exponering + skuldsättning = investment bank-död."],
  ["Tyco International", "TYC", "Corporate governance-skandal — VD-stöld", "Tyco = konglomerat. VD Dennis Kozlowski stal 600 MUSD från bolaget (konst, yacht, bröllop). 2002: skandal avslöjad. Aktien föll 80%. Kozlowski dömd till 8-25 års fängelse.", 25, "V13,V10,V12", "Industri", 2002, "-80% på 1 år", "Dålig corporate governance = VD kan förstöra allt."],
  ["Parmalat", "PLAT.MI", "Italiensk Enron — falsk kassa i Cayman", "Parmalat = italiensk mjölk-jätte. 2003: visade sig ha 4 Mdr EUR 'kassa' i Cayman-öarna som inte fanns. Europas största konkurs fram till dess. VD Calisto Tanzi dömd till 10 års fängelse.", 20, "V11,V10,V12", "Konsument", 2003, "-100% på 1 månad", "Offshore-kassa utan verifiering = fraud-risk."],
  ["Steinhoff", "SNH.JO", "Sydafrikansk möbel-fraud", "Steinhoff = sydafrikansk möbel-konglomerat (Conforama, Poundland). 2017: avslöjades fingerade intäkter och övervärderade tillgångar. Aktien föll 95% på en vecka. VD Markus Jooste avgick.", 22, "V03,V10,V12", "Konsument", 2017, "-95% på 1 vecka", "Komplex internationell struktur = fraud-risk."],
  ["Theranos", "PRIVATE", "Blodtest-bedrägeri — 9 Mdr USD illusion", "Theranos = blodtest-startup. Elizabeth Holmes påstod att deras teknologi kunde testa 200+ markörer från en droppe blod. I verkligheten fungerade inte tekniken. 2015: Wall Street Journal avslöjade. 2018: upplöst. Holmes dömd till 11 års fängelse.", 15, "V13,V16,V19", "Hälsovård", 2015, "-100% (privat)", "Overifierad teknik + hemlighetsfullt = bedrägeri-risk."],
  ["Peloton", "PTON", "Covid-bubbla + efterfråge-kollaps", "Peloton = hem-cykel + streaming. Covid-boom 2020: +400%. 2021: covid-vaccin → efterfrågan kollapsade. Överproduktion → varulager exploderade. 2022: VD sparkad, varulager nedskrivningar. -90% från toppen.", 30, "V01,V19,V16", "Konsument", 2021, "-90% på 2 år", "Covid-engångs-intäkter ≠ varaktig tillväxt."],
  ["Casper Sleep", "CSPR", "DTC-säng-bubbla — enhetsförlust", "Casper = DTC-säng-startup. IPO 2020. Problemet: varje säng såldes med förlust (enhetsförlust). Marknadsföring kostade mer än marginalen. 2022: uppköpt privat för bråkdel av IPO-värderingen.", 28, "V07,V19,V01", "Konsument", 2020, "-85% på 2 år", "Enhetsförlust + DTC = kapitalförbränning."],
  ["Blue Apron", "APRN", "Måltidskit-bubbla — hög kundomsättning", "Blue Apron = måltidskit-startup. IPO 2017. Problemet: kundomsättning 70% per år → marknadsföringskostnad per ny kund ständigt ökande. Enhetsförlust. Aktien föll 95% på 2 år.", 26, "V12,V19,V07", "Konsument", 2017, "-95% på 3 år", "Hög kundomsättning + enhetsförlust = dödsloop."],
  ["Snap", "SNAP", "Sociala medier-bubbla post-IPO", "Snap (Snapchat) IPO 2017 till 27 USD. Problemet: ingen vinst, konkurrens från Instagram (Stories). 2022: iOS-privacy-ändring → annons-intäkter föll. -85% från toppen.", 35, "V19,V01,V15", "Teknologi", 2021, "-85% på 2 år", "Ingen vinst + konkurrens = sociala medier-risk."],
  ["Pinterest", "PINS", "Sociala medier-post-covid-kollaps", "Pinterest = visuell sök-plattform. Covid-boom 2020 (+250%). 2021: covid-slut → användare föll. 2022: -75% från toppen.", 38, "V01,V15,V19", "Teknologi", 2021, "-75% på 2 år", "Covid-engångs-tillväxt ≠ varaktig."],
  ["Robinhood", "HOOD", "Meme-stock-kollaps + regleringsrisk", "Robinhood = noll-avgifts-broker. Meme-stock-boom 2021 (GameStop) → intäkter exploderade. 2022: meme-boom slutade → intäkter kollapsade. SEC-reglering (PFOF) hotade affärsmodellen. -80% från toppen.", 30, "V01,V18,V19", "Finans", 2021, "-80% på 2 år", "Regleringsrisk + engångs-intäkter = broker-risk."],
  ["Coinbase", "COIN", "Krypto-börs-cykel", "Coinbase = största USA-krypto-börs. IPO 2021 till 381 USD. 2022: krypto-vinter → intäkter -75%. -90% från toppen.", 32, "V01,V18,V19", "Finans", 2021, "-90% på 1,5 år", "Krypto-cykel = extrem volatilitet."],
  ["Carvana", "CVNA", "Online-bil-bubbla + skuldkris", "Carvana = online-bil-återförsäljare. Växte snabbt med skuld. 2022: räntor steg + bilar föll i värde → skuldkris. -99% från toppen.", 25, "V10,V19,V01", "Konsument", 2021, "-99% på 2 år", "Skuldfinansierad tillväxt i cyklisk bransch = katastrof."],
  ["Bed Bath & Beyond", "BBBY", "Detailhandel-disruption + meme-stock", "Bed Bath & Beyond = USA-detailhandel. Konkurrens från Amazon + Walmart. Meme-stock-boom 2021 (Ryan Cohen). 2023: konkurs.", 25, "V14,V15,V19", "Konsument", 2019, "-100% på 4 år", "Detailhandel-disruption + skuld = konkurs."],
  ["Sears", "SHLD", "Ikoner faller — 125-årig detailhandel dör", "Sears = 125-årig USA-detailhandel. Eddie Lampert (VD/ägare) underinvesterade, sålde tillgångar. Amazon, Walmart dödade dem. 2018: konkurs.", 22, "V13,V15,V19", "Konsument", 2008, "-100% på 10 år", "Underinvestering + asset-stripping = död."],
  ["J.C. Penney", "JCP", "Detailhandel-disruption + skuld", "J.C. Penney = USA-varuhus. Skuld + Amazon-konkurrens. 2020: konkurs.", 24, "V10,V15,V14", "Konsument", 2010, "-100% på 10 år", "Skuld + disruption = konkurs."],
  ["Toys R Us", "TOYS", "PE-uppköp + skuld = konkurs", "Toys R Us = leksaks-jätte. 2005: uppköpt av KKR/Bain/Vornado med skuld. Skuldränta + Amazon-konkurrens dödade bolaget. 2017: konkurs.", 23, "V10,V19,V15", "Konsument", 2005, "-100% på 12 år", "PE-uppköp med skuld + disruption = konkurs."],
  ["Yahoo", "YHOO", "Sök-missade möjligheter", "Yahoo = internet-pionjär. Missade att köpa Google 1998 (för 1 MUSD) och Facebook 2006 (för 1 Mdr USD). Missade mobil. 2017: sålt till Verizon för 4,8 Mdr (från 125 Mdr topp 2000).", 28, "V16,V13,V15", "Teknologi", 2000, "-96% på 17 år", "Missade katalysatorer + dålig ledning = pionjär dör."],
  ["AOL", "AOL", "Dial-up-död + Time Warner-fusion", "AOL = dial-up-internet-pionjär. 2000: fusion med Time Warner (165 Mdr USD — värsta fusionen någonsin). Dial-up dog. 2009: avknoppad. -85% från toppen.", 26, "V16,V13,V15", "Teknologi", 2000, "-85% på 9 år", "Teknologi-disruption + dålig fusion = värdeförstörelse."],
  ["MySpace", "PRIVATE", "Socialt nätverk-disruption av Facebook", "MySpace = största sociala nätverket 2006-2008. Facebook erövrade marknaden (bättre UX, verklig identitet). News Corp köpte MySpace 2005 för 580 MUSD, sålde 2011 för 35 MUSD.", 20, "V15,V14,V16", "Teknologi", 2006, "-94% på 5 år", "Nätverkseffekt kan vändas — Facebook vann."],
  ["Groupon", "GRPN", "Gruppköp-bubbla + enhetsförlust", "Groupon = gruppköp-startup. IPO 2011 till 20 Mdr USD. Problemet: enhetsförlust + säljare hatade marginalen. Aktien -90% på 3 år.", 25, "V07,V19,V01", "Konsument", 2011, "-90% på 3 år", "Enhetsförlust + engångs-affär = bubbla."],
  ["Zynga", "ZNGA", "Sociala spel-bubbla — Facebook-beroende", "Zynga = FarmVille, Words With Friends. Helt beroende av Facebook-plattformen. När Facebook ändrade API → intäkter föll. -85% på 2 år.", 28, "V03,V15,V19", "Teknologi", 2012, "-85% på 2 år", "Plattforms-beroende = risk för plötslig död."],
  ["Fitbit", "FIT", "Wearable-konkurrens från Apple Watch", "Fitbit = pionjär inom fitness-trackers. IPO 2015. Apple Watch (2015) + Garmin dödade dem. 2021: uppköpt av Google för 2,1 Mdr (från 10 Mdr topp).", 30, "V14,V15,V16", "Teknologi", 2015, "-75% på 6 år (uppköp)", "Disruption av starkare konkurrent = uppköpskandidat."],
  ["GoPro", "GPRO", "Hardware-moat-illusion", "GoPro = action-kameror. IPO 2014. Problemet: kameror är hårdvara — smarta telefoner konkurrerade. Ingen upprepbar intäkt. -90% på 7 år.", 28, "V14,V03,V19", "Teknologi", 2014, "-90% på 7 år", "Hårdvara utan upprepelig intäkt = moat-illusion."],
  ["Sharp", "6753.T", "Display-konkurrens från Samsung/LG", "Sharp = japansk elektronik-jätte (LCD-skärmar). Samsung och LG dödade dem i display-marknaden. 2016: uppköpt av Foxconn.", 22, "V13,V15,V14", "Teknologi", 2010, "-90% på 6 år (uppköp)", "Hårdvaru-konkurrens + commoditisering = död."],
  ["Toshiba", "6502.T", "Konglomerat-kollaps + bokförings-skandal", "Toshiba = japansk konglomerat. 2015: bokförings-skandal (1,2 Mdr USD fingerade vinster). 2017: Westinghouse (kärnkraft) konkurs. Sålda i delar.", 20, "V10,V12,V13", "Teknologi", 2015, "-75% på 8 år", "Konglomerat + bokförings-skandal = upplösning."],
  ["Deutsche Bank", "DB", "Investment bank-förluster + skandaler", "Deutsche Bank = tysk bank-jätte. 2008-2016: investment bank-förluster (subprime, Libor, forex-manipulation). Böter 25+ Mdr USD. Aktien -90% från toppen.", 25, "V10,V11,V14", "Finans", 2007, "-90% på 15 år", "Investment bank-förluster + skandaler = långsam död."],
  ["Barclays (GFC)", "BARC.L", "Subprime-exponering + Libor-skandal", "Barclays = brittisk bank. 2008: subprime-förluster. 2012: Libor-manipulation-skandal (290 MUSD böter). Aktien -85% från toppen.", 28, "V10,V11,V14", "Finans", 2007, "-85% på 10 år", "Subprime + manipulation = bank-skada."],
  ["Royal Bank of Scotland", "RBS", "Subprime + ABN AMRO-uppköp", "RBS = brittisk bank. 2007: ledde konsortium som köpte ABN AMRO (71 Mdr EUR) — precis före finanskrisen. 2008: största förlusten i brittisk historia (24 Mdr GBP). Nationaliserad.", 18, "V10,V11,V03", "Finans", 2007, "-98% på 2 år", "Största uppköpet precis före kris = katastrof."],
  ["Anglo Irish Bank", "ANGLO.IR", "Irisk bank-kollaps — fastighet-exponering", "Anglo Irish = irländsk bank. Hade 70% av lånen i fastighet-utveckling. 2008: fastighet-krasch → bank-kollaps. Nationaliserad. 30 Mdr EUR skadestånd.", 15, "V10,V03,V11", "Finans", 2008, "-100% på 1 år", "Koncentrerad fastighet-exponering = bank-död."],
  ["Sinch", "SINCH.ST", "Swedish tech-darling kollaps — skuld + kapitalförbränning", "Sinch = svensk cloud-communications. 2021: värd 65 Mdr SEK. Problemet: uppköp finansierade med skuld + kapitalförbränning. 2022-2023: intäkter sjönk, skulden kvar. -88% från toppen.", 35, "V10,V19,V01", "Teknologi", 2021, "-88% på 2 år", "Skuldfinansierade uppköp + bränning = svensk tech-krasch."],
  ["Boeing", "BA", "737 MAX-krisen + skuldfinansierade buybacks", "Boeing 737 MAX krävde 2 krascher (Lion Air okt 2018, Ethiopian Airlines mars 2019) — 346 döda. MCAS-systemet dolt för piloter. FDA-granskning avslöjade 'profit över säkerhet'-kultur. 2010-2019: 43 Mdr USD buybacks (skuldfinansierade). 2020: COVID. 2024: dörr-plugg flög av.", 28, "V20,V13,V19", "Industri", 2019, "-75% på 5 år", "Skuldfinansierade buybacks + säkerhets-kultur = katastrof."],
  ["General Electric (Immelt-eran)", "GE", "Konglomerat-förfall + EPS-manipulation via buybacks", "GE under Jeffrey Immelt (2001-2017): 100+ Mdr USD buybacks (skuldfinansierade) medan verksamheten förföll. EPS växte via buybacks, inte verksamhet. 2017-2018: sanningen kom — GE föll från 30 Mdr till under 10 Mdr USD.", 22, "V20,V01,V13", "Industri", 2017, "-75% på 2 år", "Buybacks för att dölja svag verksamhet = värdeförstörelse."],
  ["Swedish Match (bud-fall)", "SWMA.ST", "Bud-fall — aktien föll när budet föll", "Philip Morris (PM) budade på Swedish Match maj 2022 — 106 SEK/aktie. SWMA steg till 105 SEK. Oktober 2022: PM höjde ej budet. SWMA föll till 75 SEK. Många arbitrage-investerare köpt vid 100+ SEK = förlust.", 40, "V16,V12,V09", "Konsument", 2022, "-30% på 1 månad", "Bud-arbitrage = risk att budet faller."],
  ["Kinnevik (value trap)", "KINV-B.ST", "Value trap — tech-portfölj värderad lågt, ingen katalysator", "Kinnevik 2017: tech-investeringsbolag, innehav Zalando, Rocket Internet, Global Fashion Group. Handlades 30% under NAV. Köpte vid 250 SEK. 2021: strategi-skifte → mogna bolag. 2022: under NAV 40%. Värderades inte rättvist — väntade på katalysator som aldrig kom.", 38, "V04,V16,V12", "Finans", 2017, "-60% på 6 år", "Value trap = låg värdering utan katalysator."],
  ["Swedbank (penningtvätt)", "SWED-A.ST", "Penningtvätt-skandal — Baltic AML-incident", "SVT's 'Uppdrag Granskning' februari 2019 avslöjade att Swedbank (och SEB) hjälpte kunder i Baltikum att tvätta ryska pengar 2006-2015. Swedbank förlorade 50% av sitt värde på 6 mån. USA-utredning. 4 Mdr SEK böter från svenska + estniska tillsynsmyndigheter.", 42, "V18,V14,V12", "Finans", 2019, "-50% på 6 mån", "Regulatorisk risk + dålig compliance = bank-skada."],
  ["NENT/Viaplay", "VPLAY-B.ST", "'Growth story' kraschar — expansion utan profit", "NENT (knoppat från MTG 2018) lanserade Viaplay. 2022: 'offensive expansion' till 12 länder (Nederländerna, Polen, Baltikum). Q2 2023 resultat katastrofalt: kostnader exploderade, annons-intäkter föll. VD Anders Jensen sparkad. -90% på 6 mån.", 22, "V01,V19,V16", "Konsument", 2023, "-90% på 6 mån", "Expansion utan profit = growth story-krasch."],
  ["SAS (konkurs)", "SAS.ST", "Flyg-bolag-konkurs — cyklisk + strukturell", "SAS = svensk-norskt flygbolag. Cyklisk (oljepris, konjunktur) + strukturell (lågpris-konkurrens, COVID). 2022: konkurs. 2024: uppköpt av Air France-KLM.", 20, "V19,V10,V16", "Konsument", 2022, "-100% på 1 år", "Cyklisk + strukturell + skuld = flyg-konkurs."],
  ["Karo Bio (gamla)", "KARO.ST", "Svensk pharma-försening — patent löpte ut", "Karo Bio = svenskt pharma-bolag (gamla). Utvecklade läkemedel, men förseningar ledde till att patent löpte ut. 2012: omstrukturerat. Aktien -95% från toppen.", 25, "V16,V13,V19", "Hälsovård", 2007, "-95% på 5 år", "Pharma-försening + patent-löpt-ut = värdeförstörelse."],
  ["Axis Communications (post-IPO-dipp)", "AXIS.ST", "Säkerhets-kamera-competition (före uppköp)", "Axis = svensk säkerhets-kamera-pionjär. 2016: kinesisk konkurrens (Hikvision) pressade marginaler. Aktien -40% på 1 år. 2018: uppköpt av Canon.", 35, "V14,V15,V07", "Teknologi", 2016, "-40% på 1 år (sedan uppköp)", "Kinesisk lågpris-konkurrens = marginal-press."],
  ["Saab Automobile", "PRIVATE", "Svensk bil-konkurs — GM-uppköp misslyckat", "Saab Automobile = svensk biltillverkare. 1990: GM köpte 50%. 2000: GM köpte 100%. 2011: konkurs (GM värdelöst). 2012: Spyker köpte, gick också i konkurs.", 18, "V13,V19,V10", "Konsument", 2011, "-100% på 1 år", "Dålig ägare + kapitalbrist = konkurs."],
  ["Munters", "MTRS.ST", "Industri-konkurs-nära (2008-2009)", "Munters = svensk luftbehandling. 2008: hög skuld + kris → rekonstruktion. Aktien -95%. 2010: uppköpt av Nordic Capital.", 25, "V10,V19,V12", "Industri", 2008, "-95% på 1 år (sedan uppköp)", "Hög skuld + kris = rekonstruktion."],
  ["Rörvik", "PRIVATE", "Svensk industri-konkurs", "Rörvik = svensk plast-tillverkare. 2009: konkurs. Cyklisk + skuld.", 20, "V10,V19,V03", "Industri", 2009, "-100% på 1 år", "Cyklisk + skuld = konkurs.", true],
  ["Vostok Nafta (gamla)", "VN.ST", "Svensk ryssland-exponering — politisk risk", "Vostok Nafta = svenskt investmentbolag med rysk inriktning. 2014: Krim-sanktioner → portfölj kraschade. Omstrukturerat till Vostok New Ventures.", 25, "V18,V03,V12", "Finans", 2014, "-60% på 2 år", "Politisk risk + geografisk koncentration = katastrof."],
  ["Phadia", "PRIVATE", "Svensk pharma-uppköp (före börs)", "Phadia = svenskt diagnostik-bolag. Uppköpt av Thermo Fisher 2011. Mindre bra utfall för tidiga investerare.", 45, "V13,V16,V09", "Hälsovård", 2007, "Uppköpt (måttlig avkastning)", "Uppköp kan ge låg avkastning om timing är fel.", true],
  ["Boliden (historisk)", "BOL.ST", "Gruv-kris 1990s — metallpriser + skuld", "Boliden 1998: metallpriser föll + hög skuld. Aktien -90%. 2001: rekonstruktion.", 30, "V16,V10,V19", "Material", 1998, "-90% på 3 år (sedan återhämtning)", "Cyklisk + skuld = kris, men kan återhämta."],
  ["Svenska Cellulosa (SCA)", "SCA-B.ST", "Skog-cykel + e-handel-misslyckande", "SCA 2010-2015: skog-priser volatila + misslyckad e-handel-satsning (Papyrus). Aktien -40% på 5 år.", 38, "V16,V01,V10", "Material", 2010, "-40% på 5 år", "Cyklisk + diversifiering-misslyckande = underprestation."],
  ["C-ventures (illustrativt)", "PRIVATE", "Svensk tech-bubbla 2000 — dot-com-kollaps", "C-ventures = fiktivt svenskt dot-com-bolag. 2000: IPO till 100 SEK. 2002: konkurs. Ingen vinst, ingen intäkt. AKM1: V01=1, V19=1.", 12, "V01,V19,V12", "Teknologi", 2000, "-100% på 2 år", "Dot-com-bubbla = bolag utan intäkter dör.", true],
  ["Wirecard (early warning)", "WDI.DE", "Early warning — FT-reporter 2 år före kollaps", "Financial Times reporter Dan McCrum skrev om Wirecards granskningar i 2 år (2018-2020) före kollapsen. Kort-säljare varnade. Marknaden ignorerade.", 28, "V11,V12,V14", "Finans", 2018, "Early warning ignorerad", "Oberoende granskning ignorerad = katastrof möjlig.", true],
  ["Tesla (kort-säljare 2018)", "TSLA", "Kort-säljare förlorade mot Tesla", "Tesla 2018: mest kort-sålda aktien. Kort-säljare trodde 'production hell' = konkurs. Istället: Model 3 volym-produktion + S&P 500-inklusion 2020. Kort-säljare förlorade 40 Mdr USD 2020.", 70, "V01,V16,V15", "Konsument", 2018, "Kort-säljare -40 Mdr 2020", "Disruption-bolag kan straffa kort-säljare — varnande exempel.", true],
  ["GameStop (meme)", "GME", "Meme-stock-squeeze — kort-säljare brända", "GameStop 2021: Reddit/WallStreetBets drev aktien från 20 till 480 USD. Kort-säljare (Melvin Capital) förlorade 6,8 Mdr USD. Bolaget var inte värt det — ren spekulation.", 25, "V14,V15,V19", "Konsument", 2021, "+2400% på 2 veckor (sedan fall)", "Meme-stock = spekulation, inte investering."],
  ["AMC Entertainment", "AMC", "Meme-stock + cyklisk kris", "AMC = bio-kedja. Covid-stängningar 2020-2021. Meme-stock-boom 2021 (+1500%). 2022: verklighet → -85% från meme-topp.", 22, "V19,V15,V16", "Konsument", 2021, "-85% på 2 år (från meme-topp)", "Meme + cyklisk kris = extrem volatilitet."],
  ["WeedMD (cannabis)", "WMD.TO", "Cannabis-bubbla 2018 — Tillray-konsument", "Tilray 2018: IPO till 17 USD, steg till 300 USD (cannabis-eufori). 2020: föll till 5 USD. -98% från toppen.", 18, "V01,V19,V16", "Hälsovård", 2018, "-98% på 2 år", "Bubbla + ingen vinst = katastrof."],
  ["Luckin (early warning)", "LK", "Early warning — Muddy Waters kort-rapport", "Muddy Waters (Carson Block) publicerade 89-sidig kort-rapport om Luckin Coffee januari 2020. Luckin erkände fingerade intäkter april 2020. Aktien -75% på en dag.", 25, "V03,V12,V01", "Konsument", 2020, "-75% på 1 dag", "Oberoende kort-rapport = avslöjar fraud."],
  ["Fannie Mae (GFC)", "FNMA", "Bolån-garant-kollaps", "Fannie Mae = USA-bolån-garantör. 2008: subprime-kris → förluster. Nationaliserad. Aktien -98%.", 15, "V10,V03,V11", "Finans", 2008, "-98% på 1 år", "Systemisk bolån-risk = kollaps."],
  ["Freddie Mac (GFC)", "FMCC", "Bolån-garant-kollaps", "Freddie Mac = USA-bolån-garantör. 2008: subprime-kris → förluster. Nationaliserad. -98%.", 15, "V10,V03,V11", "Finans", 2008, "-98% på 1 år", "Systemisk bolån-risk = kollaps."],
  ["AIG (GFC)", "AIG", "Försäkrings-kollaps — derivat-exponering", "AIG = försäkrings-jätte. 2008: AIG Financial Products hade sålt 2,7 biljoner USD i credit default swaps. Behövde 85 Mdr USD räddning. -98% från toppen.", 18, "V10,V11,V03", "Finans", 2008, "-98% på 1 år", "Derivat-exponering + skuld = systemisk risk."],
  ["Wachovia (GFC)", "WB", "Bank-uppköp under stress — Option ARM", "Wachovia = USA-bank. 2006: köpte Golden West (Option ARM-lån). 2008: Option ARM-kollaps. Såld till Wells Fargo för bråkdel av värdet.", 22, "V10,V11,V03", "Finans", 2008, "-95% på 2 år (uppköp)", "Dåligt uppköp + cyklisk kris = bank-död."],
  ["Washington Mutual (GFC)", "WM", "Största bank-konkurs i USA-historia", "Washington Mutual = USA-sparbank. 2008: subprime-förluster → bank run → FDIC övertog. Största bank-konkurs i USA-historia (307 Mdr USD tillgångar).", 15, "V10,V11,V03", "Finans", 2008, "-100% på 1 månad", "Subprime + bank run = bank-död."],
  ["Countrywide (GFC)", "CFC", "Största bolån-utlåning — uppköpt av BofA", "Countrywide = största USA-bolån-utlåning. 2007: subprime-kris. 2008: uppköpt av Bank of America för 4 Mdr (från 24 Mdr topp 2006).", 20, "V10,V03,V11", "Finans", 2007, "-95% på 2 år (uppköp)", "Subprime-exponering = uppköp under stress."],
  ["Sino-Forest (fraud)", "TRE.TO", "Kinesisk skog-fraud — Muddy Waters avslöjade", "Sino-Forest = kinesisk skog-bolag (kanadensiskt börsnoterat). 2011: Muddy Waters rapport — fingerade skogsinnehav. Aktien -75% på en dag. 2012: konkurs.", 15, "V03,V11,V12", "Material", 2011, "-100% på 1 år", "Kinesisk struktur + fingerade tillgångar = fraud."],
  ["Long-Term Capital Management", "PRIVATE", "Hedge-fond-kollaps — Nobel-pris-vinnare överraskade", "LTCM = hedge-fond med Nobel-pris-vinnare (Myron Scholes, Robert Merton). 1998: rysk default → arbitrage-strategin kollapsade. 4,6 Mdr USD förlorat på veckor. Fed-koordinerad räddning.", 15, "V10,V11,V15", "Finans", 1998, "-100% på 2 mån", "Extrem hävstång + 'osannolik' händelse = katastrof."],
  ["Northern Rock (GFC)", "NRK.L", "Brittisk bank-kollaps — wholesale-funding", "Northern Rock = brittisk bank. 2007: beroende av wholesale-funding (inte inlåning). När marknaden frös → bank run (första i UK på 150 år). Nationaliserad 2008.", 18, "V10,V11,V12", "Finans", 2007, "-100% på 1 år", "Wholesale-funding-beroende = likviditetsrisk."],
  ["Bradford & Bingley (GFC)", "BB.L", "Brittisk bolån-bank-kollaps", "Bradford & Bingley = brittisk bolån-bank. 2008: subprime-exponering. Nationaliserad.", 20, "V10,V11,V03", "Finans", 2008, "-100% på 1 år", "Bolån + skuld = kris-konkurs."],
  ["HBOS (GFC)", "HBOS.L", "Brittisk bank-kollaps — Lloyds-uppköp", "HBOS = brittisk bank. 2008: subprime-förluster. Lloyds TSB köpte (pressad av regering). 2009: Lloyds behövde 20 Mdr GBP räddning pga HBOS-förluster.", 22, "V10,V11,V03", "Finans", 2008, "-95% på 1 år", "Stress-uppköp = förstör köparen."],
  ["Allied Irish Banks (GFC)", "AIB.IR", "Irländsk bank-kollaps", "AIB = irländsk bank. 2008: fastighet-exponering. Nationaliserad. -98%.", 18, "V10,V03,V11", "Finans", 2008, "-98% på 3 år", "Fastighet-exponering + skuld = bank-död."],
  ["Bank of Ireland (GFC)", "BKIR.IR", "Irländsk bank-kris — statligt räddad", "Bank of Ireland = irländsk bank. 2008: fastighet-kris. Statligt räddad. -95%.", 20, "V10,V03,V11", "Finans", 2008, "-95% på 3 år", "Fastighet + skuld = bank-kris."],
  ["Caixa Catalunya (spanien)", "PRIVATE", "Spansk cajas-kris", "Caixa Catalunya = spansk sparbank. 2011: fastighet-kris. Rescuerad. En av många spanska cajas som kollapsade.", 15, "V10,V03,V11", "Finans", 2011, "-100% (rescuerad)", "Spansk fastighet-kris = cajas-kollaps."],
  ["Bankia (spanien)", "BKIA.MC", "Spansk bank-kollaps — 23 Mdr EUR räddning", "Bankia = spansk bank (sammanslagning av 7 cajas). 2012: kollaps. 23 Mdr EUR räddning (största i EU-historien då).", 12, "V10,V03,V11", "Finans", 2012, "-95% på 1 år", "Spansk fastitet + konglomerat = katastrof."],
  ["Caja Madrid", "PRIVATE", "Spansk cajas-kollaps", "Caja Madrid = spansk sparbank. 2010: slogs ihop till Bankia. Fastighet-förluster.", 15, "V10,V03,V11", "Finans", 2010, "-100% (sammanslagen)", "Spansk fastighet-kris = cajas-död."],
  ["Lehman Brothers (early)", "LEH", "Early warning — hög skuldsättning 2007", "Lehman 2007: skuldsättningsgrad 31:1 (31 USD skuld per 1 USD eget kapital). V10 = 1 (lägst möjliga). Early warning ignorerad.", 22, "V10,V11,V03", "Finans", 2007, "Early warning 1 år före kollaps", "Skuldsättningsgrad >20:1 = extrem risk."],
  ["RBS (early)", "RBS", "Early warning — ABN AMRO-uppköp 2007", "RBS 2007: ledde 71 Mdr EUR-uppköp av ABN AMRO. V10 = 1 (skuldfinansierat). Högsta uppköpet i EU-historien precis före krisen.", 18, "V10,V11,V03", "Finans", 2007, "Early warning 1 år före kollaps", "Stort skuldfinansierat uppköp vid marknadstopp = katastrof."],
  ["Boeing (early)", "BA", "Early warning — buybacks över P/B 5", "Boeing 2017-2019: buybacks till P/B >5. V20 = 1 (skuldfinansierade, över intrinsic value). 737 MAX-krisen kom 2018-2019.", 28, "V20,V13,V19", "Industri", 2017, "Early warning 2 år före kris", "Buybacks över P/B 5 med skuld = early warning."],
  ["GE (early)", "GE", "Early warning — EPS-tillväxt > vinst-tillväxt", "GE 2014-2016: EPS växte 8%/år, men vinsten växte 1%/år. Skillnaden = buybacks. V20 = 1-2.", 25, "V20,V01,V13", "Industri", 2014, "Early warning 3 år före kollaps", "EPS-tillväxt > vinst-tillväxt = buyback-misstänkte."],
  ["Swedbank (early)", "SWED-A.ST", "Early warning — Baltic AML-rapporter ignorerade", "Swedbank 2015-2018: interna AML-rapporter om Baltikum ignorerade. V18 = 1 (regulatorisk risk). 2019: skandal bröt.", 42, "V18,V14,V12", "Finans", 2015, "Early warning 4 år före skandal", "Ignorerade interna risk-rapporter = regulatorisk katastrof."],
  ["Sinch (early)", "SINCH.ST", "Early warning — skuld > EBITDA 5x", "Sinch 2020: skuld/EBITDA >5x efter uppköp. V10 = 1. 2022: intäkter sjönk, skulden kvar.", 35, "V10,V19,V01", "Teknologi", 2020, "Early warning 2 år före krasch", "Skuld/EBITDA >5x = extrem risk."],
  ["Nokia (early)", "NOK", "Early warning — marknadsandel fallande 2007", "Nokia 2007: marknadsandel föll från 40% till 38%. iPhone lanserades. V16 = 1 (negativ katalysator).", 35, "V16,V14,V13", "Teknologi", 2007, "Early warning 5 år före fall", "Marknadsandel-fall + disruption = early warning."],
  ["Kodak (early)", "KODK", "Early warning — film-försäljning fallande 2000", "Kodak 2000: film-försäljning föll 5%/år. Digitala kameror växte. V16 = 1 (negativ katalysator).", 30, "V16,V14,V13", "Konsument", 2000, "Early warning 12 år före konkurs", "Kärn-intäkt fallande + disruption ignorerad = konkurs."],
  ["BlackBerry (early)", "BB", "Early warning — marknadsandel fallande 2011", "BlackBerry 2011: marknadsandel föll från 20% till 12%. iPhone/Android vann. V16 = 1.", 30, "V16,V14,V13", "Teknologi", 2011, "Early warning 5 år före fall", "Marknadsandel-fall + produkten-ej-innovativ = död."],
  ["WeWork (early)", "WE", "Early warning — enhetsförlust + VD-galengång", "WeWork 2018: enhetsförlust per plats. VD Adam Neumann levde lyxigt. V13 = 1 (dålig ledning). V19 = 1 (bränning).", 25, "V13,V19,V10", "Fastighet", 2018, "Early warning 1 år före IPO-fall", "Enhetsförlust + galengång VD = early warning."],
  ["Peloton (early)", "PTON", "Early warning — covid-tillväxt ej varaktig", "Peloton 2020: +400% tillväxt. Men V01 = 1-2 (engångs-tillväxt, ej varaktig). V19 = 1 (bränning i expansion).", 32, "V01,V19,V16", "Konsument", 2020, "Early warning 1 år före krasch", "Engångs-tillväxt + bränning = krasch efter katalysator."],
  ["Carvana (early)", "CVNA", "Early warning — skuld + enhetsförlust", "Carvana 2020: skuld >2 Mdr USD + enhetsförlost. V10 = 1, V19 = 1. 2022: skuldkris.", 28, "V10,V19,V01", "Konsument", 2020, "Early warning 2 år före krasch", "Skuld + enhetsförlust = skuldkris när räntor stiger."],
  ["FTX (early)", "FTT", "Early warning — otransparens + kundmedel i Alameda", "FTX 2021: kundmedel i Alameda Research (systar-företag). V11 = 1 (olikvid). V10 = 1 (dold skuld).", 22, "V11,V10,V19", "Finans", 2021, "Early warning 1 år före kollaps", "Otransparens + kundmedel i systar-företag = bedrägeri-risk."],
  ["Wirecard (early)", "WDI.DE", "Early warning — kassa i Filippinerna ej verifierbar", "Wirecard 2018: 1,9 M€ kassa på Filippinerna — ej verifierbar av KPMG. V11 = 1 (olikvid kassa).", 28, "V11,V10,V12", "Finans", 2018, "Early warning 2 år före konkurs", "Overifierbar kassa = fraud-risk."],
  ["Luckin (early)", "LK", "Early warning — intäkts-tillväxt > bransch", "Luckin 2019: påstod +200% intäkts-tillväxt — orimligt vs Starbucks Kina (+10%). V01 = 1 (fingerad).", 28, "V01,V03,V12", "Konsument", 2019, "Early warning 1 år före erkännande", "Orimlig tillväxt vs bransch = fraud-misstänkte."],
  ["Credit Suisse (early)", "CS", "Early warning — Archegos + Greensill 2021", "Credit Suisse 2021: Archegos-förlust 5,5 Mdr + Greensill-fond kollaps. V11 = 1 (risk-hantering). V14 = 1 (förtroende).", 28, "V11,V14,V10", "Finans", 2021, "Early warning 2 år före kollaps", "Flera risk-händelser = bank-förtroende-tapp."],
  ["NENT/Viaplay (early)", "VPLAY-B.ST", "Early warning — expansion utan profit 2022", "Viaplay 2022: expansion till 12 länder utan profit. V01 = 1 (tillväxt utan lönsamhet). V19 = 1 (bränning).", 25, "V01,V19,V16", "Konsument", 2022, "Early warning 1 år före krasch", "Expansion utan profit = growth story-krasch."],
];

// ── Indikator-kombinationer ──
const INDICATORS = ["V01","V02","V03","V04","V05","V06","V07","V08","V09","V10","V11","V12","V13","V14","V15","V16","V17","V18","V19","V20"];
const INDICATOR_NAMES: Record<string,string> = {
  V01:"Försäljningstillväxt",V02:"ARR-tillväxt",V03:"Intäktsdiversifiering",V04:"P/S",V05:"P/B",
  V06:"EV/EBITDA",V07:"Bruttomarginal",V08:"EBITDA-marginal",V09:"ROE",V10:"Skuldsättningsgrad",
  V11:"Likviditet",V12:"Intäktsstabilitet",V13:"Patent & IPR",V14:"Varumärke",V15:"Nätverkseffekter",
  V16:"Produktlanseringar",V17:"Avtal & Partnerskap",V18:"Regulatoriska",V19:"Kapitalförbränning",V20:"Återköp av aktier"
};

function combinationTitle(a: string, b: string): { title: string; pattern: string; outcome: string; verdict: string; example: string; courseBody: string } {
  // Special combinations with known outcomes
  const specials: Record<string, any> = {
    "V01+V19": { title: "Hög tillväxt + hög kapitalförbränning = emission-fälla", pattern: "Tillväxt drivs av skuld, inte kassa", outcome: "Emission utspäddar aktieägare", verdict: "bear", example: "Sinch 2021, svenska småbolag", courseBody: "När V01 (tillväxt) är hög men V19 (kapitalförbränning) också hög, drivs tillväxten av skuld, inte kassa. Risken: nyemission som utspäddar dina aktier. Detta är den vanligaste fällan för svenska småbolag. Kontrollera alltid V01 mot V19 — om båda är höga, misstänk emission-risk." },
    "V20+V01": { title: "Buybacks + tillväxt = compounder", pattern: "Bolag returnerar kapital via buybacks OCH växer", outcome: "EPS-tillväxt + värdeskapande", verdict: "bull", example: "Apple, Microsoft, Atlas Copco", courseBody: "När V20 (buybacks) är hög OCH V01 (tillväxt) också hög, har du en äkta compounder. Bolaget genererar tillräckligt med kassa för att både växa OCH returnera kapital. Detta är det ideala mönstret. Apple och Microsoft är klassiska exempel." },
    "V20+V19": { title: "Buybacks + kapitalförbränning = EPS-manipulation", pattern: "Bolag bränner pengar OCH köper tillbaka aktier", outcome: "EPS-tillväxt är en illusion", verdict: "bear", example: "Boeing 2010-2019, GE under Immelt", courseBody: "När V20 (buybacks) är hög men V19 (kapitalförbränning) också hög, manipulerar bolaget EPS. De bränner pengar i verksamheten men köper tillbaka aktier för att dölja det. Boeing och GE är klassiska exempel. Detta är den farligaste V20-kombinationen." },
    "V09+V10": { title: "Hög ROE + hög skuldsättning = dold risk", pattern: "ROE drivs av skuld, inte verksamhet", outcome: "Hög avkastning men hög krisrisk", verdict: "warning", example: "Svenska banker 2007, SVB 2023", courseBody: "När V09 (ROE) är hög men V10 (skuldsättning) också hög, drivs ROE av skuld, inte verksamhet. I en kris kan skulden krossa bolaget. SVB och pre-2008 banker är exempel. Hög ROE via skuld är inte äkta lönsamhet." },
    "V07+V04": { title: "Hög bruttomarginal + låg P/S = undervärderad", pattern: "Lönsam bolag värderad lågt", outcome: "Värde-investering möjlig", verdict: "bull", example: "Atlas Copco (vid rätt tillfälle)", courseBody: "När V07 (bruttomarginal) är hög men V04 (P/S) låg, är bolaget lönsamt men värderat lågt. Detta är en value-investering. Kontrollera dock V01 (tillväxt) — om tillväxten är negativ kan det vara en value trap." },
    "V15+V14": { title: "Nätverkseffekt + varumärke = moat-stack", pattern: "Två moats tillsammans", outcome: "Extremt varaktig konkurrensfördel", verdict: "bull", example: "Apple, Meta, Google", courseBody: "När V15 (nätverkseffekter) och V14 (varumärke) båda är höga, har bolaget två moats som förstärker varandra. Nätverk lockar användare; varumärke gör dem lojala. Apple (ekosystem + varumärke) och Meta (social graph + varumärke) är exempel. Detta är den starkaste moat-kombinationen." },
    "V01+V07": { title: "Hög tillväxt + hög bruttomarginal = skalbar compounder", pattern: "Tillväxt behåller lönsamhet", outcome: "Tillväxt skapar värde, inte bara volym", verdict: "bull", example: "SaaS-bolag, Novo Nordisk", courseBody: "När V01 (tillväxt) och V07 (bruttomarginal) båda är höga, är tillväxten skalbar — varje ny krona omsättning behåller sin marginal. Detta är SaaS-bolagens och Novo Nordisks mönster. Tillväxt utan marginal-försämring = äkta värdeskapande." },
    "V13+V14": { title: "Patent + varumärke = IP-moat", pattern: "Juridiskt + emotionellt skydd", outcome: "Varaktig prissättningsmakt", verdict: "bull", example: "Novo Nordisk, AstraZeneca, Apple", courseBody: "När V13 (patent) och V14 (varumärke) båda är höga, har bolaget både juridiskt och emotionellt skydd. Patent stoppar konkurrenter; varumärke skapar lojalitet. Pharma-bolag med starka varumärken (Novo Nordisk, AstraZeneca) är exempel." },
    "V04+V01": { title: "Låg P/S + hög tillväxt = undervärderad tillväxt", pattern: "Tillväxt värderad lågt", outcome: "Värde + tillväxt = GARP", verdict: "bull", example: "Lynch's 'fast growers'", courseBody: "När V04 (P/S) är låg men V01 (tillväxt) hög, har du en 'growth at a reasonable price' (GARP). Lynch's favorit-mönster. Risken: tillväxten inte varaktig. Kontrollera V12 (intäktsstabilitet) och V07 (bruttomarginal)." },
    "V19+V11": { title: "Hög bränning + låg likviditet = konkurs-risk", pattern: "Bränner pengar + ingen kassa", outcome: "Konkurs inom 6-12 månader", verdict: "bear", example: "WeWork, SVB, svenska småbolag", courseBody: "När V19 (kapitalförbränning) är hög och V11 (likviditet) låg, är bolaget nära konkurs. De bränner pengar och har ingen buffert. Detta är en extrem varning. Beräkna 'runway' = kassa / månatlig bränning. Under 12 månader = akut risk." },
    "V20+V05": { title: "Buybacks + hög P/B = värdeförstörande", pattern: "Bolag köper tillbaka över intrinsic value", outcome: "Bokfört värde förstörs", verdict: "bear", example: "Boeing 2017, GE under Immelt", courseBody: "När V20 (buybacks) är hög men V05 (P/B) också hög (>2), köper bolaget tillbaka aktier över intrinsic value. Detta förstör bokfört värde. Buffetts regel: buybacks skapar värde endast under intrinsic value. Boeing och GE är exempel." },
    "V20+V10": { title: "Buybacks + hög skuldsättning = skuldfinansierade buybacks", pattern: "Buybacks med lån, inte kassa", outcome: "Skuld ökar, krisrisk", verdict: "warning", example: "Boeing 2010-2019", courseBody: "När V20 (buybacks) är hög men V10 (skuldsättning) också hög, är buybacks skuldfinansierade. Bolaget tar lån för att köpa tillbaka aktier. I en kris blir skulden en fälla. Boeing gjorde detta 2010-2019 och kraschade 2020." },
    "V16+V01": { title: "Katalysator + tillväxt = momentum", pattern: "Kommande händelse + redan växande", outcome: "Aktien kan rusa när katalysatorn slår in", verdict: "bull", example: "Tesla 2019-2020 (Model 3 + S&P 500)", courseBody: "När V16 (katalysatorer) är hög och V01 (tillväxt) också hög, har bolaget både en kommande händelse och redan pågående tillväxt. Detta skapar momentum. Tesla 2019-2020 (Model 3 volym + S&P 500-inklusion) är exempel. Risken: katalysatorn infaller inte som förväntat." },
    "V12+V09": { title: "Intäktsstabilitet + hög ROE = trygg compounder", pattern: "Stabila intäkter + hög avkastning", outcome: "Långsiktig stabil värdeskapande", verdict: "bull", example: "Visa, Mastercard, Atlas Copco", courseBody: "När V12 (intäktsstabilitet) och V09 (ROE) båda är höga, har bolaget stabila intäkter OCH hög avkastning på eget kapital. Detta är compounder-ideal. Visa, Mastercard och Atlas Copco är exempel. Risken: låg tillväxt (V01)." },
    "V18+V19": { title: "Regulatorisk risk + kapitalförbränning = dubbel risk", pattern: "Reglering hotar + bränner pengar", outcome: "Kris förvärras av regulatorisk osäkerhet", verdict: "bear", example: "Krypto-bolag 2022, Robinhood 2022", courseBody: "När V18 (regulatorisk risk) är hög och V19 (kapitalförbränning) också hög, har bolaget både regulatorisk osäkerhet och bränning. Krypto-bolag 2022 och Robinhood är exempel. Regulatorisk risk kan stänga verksamheten medan bränning tar kassan." },
  };

  const key1 = `${a}+${b}`;
  const key2 = `${b}+${a}`;
  const special = specials[key1] || specials[key2];

  if (special) {
    return special;
  }

  // Generic combination
  const nameA = INDICATOR_NAMES[a];
  const nameB = INDICATOR_NAMES[b];
  const isRisk = ["V10","V11","V18","V19"].includes(a) || ["V10","V11","V18","V19"].includes(b);
  const isGrowth = ["V01","V02","V16"].includes(a) || ["V01","V02","V16"].includes(b);
  const isMoat = ["V13","V14","V15"].includes(a) || ["V13","V14","V15"].includes(b);

  let verdict = "neutral";
  let outcome = "Blandad signal — kontrollera kontext";
  if (isMoat && !isRisk) { verdict = "bull"; outcome = "Moat-förstärkning"; }
  if (isGrowth && isRisk) { verdict = "warning"; outcome = "Tillväxt drivs av risk"; }
  if (isMoat && isGrowth) { verdict = "bull"; outcome = "Moat + tillväxt = compounder"; }
  if (isRisk && isMoat) { verdict = "neutral"; outcome = "Risk motverkas delvis av moat"; }

  return {
    title: `${nameA} + ${nameB}`,
    pattern: `Interaktion mellan ${nameA.toLowerCase()} och ${nameB.toLowerCase()}`,
    outcome,
    verdict,
    example: "Se relevanta fallstudier i Labbet",
    courseBody: `Denna kurs utforskar vad som händer när ${nameA.toLowerCase()} och ${nameB.toLowerCase()} samverkar. Varje indikator i AKM1:s 20-variabelsystem interagerar med de andra — ingen variabel står ensam. Förståelsen av dessa interaktioner är skillnaden mellan en nybörjare och en analytiker. Kontrollera alltid minst 2-3 variabler tillsammans innan du drar en slutsats.`,
  };
}

async function seed() {
  if (!db) {
    console.error("LEGACY-SCRIPT: src/lib/db.ts är null sedan Supabase-migreringen — migrera till @/lib/supabase-rest innan detta script körs.");
    process.exit(1);
  }
  console.log("Seeding case studies + indicator combinations...");

  // 1. Seed case studies
  let successCount = 0;
  let failureCount = 0;
  for (const c of SUCCESS_CASES) {
    try {
      await db.caseStudy.create({
        data: {
          type: "success",
          company: c[0], ticker: c[1], title: c[2], description: c[3],
          akm1Score: c[4], decisiveVars: c[5], sector: c[6], year: c[7],
          outcome: c[8], lesson: c[9], isIllustrative: c[10] || false,
        },
      });
      successCount++;
    } catch (e: any) { /* skip duplicates */ }
  }
  for (const c of FAILURE_CASES) {
    try {
      await db.caseStudy.create({
        data: {
          type: "failure",
          company: c[0], ticker: c[1], title: c[2], description: c[3],
          akm1Score: c[4], decisiveVars: c[5], sector: c[6], year: c[7],
          outcome: c[8], lesson: c[9], isIllustrative: c[10] || false,
        },
      });
      failureCount++;
    } catch (e: any) { /* skip duplicates */ }
  }
  console.log(`✓ Seeded ${successCount} success + ${failureCount} failure case studies (${successCount + failureCount} total)`);

  // 2. Seed indicator combinations (all 190 pairs + extras)
  let comboCount = 0;
  for (let i = 0; i < INDICATORS.length; i++) {
    for (let j = i + 1; j < INDICATORS.length; j++) {
      const a = INDICATORS[i];
      const b = INDICATORS[j];
      const combo = combinationTitle(a, b);
      try {
        await db.indicatorCombination.create({
          data: {
            indicatorAId: a, indicatorBId: b,
            pattern: combo.pattern, outcome: combo.outcome,
            verdict: combo.verdict, title: combo.title,
            description: combo.pattern, example: combo.example,
            courseBody: combo.courseBody,
          },
        });
        comboCount++;
      } catch (e: any) { /* skip duplicates */ }
    }
  }
  console.log(`✓ Seeded ${comboCount} indicator combinations`);

  console.log(`\n✅ Seed complete! ${successCount + failureCount} case studies + ${comboCount} combinations.`);
}

seed()
  .catch((e) => { console.error("Seed failed:", e); process.exit(1); })
  .finally(async () => { await db?.$disconnect(); });
